/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import type { CostCalculationConfig } from './types'

export const COST_CALCULATION_OPTION_KEY = 'FlatkeyCostCalculation'

export const DEFAULT_COST_CALCULATION: CostCalculationConfig = {
  assumptions: {
    listPrice: 10,
    bonus: 35,
    coupon: 5,
    seedanceSellFactor: 0.9,
    otherSellFactor: 0.8,
    inputTokens: 1000000,
    outputTokens: 1000000,
    nonTokenUsage: 1,
  },
  discounts: {
    openai: 0.75,
    anthropic: 0.75,
    moonshot: 0.75,
    national: 0.8,
    bytedance: 0.85,
    other: 0,
  },
  fields: [],
  models: [
    {
      name: 'seedance-2.0-mini',
      vendor: 'ByteDance',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.020176,
      costDiscount: null,
      note: '项目网页定价；Seedance价格与项目网页/截图核对一致。',
    },
    {
      name: 'deepseek-v3.2',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.266,
      officialOutput: 0.44400001800000005,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-sonnet-4-5-20250929',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.43,
      officialOutput: 2.15,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'seedance-2.0-pro',
      vendor: 'ByteDance',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.041312,
      costDiscount: null,
      note: '项目网页定价；Seedance价格与项目网页/截图核对一致。',
    },
    {
      name: 'grok-imagine-image-pro',
      vendor: 'xAI',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.05,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'minimax-m2.5',
      vendor: 'MiniMax',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 1.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-opus-4-7',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-robotics-er-1.6-preview',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 1.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.4-mini',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.75,
      officialOutput: 4.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'grok-imagine-video',
      vendor: 'xAI',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.09,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'glm-5.2',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.4,
      officialOutput: 4.3999999999998,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'kimi-k3',
      vendor: 'Moonshot AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 3,
      officialOutput: 15,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-flash',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.1,
      officialOutput: 0.4,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-plus',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.4,
      officialOutput: 2.4000000000000004,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-fable-5',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 10,
      officialOutput: 50,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-2.5-pro-tts',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1,
      officialOutput: 20,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-image-2',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens + 非Token',
      officialInput: 5,
      officialOutput: 30,
      officialNonToken: 8,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-flash',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.09,
      officialOutput: 0.7100000099999999,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-sonnet-4-6',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 3,
      officialOutput: 15,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3.1-pro-preview',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 12,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-plus-2026-02-15',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.4,
      officialOutput: 2.4000000000000004,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-haiku-4-5-20251001',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 1,
      officialOutput: 5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-flash-image',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens + USD/图片',
      officialInput: 0.3,
      officialOutput: 30,
      officialNonToken: 30,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-2.5-pro',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.125,
      officialOutput: 9,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.1-flash-lite-image',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens + USD/图片',
      officialInput: 0.25,
      officialOutput: 30,
      officialNonToken: 30,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3.1-flash-lite-preview',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.25,
      officialOutput: 1.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-flash-lite',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.09,
      officialOutput: 0.36,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.4-nano',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.2,
      officialOutput: 1.25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'macaron-v1-venti',
      vendor: 'Macaron',
      billingUnit: 'USD/1M tokens',
      officialInput: 7,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'glm-5-turbo',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.2,
      officialOutput: 4,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-opus-5',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-pro-latest',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 12,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'veo-3.1-generate-preview',
      vendor: 'Google',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.4,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'eleven_multilingual_v2',
      vendor: 'ElevenLabs',
      billingUnit: 'USD/1M tokens',
      officialInput: 100,
      officialOutput: 100,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3-flash-preview',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.07,
      officialOutput: 0.42999999000000005,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.6-flash',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.5,
      officialOutput: 7.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.6-sol',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 30,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5-mini',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.04,
      officialOutput: 0.32,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'macaron-v1-coding-venti',
      vendor: 'Macaron',
      billingUnit: 'USD/1M tokens',
      officialInput: 5.2,
      officialOutput: 18.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemma-4-26b-a4b-it',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.25,
      officialOutput: 0.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-4o',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 2.5,
      officialOutput: 10,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v4-pro-0813',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.32,
      officialOutput: 3.96,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；分时价格按高峰价列入；实际高峰/非高峰由项目表达式决定。',
    },
    {
      name: 'kimi-k2.5',
      vendor: 'Moonshot AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.6,
      officialOutput: 3,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'minimax-m2',
      vendor: 'MiniMax',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 1.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-flash-preview-tts',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.5,
      officialOutput: 10,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-embedding-001',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.15,
      officialOutput: 0,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'eleven_sound_v1',
      vendor: 'ElevenLabs',
      billingUnit: 'USD/1M tokens',
      officialInput: 2000,
      officialOutput: 2000,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'grok-imagine-video-1.5',
      vendor: 'xAI',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.11,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'kimi-k2.6',
      vendor: 'Moonshot AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.95,
      officialOutput: 3.9999999999999996,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-35b-a3b',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.245,
      officialOutput: 1.96,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.6-plus',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.5,
      officialOutput: 3,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-flash-tts',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.5,
      officialOutput: 10,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.1-flash-tts-preview',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1,
      officialOutput: 20,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.6-sol-fk-cx',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 30,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'MiniMax-H3',
      vendor: 'MiniMax',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.08,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'glm-5',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 1,
      officialOutput: 3.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-opus-4-8',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'claude-opus-4-5',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3.7-flash',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.5,
      officialOutput: 7.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-397b-a17b',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.588,
      officialOutput: 3.5279999999999996,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.7-plus',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.4,
      officialOutput: 1.6,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'sonilo-video-to-music',
      vendor: 'Sonilo',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.009,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'macaron-v1-tall',
      vendor: 'Macaron',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.8,
      officialOutput: 10,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'seedance-2.5',
      vendor: 'ByteDance',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.084,
      costDiscount: null,
      note: '项目网页定价；Seedance价格与项目网页/截图核对一致。',
    },
    {
      name: 'gpt-5.5',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 30,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.1-flash-lite',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.25,
      officialOutput: 1.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-2.5-pro-preview-tts',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1,
      officialOutput: 20,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'glm-4.7',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.6,
      officialOutput: 2.1999999999999997,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v3',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.4,
      officialOutput: 1.3,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v3.1',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.21,
      officialOutput: 0.79000000000005,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.5-flash-lite',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 2.4999999999999,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.6-terra',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 12,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'seedance-2.0',
      vendor: 'ByteDance',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.041312,
      costDiscount: null,
      note: '项目网页定价；Seedance价格与项目网页/截图核对一致。',
    },
    {
      name: 'claude-sonnet-5',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 10,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3.1-flash-image',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens + USD/图片',
      officialInput: 0.5,
      officialOutput: 60,
      officialNonToken: 60,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gpt-4.1-mini',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.4,
      officialOutput: 1.6,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'grok-imagine-image-quality',
      vendor: 'xAI',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.05,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v4-pro',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.32,
      officialOutput: 3.96,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；分时价格按高峰价列入；实际高峰/非高峰由项目表达式决定。',
    },
    {
      name: 'glm-5.1',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.4,
      officialOutput: 4.3999999999999995,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-flash-lite-latest',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.1,
      officialOutput: 0.4,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'nano-banana-pro-preview',
      vendor: '其他',
      billingUnit: 'USD/1M tokens + USD/图片',
      officialInput: 2,
      officialOutput: 120,
      officialNonToken: 120,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3-pro-image',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens + USD/图片',
      officialInput: 2,
      officialOutput: 120,
      officialNonToken: 120,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'veo-3.1-fast-generate-preview',
      vendor: 'Google',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.15,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'grok-imagine-image',
      vendor: 'xAI',
      billingUnit: 'USD/请求',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.02,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'minimax-m2.7',
      vendor: 'MiniMax',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 1.2,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'seedance-2.0-fast',
      vendor: 'ByteDance',
      billingUnit: 'USD/秒',
      officialInput: 0,
      officialOutput: 0,
      officialNonToken: 0.031705,
      costDiscount: null,
      note: '项目网页定价；Seedance价格与项目网页/截图核对一致。',
    },
    {
      name: 'gpt-4o-mini',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.15,
      officialOutput: 0.6,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.6-max-preview',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.3,
      officialOutput: 7.800000000000001,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v3.2-thinking',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.29,
      officialOutput: 0.42000000000001,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.4',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 2.5,
      officialOutput: 15,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gpt-5.6-luna',
      vendor: 'OpenAI',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.2,
      officialOutput: 1.2000000000000002,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.5-27b',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 2.4,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemini-3.5-flash',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.5,
      officialOutput: 9,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'gemma-4-31b-it',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.18,
      officialOutput: 0.50000004,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'deepseek-v4-flash',
      vendor: 'DeepSeek',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.44,
      officialOutput: 1.32,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；分时价格按高峰价列入；实际高峰/非高峰由项目表达式决定。',
    },
    {
      name: 'qwen3.8-max',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 6,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'glm-5.3',
      vendor: 'Zhipu AI',
      billingUnit: 'USD/1M tokens',
      officialInput: 1.4,
      officialOutput: 4.3999999999998,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-opus-4-6',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 5,
      officialOutput: 25,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-flash-latest',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 0.3,
      officialOutput: 2.4999998999999997,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'qwen3.7-max',
      vendor: 'Alibaba',
      billingUnit: 'USD/1M tokens',
      officialInput: 2.5,
      officialOutput: 2.5,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
    {
      name: 'claude-sonnet-4-5',
      vendor: 'Anthropic',
      billingUnit: 'USD/1M tokens',
      officialInput: 3,
      officialOutput: 15,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页表达式还原；输入/输出由项目billing_expr还原。',
    },
    {
      name: 'gemini-3.1-pro-preview-customtools',
      vendor: 'Google',
      billingUnit: 'USD/1M tokens',
      officialInput: 2,
      officialOutput: 12,
      officialNonToken: 0,
      costDiscount: null,
      note: '项目网页定价',
    },
  ],
}

export function parseCostCalculation(value: string): CostCalculationConfig {
  try {
    const parsed = JSON.parse(value) as CostCalculationConfig
    if (
      !parsed.assumptions ||
      !parsed.discounts ||
      !Array.isArray(parsed.models)
    ) {
      return DEFAULT_COST_CALCULATION
    }
    return parsed
  } catch {
    return DEFAULT_COST_CALCULATION
  }
}
