import type { Locale } from "./locales";
import { withIdFallback } from "@/lib/locales";

export type BlogCopy = {
  title: string;
  description: string;
  searchPlaceholder: string;
  search: string;
  clear: string;
  readMore: string;
  previous: string;
  next: string;
  pageOf: string;
  ctaTitle: string;
  ctaDescription: string;
  ctaButton: string;
  emptyTitle: string;
  emptyDescription: string;
  latestInCategory: string;
  onThisPage: string;
  relatedArticles: string;
  backToBlog: string;
  articleFallbackTitle: string;
  articleFallbackDescription: string;
  categoryTitle: string;
  categoryFallbackDescription: string;
};

export const BLOG_COPY: Record<Locale, BlogCopy> =withIdFallback({
  en: {
    title: "flatkey.ai Blog",
    description: "Insights, product notes, and implementation guides for teams building on AI APIs.",
    searchPlaceholder: "Search articles",
    search: "Search",
    clear: "Clear",
    readMore: "Read more",
    previous: "Previous",
    next: "Next",
    pageOf: "Page {{page}} of {{total}}",
    ctaTitle: "Build faster with one AI gateway.",
    ctaDescription: "Use flatkey.ai to manage models, keys, billing, and observability from one API platform.",
    ctaButton: "Get started",
    emptyTitle: "No posts found",
    emptyDescription: "Try a different search or category.",
    latestInCategory: "Latest articles in {{category}}.",
    onThisPage: "On this page",
    relatedArticles: "Related articles",
    backToBlog: "Back to Blog",
    articleFallbackTitle: "Blog article",
    articleFallbackDescription: "Article from flatkey.ai.",
    categoryTitle: "Blog category: {{category}}",
    categoryFallbackDescription: "Browse flatkey.ai blog articles by category.",
  },
  zh: {
    title: "flatkey.ai 博客",
    description: "面向 AI API 产品团队的洞察、产品更新和实施指南。",
    searchPlaceholder: "搜索文章",
    search: "搜索",
    clear: "清除",
    readMore: "阅读全文",
    previous: "上一页",
    next: "下一页",
    pageOf: "第 {{page}} 页，共 {{total}} 页",
    ctaTitle: "用一个 AI 网关更快上线。",
    ctaDescription: "使用 flatkey.ai 在一个 API 平台中管理模型、密钥、计费和可观测性。",
    ctaButton: "开始使用",
    emptyTitle: "未找到文章",
    emptyDescription: "请尝试其他搜索词或分类。",
    latestInCategory: "{{category}} 的最新文章。",
    onThisPage: "本文目录",
    relatedArticles: "相关文章",
    backToBlog: "返回博客",
    articleFallbackTitle: "博客文章",
    articleFallbackDescription: "来自 flatkey.ai 的文章。",
    categoryTitle: "博客分类：{{category}}",
    categoryFallbackDescription: "按分类浏览 flatkey.ai 博客文章。",
  },
  es: {
    title: "Blog de flatkey.ai",
    description: "Ideas, notas de producto y guías de implementación para equipos que crean sobre APIs de IA.",
    searchPlaceholder: "Buscar artículos",
    search: "Buscar",
    clear: "Limpiar",
    readMore: "Leer más",
    previous: "Anterior",
    next: "Siguiente",
    pageOf: "Página {{page}} de {{total}}",
    ctaTitle: "Crea más rápido con una sola pasarela de IA.",
    ctaDescription: "Usa flatkey.ai para gestionar modelos, claves, facturación y observabilidad desde una plataforma API.",
    ctaButton: "Empezar",
    emptyTitle: "No se encontraron publicaciones",
    emptyDescription: "Prueba con otra búsqueda o categoría.",
    latestInCategory: "Últimos artículos en {{category}}.",
    onThisPage: "En esta página",
    relatedArticles: "Artículos relacionados",
    backToBlog: "Volver al blog",
    articleFallbackTitle: "Artículo del blog",
    articleFallbackDescription: "Artículo de flatkey.ai.",
    categoryTitle: "Categoría del blog: {{category}}",
    categoryFallbackDescription: "Explora artículos del blog de flatkey.ai por categoría.",
  },
  fr: {
    title: "Blog flatkey.ai",
    description: "Analyses, notes produit et guides d'implémentation pour les équipes qui construisent avec des API d'IA.",
    searchPlaceholder: "Rechercher des articles",
    search: "Rechercher",
    clear: "Effacer",
    readMore: "Lire la suite",
    previous: "Précédent",
    next: "Suivant",
    pageOf: "Page {{page}} sur {{total}}",
    ctaTitle: "Construisez plus vite avec une seule passerelle IA.",
    ctaDescription: "Utilisez flatkey.ai pour gérer modèles, clés, facturation et observabilité depuis une plateforme API.",
    ctaButton: "Commencer",
    emptyTitle: "Aucun article trouvé",
    emptyDescription: "Essayez une autre recherche ou catégorie.",
    latestInCategory: "Derniers articles dans {{category}}.",
    onThisPage: "Dans cette page",
    relatedArticles: "Articles associés",
    backToBlog: "Retour au blog",
    articleFallbackTitle: "Article de blog",
    articleFallbackDescription: "Article de flatkey.ai.",
    categoryTitle: "Catégorie du blog : {{category}}",
    categoryFallbackDescription: "Parcourez les articles du blog flatkey.ai par catégorie.",
  },
  pt: {
    title: "Blog da flatkey.ai",
    description: "Insights, notas de produto e guias de implementação para equipes que criam com APIs de IA.",
    searchPlaceholder: "Pesquisar artigos",
    search: "Pesquisar",
    clear: "Limpar",
    readMore: "Ler mais",
    previous: "Anterior",
    next: "Próxima",
    pageOf: "Página {{page}} de {{total}}",
    ctaTitle: "Crie mais rápido com um único gateway de IA.",
    ctaDescription: "Use a flatkey.ai para gerenciar modelos, chaves, cobrança e observabilidade em uma plataforma de API.",
    ctaButton: "Começar",
    emptyTitle: "Nenhum post encontrado",
    emptyDescription: "Tente outra busca ou categoria.",
    latestInCategory: "Artigos mais recentes em {{category}}.",
    onThisPage: "Nesta página",
    relatedArticles: "Artigos relacionados",
    backToBlog: "Voltar ao blog",
    articleFallbackTitle: "Artigo do blog",
    articleFallbackDescription: "Artigo da flatkey.ai.",
    categoryTitle: "Categoria do blog: {{category}}",
    categoryFallbackDescription: "Navegue pelos artigos do blog da flatkey.ai por categoria.",
  },
  ru: {
    title: "Блог flatkey.ai",
    description: "Идеи, заметки о продукте и руководства по внедрению для команд, создающих продукты на AI API.",
    searchPlaceholder: "Искать статьи",
    search: "Поиск",
    clear: "Очистить",
    readMore: "Читать дальше",
    previous: "Назад",
    next: "Вперед",
    pageOf: "Страница {{page}} из {{total}}",
    ctaTitle: "Запускайте быстрее с единым AI-шлюзом.",
    ctaDescription: "Используйте flatkey.ai, чтобы управлять моделями, ключами, биллингом и наблюдаемостью на одной API-платформе.",
    ctaButton: "Начать",
    emptyTitle: "Публикации не найдены",
    emptyDescription: "Попробуйте другой поиск или категорию.",
    latestInCategory: "Последние статьи в категории {{category}}.",
    onThisPage: "На этой странице",
    relatedArticles: "Похожие статьи",
    backToBlog: "Назад в блог",
    articleFallbackTitle: "Статья блога",
    articleFallbackDescription: "Статья от flatkey.ai.",
    categoryTitle: "Категория блога: {{category}}",
    categoryFallbackDescription: "Просматривайте статьи блога flatkey.ai по категориям.",
  },
  ja: {
    title: "flatkey.ai ブログ",
    description: "AI API を使って開発するチーム向けのインサイト、製品ノート、実装ガイド。",
    searchPlaceholder: "記事を検索",
    search: "検索",
    clear: "クリア",
    readMore: "続きを読む",
    previous: "前へ",
    next: "次へ",
    pageOf: "{{total}} ページ中 {{page}} ページ",
    ctaTitle: "1つの AI ゲートウェイで開発を加速。",
    ctaDescription: "flatkey.ai なら、モデル、キー、課金、可観測性を1つの API プラットフォームで管理できます。",
    ctaButton: "始める",
    emptyTitle: "記事が見つかりません",
    emptyDescription: "別の検索語句またはカテゴリを試してください。",
    latestInCategory: "{{category}} の最新記事。",
    onThisPage: "このページの内容",
    relatedArticles: "関連記事",
    backToBlog: "ブログに戻る",
    articleFallbackTitle: "ブログ記事",
    articleFallbackDescription: "flatkey.ai の記事。",
    categoryTitle: "ブログカテゴリ：{{category}}",
    categoryFallbackDescription: "カテゴリ別に flatkey.ai ブログ記事を閲覧できます。",
  },
  vi: {
    title: "Blog flatkey.ai",
    description: "Góc nhìn, ghi chú sản phẩm và hướng dẫn triển khai cho đội ngũ xây dựng trên AI API.",
    searchPlaceholder: "Tìm bài viết",
    search: "Tìm kiếm",
    clear: "Xóa",
    readMore: "Đọc thêm",
    previous: "Trước",
    next: "Tiếp",
    pageOf: "Trang {{page}} / {{total}}",
    ctaTitle: "Xây dựng nhanh hơn với một cổng AI.",
    ctaDescription: "Dùng flatkey.ai để quản lý mô hình, khóa, tính phí và quan sát vận hành trong một nền tảng API.",
    ctaButton: "Bắt đầu",
    emptyTitle: "Không tìm thấy bài viết",
    emptyDescription: "Thử tìm kiếm hoặc danh mục khác.",
    latestInCategory: "Bài viết mới nhất trong {{category}}.",
    onThisPage: "Trong trang này",
    relatedArticles: "Bài viết liên quan",
    backToBlog: "Quay lại Blog",
    articleFallbackTitle: "Bài viết blog",
    articleFallbackDescription: "Bài viết từ flatkey.ai.",
    categoryTitle: "Danh mục blog: {{category}}",
    categoryFallbackDescription: "Duyệt bài viết blog flatkey.ai theo danh mục.",
  },
  de: {
    title: "flatkey.ai Blog",
    description: "Einblicke, Produktnotizen und Implementierungsleitfäden für Teams, die mit KI-APIs entwickeln.",
    searchPlaceholder: "Artikel suchen",
    search: "Suchen",
    clear: "Löschen",
    readMore: "Weiterlesen",
    previous: "Zurück",
    next: "Weiter",
    pageOf: "Seite {{page}} von {{total}}",
    ctaTitle: "Schneller entwickeln mit einem KI-Gateway.",
    ctaDescription: "Nutze flatkey.ai, um Modelle, Schlüssel, Abrechnung und Observability über eine API-Plattform zu verwalten.",
    ctaButton: "Loslegen",
    emptyTitle: "Keine Beiträge gefunden",
    emptyDescription: "Probiere eine andere Suche oder Kategorie.",
    latestInCategory: "Neueste Artikel in {{category}}.",
    onThisPage: "Auf dieser Seite",
    relatedArticles: "Ähnliche Artikel",
    backToBlog: "Zurück zum Blog",
    articleFallbackTitle: "Blogartikel",
    articleFallbackDescription: "Artikel von flatkey.ai.",
    categoryTitle: "Blog-Kategorie: {{category}}",
    categoryFallbackDescription: "Durchsuche flatkey.ai-Blogartikel nach Kategorie.",
  },
});

export function formatBlogCopy(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(values[key] ?? ""));
}
