import { consoleUrl } from "@/lib/origins";
import type { Locale } from "@/lib/locales";
import type { SeoInput } from "@/lib/seo";

export const EDM_CAMPAIGN_IDS = ["personal-ai", "cto-ai-savings", "image-buddy"] as const;
export type EdmCampaignId = (typeof EDM_CAMPAIGN_IDS)[number];

export const EDM_LANDING_PATHS: Record<EdmCampaignId, string> = {
  "personal-ai": "/lp/personal-ai",
  "cto-ai-savings": "/lp/cto-ai-savings",
  "image-buddy": "/lp/image-buddy",
};

export type EdmCampaignCopy = {
  eyebrow: string;
  badge: string;
  hero: {
    title: string;
    accent: string;
    description: string;
    highlight?: string;
  };
  offer: {
    title: string;
    body: string;
  };
  primaryCta: string;
  secondaryCta?: {
    label: string;
    href: string;
  };
  heroPanel?: {
    kicker: string;
    title: string;
    rows: Array<{ label: string; value: string; body: string }>;
    footnote: string;
  };
  showcase?: Array<{ src: string; title: string; body: string; alt: string; wide?: boolean }>;
  proof: {
    title: string;
    body: string;
  };
  evidence: Array<{ title: string; body: string }>;
  steps: Array<{ title: string; body: string }>;
  faqs: Array<{ question: string; answer: string }>;
  sectionLabels: {
    startEyebrow: string;
    startTitle: string;
    faqEyebrow: string;
    faqTitle: string;
  };
  finalTitle: string;
  finalBody: string;
};

type CampaignRecord = Record<EdmCampaignId, EdmCampaignCopy>;

const imageBuddyLink = {
  label: "GitHub: flatkey-ai/awesome-images",
  href: "https://github.com/flatkey-ai/awesome-images",
};

const imageBuddyShowcases: Record<Locale, EdmCampaignCopy["showcase"]> = {
  en: [
    {
      src: "/use-case/image-buddy/premium-product-hero.jpg",
      title: "Premium product hero",
      body: "Turn a short product idea into a landing-page or campaign hero image.",
      alt: "Generated hero image of a ceramic coffee mug near a sunny beach",
      wide: true,
    },
    {
      src: "/use-case/image-buddy/marketplace-main-image.jpg",
      title: "Marketplace main image",
      body: "Create clean ecommerce listing images for Amazon-style marketplaces.",
      alt: "Generated marketplace product image of a stainless steel water bottle on white background",
    },
    {
      src: "/use-case/image-buddy/ugc-ad-still.jpg",
      title: "UGC ad still",
      body: "Generate social ad stills and lifestyle scenes from reusable prompt workflows.",
      alt: "Generated UGC style image of a hand holding amber skincare serum in a bright bathroom",
    },
  ],
  zh: [
    {
      src: "/use-case/image-buddy/premium-product-hero.jpg",
      title: "高端产品主视觉",
      body: "把一句产品想法变成落地页或活动主视觉。",
      alt: "生成的海边阳光陶瓷咖啡杯主视觉",
      wide: true,
    },
    {
      src: "/use-case/image-buddy/marketplace-main-image.jpg",
      title: "Marketplace 主图",
      body: "生成适合 Amazon 等电商 listing 的干净产品主图。",
      alt: "生成的白底不锈钢水瓶电商主图",
    },
    {
      src: "/use-case/image-buddy/ugc-ad-still.jpg",
      title: "UGC 广告图",
      body: "用可复用提示词工作流生成社媒广告图和生活方式场景。",
      alt: "生成的手持琥珀色护肤精华瓶 UGC 风格图片",
    },
  ],
  es: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero de producto premium", body: "Convierte una idea corta en un hero para landing page o campaña.", alt: "Hero generado de una taza cerámica junto a una playa soleada", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Imagen principal marketplace", body: "Crea imágenes limpias para listings ecommerce tipo Amazon.", alt: "Imagen generada de botella de acero inoxidable sobre fondo blanco" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Still de anuncio UGC", body: "Genera anuncios sociales y escenas lifestyle desde workflows reutilizables.", alt: "Imagen UGC generada de una mano con serum ámbar en un baño luminoso" },
  ],
  fr: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero produit premium", body: "Transformez une idée produit courte en hero de landing page ou de campagne.", alt: "Hero généré d'un mug en céramique près d'une plage ensoleillée", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Image principale marketplace", body: "Créez des images propres pour listings ecommerce type Amazon.", alt: "Image générée d'une gourde inox sur fond blanc" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Visuel publicitaire UGC", body: "Générez des visuels social ads et scènes lifestyle via workflows réutilisables.", alt: "Image UGC générée d'une main tenant un sérum ambré dans une salle de bain lumineuse" },
  ],
  pt: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero premium de produto", body: "Transforme uma ideia curta em hero para landing page ou campanha.", alt: "Hero gerado de uma caneca cerâmica perto de uma praia ensolarada", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Imagem principal marketplace", body: "Crie imagens limpas para listings ecommerce estilo Amazon.", alt: "Imagem gerada de garrafa inox em fundo branco" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Still de anúncio UGC", body: "Gere social ads e cenas lifestyle com workflows reutilizáveis.", alt: "Imagem UGC gerada de uma mão segurando sérum âmbar em banheiro claro" },
  ],
  ru: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Премиальный product hero", body: "Превращайте короткую идею продукта в hero для лендинга или кампании.", alt: "Сгенерированный hero-визуал керамической кружки у солнечного пляжа", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Главное изображение marketplace", body: "Создавайте чистые ecommerce listing images для marketplace вроде Amazon.", alt: "Сгенерированное изображение стальной бутылки на белом фоне" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC ad still", body: "Генерируйте social ads и lifestyle-сцены из повторяемых workflows.", alt: "Сгенерированное UGC-изображение руки с янтарной сывороткой в светлой ванной" },
  ],
  ja: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "プレミアム商品 hero", body: "短い商品アイデアを landing page や campaign の hero に変換します。", alt: "晴れた海辺の陶器マグを生成した hero 画像", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Marketplace メイン画像", body: "Amazon listing 向けのクリーンな ecommerce 商品画像を作成します。", alt: "白背景のステンレスボトルを生成した商品画像" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC 広告画像", body: "再利用workflowから social ad と lifestyle scene を生成します。", alt: "明るい浴室で琥珀色の美容液を持つ手の UGC 風生成画像" },
  ],
  vi: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero sản phẩm premium", body: "Biến ý tưởng sản phẩm ngắn thành hero cho landing page hoặc campaign.", alt: "Ảnh hero được tạo của ly gốm cạnh bãi biển nắng", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Ảnh chính marketplace", body: "Tạo ảnh listing ecommerce sạch cho marketplace kiểu Amazon.", alt: "Ảnh sản phẩm bình nước inox nền trắng được tạo" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Ảnh quảng cáo UGC", body: "Tạo social ads và cảnh lifestyle từ workflow prompt tái sử dụng.", alt: "Ảnh UGC được tạo của tay cầm serum màu hổ phách trong phòng tắm sáng" },
  ],
  de: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Premium Product Hero", body: "Verwandle eine kurze Produktidee in ein Hero-Bild für Landingpage oder Kampagne.", alt: "Generiertes Hero-Bild eines Keramikbechers an einem sonnigen Strand", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Marketplace-Hauptbild", body: "Erstelle saubere ecommerce Listing-Bilder für Amazon-ähnliche Marketplaces.", alt: "Generiertes Produktbild einer Edelstahlflasche auf weißem Hintergrund" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC-Ad-Still", body: "Generiere social ads und lifestyle scenes aus wiederverwendbaren workflows.", alt: "Generiertes UGC-Bild einer Hand mit bernsteinfarbenem Serum in hellem Bad" },
  ],
};

const CAMPAIGN_COPY: Record<Locale, CampaignRecord> = {
  en: {
    "personal-ai": {
      eyebrow: "Personal AI savings",
      badge: "$20 recharge gets $5 bonus",
      hero: {
        title: "Use top AI models with 40% cheaper tokens",
        accent: "and balance that does not expire",
        description:
          "Create one Flatkey API key, test with a small recharge, and use many well-known models without buying another fixed monthly plan.",
        highlight:
          "If you already think of Plus as a $20 plan, Flatkey makes that same $20 go further: $5 bonus on top, 40% cheaper official tokens, and close to 3x usable AI budget that does not reset monthly.",
      },
      offer: {
        title: "A non-expiring GPT-style power plan",
        body: "Recharge $20 and get $5 bonus to start. Larger recharges unlock larger bonuses, including $200 tiers for heavier personal use.",
      },
      primaryCta: "Create a key and test",
      heroPanel: {
        kicker: "Direct test path",
        title: "Create key -> recharge small -> use more models",
        rows: [
          { label: "Token price", value: "-40%", body: "More prompts, coding runs, and image tests from the same budget." },
          { label: "First test", value: "$20 + $5", body: "Small enough to verify your own workflow before adding more." },
          { label: "Access", value: "1 key", body: "GPT, Claude, Gemini, image models, Codex, and Claude Code." },
        ],
        footnote: "Balance is prepaid and built for usage over time, not a fixed monthly plan.",
      },
      proof: {
        title: "Official model-token quality you can trust",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported model is served through its official upstream tokens, giving you authentic model quality from trusted sources.",
      },
      evidence: [
        { title: "40% cheaper tokens", body: "Stretch the same personal budget across more prompts, coding runs, and image tests." },
        { title: "Many famous models", body: "Use GPT, Claude, Gemini, image models, and more behind one compatible key." },
        { title: "Codex and Claude Code ready", body: "Connect developer tools after creating the key, without managing separate balances." },
      ],
      steps: [
        { title: "Create your key", body: "Sign up and land directly on the API key page." },
        { title: "Recharge from $20", body: "Start with the $5 bonus and verify your own workflow." },
        { title: "Use any supported model", body: "Point apps, scripts, Codex, or Claude Code at Flatkey." },
      ],
      faqs: [
        { question: "Does balance expire?", answer: "Flatkey prepaid balance is designed for usage over time, not a monthly plan you lose if unused." },
        { question: "Is model quality reduced?", answer: "No. Flatkey routes usage through official upstream tokens and keeps provider quality intact." },
        { question: "Can I start small?", answer: "Yes. The $20 recharge plus $5 bonus is intended for quick testing before larger use." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "From email click to working key",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Start with a small key test",
      finalBody: "Create a key, try your real workflow, and decide after seeing cost and quality yourself.",
    },
    "cto-ai-savings": {
      eyebrow: "CTO AI savings",
      badge: "Cut AI spend by 40% today",
      hero: {
        title: "Reduce AI API and engineering AI cost by 40%",
        accent: "without changing your stack",
        description:
          "Flatkey gives your team one compatible gateway for product AI, developer agents, logs, prepaid balance, and fewer quota bottlenecks.",
      },
      offer: {
        title: "Validate with $20 + $5 bonus",
        body: "Run a real workload first. If routing, quality, and logs meet your bar, contact us for higher-volume team pricing.",
      },
      primaryCta: "Create a test key",
      heroPanel: {
        kicker: "Low-risk pilot",
        title: "Test one real workload before scaling team usage",
        rows: [
          { label: "Cost target", value: "-40%", body: "Cut API and engineering-agent spend without changing your stack." },
          { label: "Pilot budget", value: "$20 + $5", body: "Run latency, quality, log, and cost checks on real traffic." },
          { label: "Team path", value: "1 gateway", body: "Centralize keys, prepaid balance, and quota relief for product and engineering." },
        ],
        footnote: "After validation, move to larger prepaid packages or contact us for team pricing.",
      },
      proof: {
        title: "Trusted official-token quality for teams",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported model is served through its official upstream tokens, giving teams trusted sources and authentic model quality.",
      },
      evidence: [
        { title: "Product AI gateway", body: "Add AI capability to your system while keeping one compatible key and usage trail." },
        { title: "Cheaper developer agents", body: "Route Codex, Claude Code, and engineering loops through lower-cost metered usage." },
        { title: "Quota relief", body: "Reduce friction when official accounts hit rate, quota, or operational limits." },
      ],
      steps: [
        { title: "Create a team test key", body: "Use the signup flow to create a key for controlled validation." },
        { title: "Run one real workload", body: "Compare latency, quality, logs, and cost against current routing." },
        { title: "Scale after validation", body: "Move to larger prepaid packages or contact us for a team plan." },
      ],
      faqs: [
        { question: "Do we need code changes?", answer: "Most OpenAI-compatible integrations only need base URL and key changes." },
        { question: "Can we validate before committing?", answer: "Yes. Start with $20 plus $5 bonus and measure a real workload." },
        { question: "Is this suitable for multiple engineers?", answer: "Yes. Flatkey centralizes keys, balances, and logs for shared usage control." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "From email click to working key",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Prove the 40% saving on your own workload",
      finalBody: "Start with a small key, test routing quality, then decide whether to scale the team package.",
    },
    "image-buddy": {
      eyebrow: "Image Buddy for operators",
      badge: "Lower-cost image generation workflow",
      hero: {
        title: "Generate campaign images faster with 40% cheaper AI usage",
        accent: "and reusable prompt workflows",
        description:
          "Flatkey unlocks lower-cost image generation, while Image Buddy gives operators ready workflows instead of repeated prompt hunting.",
      },
      offer: {
        title: "Create a key, then install Image Buddy",
        body: "Use Flatkey for generation capacity and lower cost. Use Image Buddy templates for product shots, ads, marketplace images, and campaign visuals.",
      },
      primaryCta: "Create a key first",
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases.en,
      proof: {
        title: "Reliable token quality for repeat creative work",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported image and text model is served through its official upstream tokens, giving operators trusted sources for repeat creative work.",
      },
      evidence: [
        { title: "Less prompt hunting", body: "Start from reusable Image Buddy workflows instead of rewriting image prompts every time." },
        { title: "Fewer quota stops", body: "Use Flatkey routing to reduce friction from common generation limits." },
        { title: "Campaign-ready assets", body: "Create product visuals, ad stills, marketplace images, and social creatives faster." },
      ],
      steps: [
        { title: "Create a Flatkey key", body: "Sign up and create the key that Image Buddy will use." },
        { title: "Install Image Buddy", body: "Use the GitHub guide to add the workflow to your environment." },
        { title: "Generate with templates", body: "Pick a workflow, add product context, and create usable images." },
      ],
      faqs: [
        { question: "Is Image Buddy only for developers?", answer: "No. It is designed to package image prompts into repeatable workflows for operators and teams." },
        { question: "Why create the key first?", answer: "The key unlocks Flatkey routing and generation capacity before Image Buddy sends requests." },
        { question: "Can I use it for ecommerce?", answer: "Yes. It supports product shots, marketplace cards, ads, and other recurring creative needs." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "From email click to working key",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Create the key before your next image batch",
      finalBody: "Set up Flatkey first, then use Image Buddy to make repeat creative work faster and cheaper.",
    },
  },
  zh: {
    "personal-ai": {
      eyebrow: "个人 AI 省钱方案",
      badge: "充 $20 送 $5 额度",
      hero: {
        title: "用更便宜 40% 的 token 使用主流 AI 模型",
        accent: "余额长期可用",
        description: "创建一个 Flatkey API key，小额充值即可测试，解锁多个知名模型，不必再被固定月费套餐绑住。",
        highlight:
          "如果你已经习惯把 Plus 理解成 $20/月，Flatkey 会让同样 $20 更耐用：先多送 $5，官方 token 再便宜 40%，实际可用量接近 3 倍，而且余额不会按月清零。",
      },
      offer: {
        title: "像不会过期的 GPT 加强计划",
        body: "先充 $20 获得 $5 奖励额度。更高充值档位奖励更多，重度个人用户可选择 $200 等套餐。",
      },
      primaryCta: "创建 key 试用",
      heroPanel: {
        kicker: "最短测试链路",
        title: "创建 key -> 小额充值 -> 直接用更多模型",
        rows: [
          { label: "Token 成本", value: "-40%", body: "同样预算跑更多提示词、编程任务和图片测试。" },
          { label: "首次测试", value: "$20 + $5", body: "先用小额预算验证自己的真实工作流。" },
          { label: "接入范围", value: "1 key", body: "GPT、Claude、Gemini、图片模型、Codex 与 Claude Code。" },
        ],
        footnote: "余额按预付使用，不是每月不用就浪费的固定套餐。",
      },
      proof: {
        title: "模型 token 质量可靠，可放心使用",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的模型都走对应官方上游 token，来源可信赖，模型质量保真、稳定、放心。",
      },
      evidence: [
        { title: "token 便宜 40%", body: "同样预算可以跑更多提示词、编程任务和图片测试。" },
        { title: "覆盖多个知名模型", body: "一个兼容 key 可用 GPT、Claude、Gemini、图片模型等。" },
        { title: "支持 Codex 与 Claude Code", body: "创建 key 后即可接入开发工具，不必维护多套余额。" },
      ],
      steps: [
        { title: "创建你的 key", body: "注册后直接进入 API key 页面。" },
        { title: "从 $20 开始充值", body: "先拿 $5 奖励额度，验证自己的工作流。" },
        { title: "接入任意支持模型", body: "把 App、脚本、Codex 或 Claude Code 指向 Flatkey。" },
      ],
      faqs: [
        { question: "余额会过期吗？", answer: "Flatkey 预付余额面向长期使用，不是不用就浪费的月费套餐。" },
        { question: "模型质量会下降吗？", answer: "不会。Flatkey 通过官方上游 token 路由，保持模型质量。" },
        { question: "可以先小额测试吗？", answer: "可以。$20 充值加 $5 奖励就是为了先验证真实使用效果。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "从邮件点击到拿到可用 key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "先用一个小 key 测起来",
      finalBody: "创建 key，用真实工作流测试成本和质量，再决定是否加大使用。",
    },
    "cto-ai-savings": {
      eyebrow: "CTO AI 成本优化",
      badge: "今天开始省 40% AI 成本",
      hero: {
        title: "让公司 AI API 与研发 AI 成本降低 40%",
        accent: "无需重做技术栈",
        description: "Flatkey 为团队提供兼容网关，统一产品 AI、开发者 Agent、日志、预付余额，并减少 quota 卡点。",
      },
      offer: {
        title: "用 $20 + $5 奖励先验证",
        body: "先跑一段真实工作负载。确认路由、质量与日志满足要求后，再联系升级大额团队套餐。",
      },
      primaryCta: "创建测试 key",
      heroPanel: {
        kicker: "低风险试点",
        title: "先跑一个真实 workload，再决定团队扩容",
        rows: [
          { label: "成本目标", value: "-40%", body: "不重做技术栈，先降低 API 与研发 Agent 用量成本。" },
          { label: "试点预算", value: "$20 + $5", body: "用真实流量验证延迟、质量、日志和成本。" },
          { label: "团队路径", value: "1 gateway", body: "统一 key、预付余额、用量日志，并缓解 quota 卡点。" },
        ],
        footnote: "验证通过后再升级大额预付包，或联系配置团队方案。",
      },
      proof: {
        title: "团队可依赖的官方 token 质量",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的模型都走对应官方上游 token，团队可依赖可信来源和保真的模型质量。",
      },
      evidence: [
        { title: "产品 AI 网关", body: "为系统提供 AI 能力，同时保留一个兼容 key 和完整用量轨迹。" },
        { title: "开发者 Agent 更省", body: "把 Codex、Claude Code 与研发循环转到更低成本的计费路径。" },
        { title: "减少 quota 限制", body: "当官方账号遇到速率、额度或运维限制时，降低阻塞概率。" },
      ],
      steps: [
        { title: "创建团队测试 key", body: "通过注册流程创建一个可控验证 key。" },
        { title: "跑一个真实 workload", body: "对比当前路由的延迟、质量、日志和成本。" },
        { title: "验证后再扩容", body: "确认结果后使用更大预付包，或联系我们配置团队方案。" },
      ],
      faqs: [
        { question: "需要改很多代码吗？", answer: "多数 OpenAI 兼容集成只需要替换 base URL 和 key。" },
        { question: "能先验证再采购吗？", answer: "可以。先用 $20 加 $5 奖励跑真实工作负载。" },
        { question: "适合多名工程师使用吗？", answer: "适合。Flatkey 可集中管理 key、余额和日志，便于团队控制。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "从邮件点击到拿到可用 key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "用自己的 workload 证明 40% 节省",
      finalBody: "先建一个小额测试 key，验证路由质量，再决定是否扩大团队使用。",
    },
    "image-buddy": {
      eyebrow: "运营生图工作流",
      badge: "更低成本的图片生成",
      hero: {
        title: "用便宜 40% 的 AI 用量更快生成活动图片",
        accent: "并复用成熟提示词流程",
        description: "Flatkey 降低生图成本、缓解额度限制，Image Buddy 帮运营直接使用可复用工作流，不再反复找提示词。",
      },
      offer: {
        title: "先创建 key，再安装 Image Buddy",
        body: "用 Flatkey 提供生成能力与更低成本，再用 Image Buddy 模板生成产品图、广告图、电商图和活动素材。",
      },
      primaryCta: "先创建 key",
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases.zh,
      proof: {
        title: "长期生图也稳定的 token 质量",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的图片与文本模型都走对应官方上游 token，为长期生图提供可信赖的质量基础。",
      },
      evidence: [
        { title: "少找提示词", body: "从 Image Buddy 可复用流程开始，不用每次重写图片提示词。" },
        { title: "减少额度卡顿", body: "通过 Flatkey 路由降低常见生成限制带来的中断。" },
        { title: "更快做活动素材", body: "更快生成产品图、广告封面、电商图片和社媒创意。" },
      ],
      steps: [
        { title: "创建 Flatkey key", body: "注册并创建 Image Buddy 调用所需的 key。" },
        { title: "安装 Image Buddy", body: "按照 GitHub 文档把工作流加入你的环境。" },
        { title: "用模板生成", body: "选择工作流，补充产品信息，生成可用图片。" },
      ],
      faqs: [
        { question: "Image Buddy 只给开发者用吗？", answer: "不是。它把图片提示词封装成可重复流程，适合运营和团队。" },
        { question: "为什么先创建 key？", answer: "key 用来开启 Flatkey 路由和生成能力，Image Buddy 会用它发送请求。" },
        { question: "能做电商图吗？", answer: "可以。支持产品图、详情卡、广告图等高频素材需求。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "从邮件点击到拿到可用 key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "下次批量作图前先创建 key",
      finalBody: "先接好 Flatkey，再用 Image Buddy 更快、更便宜地处理重复创意工作。",
    },
  },
  get es() {
    return createWesternCopy("es");
  },
  get fr() {
    return createWesternCopy("fr");
  },
  get pt() {
    return createWesternCopy("pt");
  },
  get ru() {
    return createWesternCopy("ru");
  },
  get ja() {
    return createWesternCopy("ja");
  },
  get vi() {
    return createWesternCopy("vi");
  },
  get de() {
    return createWesternCopy("de");
  },
};

function createWesternCopy(locale: Exclude<Locale, "en" | "zh">): CampaignRecord {
  const t = localizedTemplates[locale];
  return {
    "personal-ai": {
      eyebrow: t.personalEyebrow,
      badge: t.personalBadge,
      hero: {
        title: t.personalTitle,
        accent: t.personalAccent,
        description: t.personalDescription,
        highlight: t.personalHighlight,
      },
      offer: { title: t.personalOfferTitle, body: t.personalOfferBody },
      primaryCta: t.createKey,
      heroPanel: {
        kicker: t.personalBadge,
        title: t.personalOfferTitle,
        rows: [
          { label: t.evidenceCheapTitle, value: "-40%", body: t.personalCheapBody },
          { label: t.stepRechargeTitle, value: "$20 + $5", body: t.personalStepRechargeBody },
          { label: t.evidenceModelsTitle, value: "1 key", body: t.personalModelsBody },
        ],
        footnote: t.personalFinalBody,
      },
      proof: { title: t.proofTitle, body: t.personalProofBody },
      evidence: [
        { title: t.evidenceCheapTitle, body: t.personalCheapBody },
        { title: t.evidenceModelsTitle, body: t.personalModelsBody },
        { title: t.evidenceAgentsTitle, body: t.personalAgentsBody },
      ],
      steps: [
        { title: t.stepKeyTitle, body: t.personalStepKeyBody },
        { title: t.stepRechargeTitle, body: t.personalStepRechargeBody },
        { title: t.stepUseTitle, body: t.personalStepUseBody },
      ],
      faqs: [
        { question: t.personalFaq1Q, answer: t.personalFaq1A },
        { question: t.personalFaq2Q, answer: t.personalFaq2A },
        { question: t.personalFaq3Q, answer: t.personalFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.personalFinalTitle,
      finalBody: t.personalFinalBody,
    },
    "cto-ai-savings": {
      eyebrow: t.ctoEyebrow,
      badge: t.ctoBadge,
      hero: {
        title: t.ctoTitle,
        accent: t.ctoAccent,
        description: t.ctoDescription,
      },
      offer: { title: t.ctoOfferTitle, body: t.ctoOfferBody },
      primaryCta: t.createTestKey,
      heroPanel: {
        kicker: t.ctoBadge,
        title: t.ctoOfferTitle,
        rows: [
          { label: t.ctoEvidenceAgentsTitle, value: "-40%", body: t.ctoEvidenceAgentsBody },
          { label: t.ctoStepWorkloadTitle, value: "$20 + $5", body: t.ctoStepWorkloadBody },
          { label: t.ctoEvidenceQuotaTitle, value: "1 gateway", body: t.ctoEvidenceQuotaBody },
        ],
        footnote: t.ctoFinalBody,
      },
      proof: { title: t.proofTitle, body: t.ctoProofBody },
      evidence: [
        { title: t.ctoEvidenceGatewayTitle, body: t.ctoEvidenceGatewayBody },
        { title: t.ctoEvidenceAgentsTitle, body: t.ctoEvidenceAgentsBody },
        { title: t.ctoEvidenceQuotaTitle, body: t.ctoEvidenceQuotaBody },
      ],
      steps: [
        { title: t.ctoStepKeyTitle, body: t.ctoStepKeyBody },
        { title: t.ctoStepWorkloadTitle, body: t.ctoStepWorkloadBody },
        { title: t.ctoStepScaleTitle, body: t.ctoStepScaleBody },
      ],
      faqs: [
        { question: t.ctoFaq1Q, answer: t.ctoFaq1A },
        { question: t.ctoFaq2Q, answer: t.ctoFaq2A },
        { question: t.ctoFaq3Q, answer: t.ctoFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.ctoFinalTitle,
      finalBody: t.ctoFinalBody,
    },
    "image-buddy": {
      eyebrow: t.imageEyebrow,
      badge: t.imageBadge,
      hero: {
        title: t.imageTitle,
        accent: t.imageAccent,
        description: t.imageDescription,
      },
      offer: { title: t.imageOfferTitle, body: t.imageOfferBody },
      primaryCta: t.createKeyFirst,
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases[locale],
      proof: { title: t.imageProofTitle, body: t.imageProofBody },
      evidence: [
        { title: t.imageEvidencePromptTitle, body: t.imageEvidencePromptBody },
        { title: t.imageEvidenceQuotaTitle, body: t.imageEvidenceQuotaBody },
        { title: t.imageEvidenceAssetTitle, body: t.imageEvidenceAssetBody },
      ],
      steps: [
        { title: t.imageStepKeyTitle, body: t.imageStepKeyBody },
        { title: t.imageStepInstallTitle, body: t.imageStepInstallBody },
        { title: t.imageStepGenerateTitle, body: t.imageStepGenerateBody },
      ],
      faqs: [
        { question: t.imageFaq1Q, answer: t.imageFaq1A },
        { question: t.imageFaq2Q, answer: t.imageFaq2A },
        { question: t.imageFaq3Q, answer: t.imageFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.imageFinalTitle,
      finalBody: t.imageFinalBody,
    },
  };
}

const localizedTemplates = {
  es: {
    sectionLabels: {
      startEyebrow: "Ruta de inicio",
      startTitle: "Del clic del email a una key funcional",
      faqEyebrow: "Preguntas",
      faqTitle: "Respuestas breves antes de probar",
    },
    personalEyebrow: "Ahorro de IA personal",
    personalBadge: "Recarga $20 y recibe $5 de bono",
    personalTitle: "Usa modelos de IA populares con tokens 40% más baratos",
    personalAccent: "y saldo que no caduca",
    personalDescription: "Crea una API key de Flatkey, prueba con una recarga pequeña y usa muchos modelos conocidos sin otro plan mensual fijo.",
    personalHighlight: "Si ya ves Plus como un plan de $20/mes, Flatkey hace que esos mismos $20 rindan más: $5 de bono, tokens oficiales 40% más baratos y casi 3x de presupuesto usable sin reinicio mensual.",
    personalOfferTitle: "Un plan potente tipo GPT que no caduca",
    personalOfferBody: "Recarga $20 y recibe $5 de bono. Las recargas mayores desbloquean más bono, incluidas opciones de $200 para uso personal intensivo.",
    createKey: "Crear key y probar",
    proofTitle: "Calidad confiable con tokens oficiales",
    personalProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo soportado usa sus tokens oficiales upstream, con fuentes confiables y calidad auténtica.",
    evidenceCheapTitle: "Tokens 40% más baratos",
    personalCheapBody: "El mismo presupuesto rinde más prompts, ejecuciones de código y pruebas de imagen.",
    evidenceModelsTitle: "Muchos modelos conocidos",
    personalModelsBody: "Usa GPT, Claude, Gemini, modelos de imagen y más detrás de una key compatible.",
    evidenceAgentsTitle: "Listo para Codex y Claude Code",
    personalAgentsBody: "Conecta herramientas de desarrollo después de crear la key, sin varios saldos separados.",
    stepKeyTitle: "Crea tu key",
    personalStepKeyBody: "Regístrate y llega directamente a la página de API keys.",
    stepRechargeTitle: "Recarga desde $20",
    personalStepRechargeBody: "Empieza con el bono de $5 y valida tu propio flujo.",
    stepUseTitle: "Usa cualquier modelo soportado",
    personalStepUseBody: "Apunta apps, scripts, Codex o Claude Code a Flatkey.",
    personalFaq1Q: "¿El saldo caduca?",
    personalFaq1A: "El saldo prepago de Flatkey está pensado para usarse con el tiempo, no como una mensualidad que pierdes.",
    personalFaq2Q: "¿Baja la calidad del modelo?",
    personalFaq2A: "No. Flatkey enruta por tokens oficiales upstream y conserva la calidad del proveedor.",
    personalFaq3Q: "¿Puedo empezar pequeño?",
    personalFaq3A: "Sí. La recarga de $20 con bono de $5 sirve para probar antes de usar más.",
    personalFinalTitle: "Empieza con una prueba pequeña",
    personalFinalBody: "Crea una key, prueba tu flujo real y decide tras ver coste y calidad.",
    ctoEyebrow: "Ahorro de IA para CTO",
    ctoBadge: "Reduce 40% el gasto de IA hoy",
    ctoTitle: "Reduce 40% el coste de APIs de IA e IA para ingeniería",
    ctoAccent: "sin cambiar tu stack",
    ctoDescription: "Flatkey da a tu equipo una puerta compatible para IA de producto, agentes de desarrollo, logs, saldo prepago y menos bloqueos de cuota.",
    ctoOfferTitle: "Valida con $20 + $5 de bono",
    ctoOfferBody: "Ejecuta primero una carga real. Si routing, calidad y logs cumplen, contáctanos para precios de equipo de mayor volumen.",
    createTestKey: "Crear key de prueba",
    ctoProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo soportado usa sus tokens oficiales upstream, con fuentes confiables y calidad auténtica para equipos.",
    ctoEvidenceGatewayTitle: "Gateway de IA de producto",
    ctoEvidenceGatewayBody: "Añade IA a tu sistema con una key compatible y una trazabilidad clara de uso.",
    ctoEvidenceAgentsTitle: "Agentes de desarrollo más baratos",
    ctoEvidenceAgentsBody: "Ruta Codex, Claude Code y ciclos de ingeniería por uso medido de menor coste.",
    ctoEvidenceQuotaTitle: "Menos bloqueo por cuotas",
    ctoEvidenceQuotaBody: "Reduce fricción cuando cuentas oficiales alcanzan límites de rate, cuota u operación.",
    ctoStepKeyTitle: "Crea una key de prueba",
    ctoStepKeyBody: "Usa el registro para crear una key controlada de validación.",
    ctoStepWorkloadTitle: "Ejecuta una carga real",
    ctoStepWorkloadBody: "Compara latencia, calidad, logs y coste frente a tu routing actual.",
    ctoStepScaleTitle: "Escala después de validar",
    ctoStepScaleBody: "Pasa a paquetes prepago mayores o habla con nosotros sobre un plan de equipo.",
    ctoFaq1Q: "¿Necesitamos cambiar mucho código?",
    ctoFaq1A: "La mayoría de integraciones compatibles con OpenAI solo cambian base URL y key.",
    ctoFaq2Q: "¿Podemos validar antes de comprometernos?",
    ctoFaq2A: "Sí. Empieza con $20 más $5 de bono y mide una carga real.",
    ctoFaq3Q: "¿Sirve para varios ingenieros?",
    ctoFaq3A: "Sí. Flatkey centraliza keys, saldos y logs para controlar uso compartido.",
    ctoFinalTitle: "Demuestra el 40% de ahorro en tu propia carga",
    ctoFinalBody: "Empieza con una key pequeña, valida calidad de routing y decide si escalar.",
    imageEyebrow: "Image Buddy para operaciones",
    imageBadge: "Flujo de imágenes con menor coste",
    imageTitle: "Genera imágenes de campaña más rápido con IA 40% más barata",
    imageAccent: "y flujos reutilizables",
    imageDescription: "Flatkey reduce el coste de generación de imágenes e Image Buddy da flujos listos para no buscar prompts cada vez.",
    imageOfferTitle: "Crea una key y luego instala Image Buddy",
    imageOfferBody: "Usa Flatkey para capacidad y menor coste. Usa plantillas de Image Buddy para producto, anuncios, marketplace y campañas.",
    createKeyFirst: "Crear key primero",
    imageProofTitle: "Calidad estable para creación repetida",
    imageProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo de imagen y texto soportado usa sus tokens oficiales upstream, una base confiable para creación repetida.",
    imageEvidencePromptTitle: "Menos búsqueda de prompts",
    imageEvidencePromptBody: "Parte de flujos reutilizables de Image Buddy en vez de reescribir prompts de imagen.",
    imageEvidenceQuotaTitle: "Menos paradas por cuota",
    imageEvidenceQuotaBody: "Usa routing de Flatkey para reducir fricción de límites frecuentes de generación.",
    imageEvidenceAssetTitle: "Assets listos para campañas",
    imageEvidenceAssetBody: "Crea producto, anuncios, marketplace y social creatives más rápido.",
    imageStepKeyTitle: "Crea una key de Flatkey",
    imageStepKeyBody: "Regístrate y crea la key que usará Image Buddy.",
    imageStepInstallTitle: "Instala Image Buddy",
    imageStepInstallBody: "Sigue la guía de GitHub para añadir el flujo a tu entorno.",
    imageStepGenerateTitle: "Genera con plantillas",
    imageStepGenerateBody: "Elige un flujo, añade contexto del producto y crea imágenes útiles.",
    imageFaq1Q: "¿Image Buddy es solo para desarrolladores?",
    imageFaq1A: "No. Empaqueta prompts de imagen en flujos repetibles para operaciones y equipos.",
    imageFaq2Q: "¿Por qué crear la key primero?",
    imageFaq2A: "La key activa routing y capacidad de generación antes de que Image Buddy envíe solicitudes.",
    imageFaq3Q: "¿Sirve para ecommerce?",
    imageFaq3A: "Sí. Soporta producto, tarjetas de marketplace, anuncios y necesidades creativas recurrentes.",
    imageFinalTitle: "Crea la key antes del próximo lote de imágenes",
    imageFinalBody: "Configura Flatkey primero y usa Image Buddy para trabajar más rápido y barato.",
  },
  fr: {
    sectionLabels: {
      startEyebrow: "Chemin de départ",
      startTitle: "Du clic email à une clé fonctionnelle",
      faqEyebrow: "Questions",
      faqTitle: "Réponses courtes avant de tester",
    },
    personalEyebrow: "Économies IA personnelles",
    personalBadge: "Rechargez $20, recevez $5 de bonus",
    personalTitle: "Utilisez les grands modèles IA avec des tokens 40% moins chers",
    personalAccent: "et un solde qui n'expire pas",
    personalDescription: "Créez une clé API Flatkey, testez avec une petite recharge et utilisez de nombreux modèles connus sans autre abonnement mensuel fixe.",
    personalHighlight: "Si vous voyez déjà Plus comme un forfait à $20/mois, Flatkey fait durer ces mêmes $20 : $5 de bonus, des tokens officiels 40% moins chers et près de 3x de budget IA utilisable sans remise à zéro mensuelle.",
    personalOfferTitle: "Un plan puissant type GPT sans expiration",
    personalOfferBody: "Rechargez $20 et recevez $5 de bonus. Les recharges plus élevées donnent plus de bonus, dont des options $200 pour usage personnel intensif.",
    createKey: "Créer une clé et tester",
    proofTitle: "Qualité fiable via tokens officiels",
    personalProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle supporté utilise ses tokens upstream officiels, avec des sources fiables et une qualité authentique.",
    evidenceCheapTitle: "Tokens 40% moins chers",
    personalCheapBody: "Le même budget couvre plus de prompts, de runs de code et de tests image.",
    evidenceModelsTitle: "Nombreux modèles connus",
    personalModelsBody: "Utilisez GPT, Claude, Gemini, modèles image et plus avec une clé compatible.",
    evidenceAgentsTitle: "Prêt pour Codex et Claude Code",
    personalAgentsBody: "Connectez les outils développeur après création de la clé, sans gérer plusieurs soldes.",
    stepKeyTitle: "Créez votre clé",
    personalStepKeyBody: "Inscrivez-vous et arrivez directement sur la page des clés API.",
    stepRechargeTitle: "Recharge dès $20",
    personalStepRechargeBody: "Commencez avec le bonus de $5 et validez votre workflow.",
    stepUseTitle: "Utilisez tout modèle supporté",
    personalStepUseBody: "Pointez apps, scripts, Codex ou Claude Code vers Flatkey.",
    personalFaq1Q: "Le solde expire-t-il ?",
    personalFaq1A: "Le solde prépayé Flatkey est fait pour être utilisé dans le temps, pas perdu comme un forfait mensuel.",
    personalFaq2Q: "La qualité du modèle baisse-t-elle ?",
    personalFaq2A: "Non. Flatkey route via des tokens upstream officiels et conserve la qualité fournisseur.",
    personalFaq3Q: "Puis-je commencer petit ?",
    personalFaq3A: "Oui. La recharge $20 avec $5 de bonus sert à tester avant un usage plus large.",
    personalFinalTitle: "Commencez par une petite clé de test",
    personalFinalBody: "Créez une clé, testez votre vrai workflow, puis décidez avec coût et qualité visibles.",
    ctoEyebrow: "Économies IA pour CTO",
    ctoBadge: "Réduisez 40% du coût IA aujourd'hui",
    ctoTitle: "Réduisez de 40% le coût API IA et l'IA d'ingénierie",
    ctoAccent: "sans changer votre stack",
    ctoDescription: "Flatkey donne à votre équipe une gateway compatible pour IA produit, agents développeur, logs, solde prépayé et moins de blocages quota.",
    ctoOfferTitle: "Validez avec $20 + $5 de bonus",
    ctoOfferBody: "Lancez d'abord une charge réelle. Si routing, qualité et logs conviennent, contactez-nous pour un prix équipe plus élevé.",
    createTestKey: "Créer une clé de test",
    ctoProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle supporté utilise ses tokens upstream officiels, avec des sources fiables et une qualité authentique pour les équipes.",
    ctoEvidenceGatewayTitle: "Gateway IA produit",
    ctoEvidenceGatewayBody: "Ajoutez l'IA à votre système avec une clé compatible et une trace d'usage claire.",
    ctoEvidenceAgentsTitle: "Agents développeur moins chers",
    ctoEvidenceAgentsBody: "Routez Codex, Claude Code et boucles d'ingénierie vers un usage mesuré moins coûteux.",
    ctoEvidenceQuotaTitle: "Moins de blocage quota",
    ctoEvidenceQuotaBody: "Réduisez la friction quand les comptes officiels touchent rate limit, quota ou limites opérationnelles.",
    ctoStepKeyTitle: "Créez une clé de test",
    ctoStepKeyBody: "Utilisez l'inscription pour créer une clé de validation contrôlée.",
    ctoStepWorkloadTitle: "Lancez une charge réelle",
    ctoStepWorkloadBody: "Comparez latence, qualité, logs et coût avec votre routing actuel.",
    ctoStepScaleTitle: "Scale après validation",
    ctoStepScaleBody: "Passez à des packs prépayés plus grands ou demandez un plan équipe.",
    ctoFaq1Q: "Faut-il beaucoup changer le code ?",
    ctoFaq1A: "La plupart des intégrations compatibles OpenAI changent seulement base URL et clé.",
    ctoFaq2Q: "Peut-on valider avant engagement ?",
    ctoFaq2A: "Oui. Commencez avec $20 plus $5 de bonus et mesurez une charge réelle.",
    ctoFaq3Q: "Est-ce adapté à plusieurs ingénieurs ?",
    ctoFaq3A: "Oui. Flatkey centralise clés, soldes et logs pour contrôler l'usage partagé.",
    ctoFinalTitle: "Prouvez les 40% d'économie sur votre charge",
    ctoFinalBody: "Commencez avec une petite clé, validez la qualité, puis décidez de scaler.",
    imageEyebrow: "Image Buddy pour opérations",
    imageBadge: "Workflow image à coût réduit",
    imageTitle: "Générez des images de campagne plus vite avec une IA 40% moins chère",
    imageAccent: "et des workflows réutilisables",
    imageDescription: "Flatkey réduit le coût de génération d'images, et Image Buddy donne des workflows prêts au lieu de chercher des prompts.",
    imageOfferTitle: "Créez une clé, puis installez Image Buddy",
    imageOfferBody: "Utilisez Flatkey pour capacité et coût réduit. Utilisez Image Buddy pour produit, ads, marketplace et campagnes.",
    createKeyFirst: "Créer la clé d'abord",
    imageProofTitle: "Qualité stable pour création répétée",
    imageProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle image et texte supporté utilise ses tokens upstream officiels, base fiable pour la création répétée.",
    imageEvidencePromptTitle: "Moins de recherche de prompts",
    imageEvidencePromptBody: "Partez de workflows Image Buddy réutilisables au lieu de réécrire chaque prompt image.",
    imageEvidenceQuotaTitle: "Moins d'arrêts quota",
    imageEvidenceQuotaBody: "Utilisez le routing Flatkey pour réduire les limites fréquentes de génération.",
    imageEvidenceAssetTitle: "Assets prêts pour campagnes",
    imageEvidenceAssetBody: "Créez plus vite visuels produit, ads, marketplace et contenus sociaux.",
    imageStepKeyTitle: "Créez une clé Flatkey",
    imageStepKeyBody: "Inscrivez-vous et créez la clé utilisée par Image Buddy.",
    imageStepInstallTitle: "Installez Image Buddy",
    imageStepInstallBody: "Suivez le guide GitHub pour ajouter le workflow à votre environnement.",
    imageStepGenerateTitle: "Générez avec templates",
    imageStepGenerateBody: "Choisissez un workflow, ajoutez le contexte produit et créez des images utiles.",
    imageFaq1Q: "Image Buddy est-il réservé aux développeurs ?",
    imageFaq1A: "Non. Il transforme les prompts image en workflows répétables pour opérations et équipes.",
    imageFaq2Q: "Pourquoi créer la clé d'abord ?",
    imageFaq2A: "La clé active le routing Flatkey et la capacité de génération avant les requêtes Image Buddy.",
    imageFaq3Q: "Est-ce utile pour ecommerce ?",
    imageFaq3A: "Oui. Il couvre produit, marketplace, ads et besoins créatifs récurrents.",
    imageFinalTitle: "Créez la clé avant votre prochain lot d'images",
    imageFinalBody: "Configurez Flatkey puis utilisez Image Buddy pour travailler plus vite et moins cher.",
  },
  pt: {
    sectionLabels: {
      startEyebrow: "Caminho inicial",
      startTitle: "Do clique no email até uma key funcionando",
      faqEyebrow: "Perguntas",
      faqTitle: "Respostas curtas antes de testar",
    },
    personalEyebrow: "Economia pessoal com IA",
    personalBadge: "Recarregue $20 e ganhe $5 de bônus",
    personalTitle: "Use modelos famosos de IA com tokens 40% mais baratos",
    personalAccent: "e saldo que não expira",
    personalDescription: "Crie uma API key Flatkey, teste com uma recarga pequena e use muitos modelos conhecidos sem outro plano mensal fixo.",
    personalHighlight: "Se você já vê o Plus como um plano de $20/mês, o Flatkey faz os mesmos $20 renderem mais: $5 de bônus, tokens oficiais 40% mais baratos e quase 3x de orçamento útil sem zerar todo mês.",
    personalOfferTitle: "Um plano poderoso tipo GPT sem expiração",
    personalOfferBody: "Recarregue $20 e receba $5 de bônus. Recargas maiores liberam bônus maiores, incluindo opções de $200 para uso pessoal intenso.",
    createKey: "Criar key e testar",
    proofTitle: "Qualidade confiável com tokens oficiais",
    personalProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo suportado usa seus tokens upstream oficiais, com fontes confiáveis e qualidade autêntica.",
    evidenceCheapTitle: "Tokens 40% mais baratos",
    personalCheapBody: "O mesmo orçamento rende mais prompts, execuções de código e testes de imagem.",
    evidenceModelsTitle: "Muitos modelos conhecidos",
    personalModelsBody: "Use GPT, Claude, Gemini, modelos de imagem e mais com uma key compatível.",
    evidenceAgentsTitle: "Pronto para Codex e Claude Code",
    personalAgentsBody: "Conecte ferramentas de desenvolvimento após criar a key, sem saldos separados.",
    stepKeyTitle: "Crie sua key",
    personalStepKeyBody: "Cadastre-se e vá direto para a página de API keys.",
    stepRechargeTitle: "Recarregue a partir de $20",
    personalStepRechargeBody: "Comece com o bônus de $5 e valide seu fluxo.",
    stepUseTitle: "Use qualquer modelo suportado",
    personalStepUseBody: "Aponte apps, scripts, Codex ou Claude Code para Flatkey.",
    personalFaq1Q: "O saldo expira?",
    personalFaq1A: "O saldo pré-pago Flatkey foi feito para uso ao longo do tempo, não como mensalidade perdida.",
    personalFaq2Q: "A qualidade do modelo cai?",
    personalFaq2A: "Não. Flatkey roteia por tokens upstream oficiais e mantém a qualidade do provedor.",
    personalFaq3Q: "Posso começar pequeno?",
    personalFaq3A: "Sim. A recarga de $20 com $5 de bônus serve para testar antes de usar mais.",
    personalFinalTitle: "Comece com um teste pequeno",
    personalFinalBody: "Crie uma key, teste seu fluxo real e decida vendo custo e qualidade.",
    ctoEyebrow: "Economia de IA para CTO",
    ctoBadge: "Reduza 40% do gasto de IA hoje",
    ctoTitle: "Reduza 40% do custo de API de IA e IA de engenharia",
    ctoAccent: "sem trocar seu stack",
    ctoDescription: "Flatkey dá à equipe um gateway compatível para IA de produto, agentes de desenvolvimento, logs, saldo pré-pago e menos bloqueios de quota.",
    ctoOfferTitle: "Valide com $20 + $5 de bônus",
    ctoOfferBody: "Rode primeiro uma carga real. Se routing, qualidade e logs passarem, fale conosco para preço de equipe em maior volume.",
    createTestKey: "Criar key de teste",
    ctoProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo suportado usa seus tokens upstream oficiais, com fontes confiáveis e qualidade autêntica para equipes.",
    ctoEvidenceGatewayTitle: "Gateway de IA para produto",
    ctoEvidenceGatewayBody: "Adicione IA ao sistema com uma key compatível e trilha clara de uso.",
    ctoEvidenceAgentsTitle: "Agentes de desenvolvimento mais baratos",
    ctoEvidenceAgentsBody: "Roteie Codex, Claude Code e ciclos de engenharia por uso medido mais barato.",
    ctoEvidenceQuotaTitle: "Menos bloqueio por quota",
    ctoEvidenceQuotaBody: "Reduza atrito quando contas oficiais atingem limites de rate, quota ou operação.",
    ctoStepKeyTitle: "Crie uma key de teste",
    ctoStepKeyBody: "Use o cadastro para criar uma key controlada de validação.",
    ctoStepWorkloadTitle: "Rode uma carga real",
    ctoStepWorkloadBody: "Compare latência, qualidade, logs e custo contra seu routing atual.",
    ctoStepScaleTitle: "Escale após validar",
    ctoStepScaleBody: "Passe para pacotes pré-pagos maiores ou peça um plano de equipe.",
    ctoFaq1Q: "Precisamos mudar muito código?",
    ctoFaq1A: "A maioria das integrações compatíveis com OpenAI só muda base URL e key.",
    ctoFaq2Q: "Podemos validar antes de compromisso?",
    ctoFaq2A: "Sim. Comece com $20 mais $5 de bônus e meça uma carga real.",
    ctoFaq3Q: "Serve para vários engenheiros?",
    ctoFaq3A: "Sim. Flatkey centraliza keys, saldos e logs para controlar uso compartilhado.",
    ctoFinalTitle: "Comprove 40% de economia na sua carga",
    ctoFinalBody: "Comece com uma key pequena, valide qualidade e decida se escala.",
    imageEyebrow: "Image Buddy para operações",
    imageBadge: "Fluxo de imagem com menor custo",
    imageTitle: "Gere imagens de campanha mais rápido com IA 40% mais barata",
    imageAccent: "e workflows reutilizáveis",
    imageDescription: "Flatkey reduz custo de geração de imagens, e Image Buddy traz workflows prontos em vez de procurar prompts sempre.",
    imageOfferTitle: "Crie uma key e depois instale Image Buddy",
    imageOfferBody: "Use Flatkey para capacidade e menor custo. Use templates Image Buddy para produto, anúncios, marketplace e campanhas.",
    createKeyFirst: "Criar key primeiro",
    imageProofTitle: "Qualidade estável para criação recorrente",
    imageProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo de imagem e texto suportado usa seus tokens upstream oficiais, uma base confiável para criação recorrente.",
    imageEvidencePromptTitle: "Menos busca de prompts",
    imageEvidencePromptBody: "Comece com workflows reutilizáveis Image Buddy em vez de reescrever prompts de imagem.",
    imageEvidenceQuotaTitle: "Menos paradas por quota",
    imageEvidenceQuotaBody: "Use routing Flatkey para reduzir limites frequentes de geração.",
    imageEvidenceAssetTitle: "Assets prontos para campanha",
    imageEvidenceAssetBody: "Crie produto, anúncios, marketplace e criativos sociais mais rápido.",
    imageStepKeyTitle: "Crie uma key Flatkey",
    imageStepKeyBody: "Cadastre-se e crie a key que Image Buddy usará.",
    imageStepInstallTitle: "Instale Image Buddy",
    imageStepInstallBody: "Siga o guia GitHub para adicionar o workflow ao seu ambiente.",
    imageStepGenerateTitle: "Gere com templates",
    imageStepGenerateBody: "Escolha um workflow, adicione contexto do produto e crie imagens úteis.",
    imageFaq1Q: "Image Buddy é só para devs?",
    imageFaq1A: "Não. Ele empacota prompts de imagem em workflows repetíveis para operações e equipes.",
    imageFaq2Q: "Por que criar a key primeiro?",
    imageFaq2A: "A key ativa routing e capacidade de geração antes das requisições do Image Buddy.",
    imageFaq3Q: "Serve para ecommerce?",
    imageFaq3A: "Sim. Suporta produto, cards de marketplace, anúncios e criativos recorrentes.",
    imageFinalTitle: "Crie a key antes do próximo lote de imagens",
    imageFinalBody: "Configure Flatkey primeiro e use Image Buddy para trabalhar mais rápido e barato.",
  },
  ru: {
    sectionLabels: {
      startEyebrow: "Путь запуска",
      startTitle: "От клика в письме до рабочего key",
      faqEyebrow: "Вопросы",
      faqTitle: "Короткие ответы перед проверкой",
    },
    personalEyebrow: "Экономия на ИИ для личного использования",
    personalBadge: "Пополните на $20 и получите $5 бонуса",
    personalTitle: "Используйте популярные ИИ-модели с токенами на 40% дешевле",
    personalAccent: "и балансом без сгорания",
    personalDescription: "Создайте API key Flatkey, протестируйте небольшое пополнение и используйте известные модели без ещё одной фиксированной подписки.",
    personalHighlight: "Если вы уже воспринимаете Plus как план за $20/мес., Flatkey растягивает те же $20 дальше: $5 бонуса, официальные токены на 40% дешевле и почти 3x полезного AI-бюджета без ежемесячного обнуления.",
    personalOfferTitle: "Мощный GPT-подобный план без сгорания",
    personalOfferBody: "Пополните на $20 и получите $5 бонуса. Более крупные пополнения дают больше бонусов, включая варианты $200 для активного личного использования.",
    createKey: "Создать key и проверить",
    proofTitle: "Надёжное качество через официальные токены",
    personalProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая модель работает через свои официальные upstream-токены, с доверенными источниками и подлинным качеством.",
    evidenceCheapTitle: "Токены на 40% дешевле",
    personalCheapBody: "Тот же бюджет даёт больше промптов, запусков кода и тестов изображений.",
    evidenceModelsTitle: "Много известных моделей",
    personalModelsBody: "Используйте GPT, Claude, Gemini, модели изображений и другие через один совместимый key.",
    evidenceAgentsTitle: "Готово для Codex и Claude Code",
    personalAgentsBody: "Подключайте developer-инструменты после создания key без отдельных балансов.",
    stepKeyTitle: "Создайте key",
    personalStepKeyBody: "Зарегистрируйтесь и сразу перейдите на страницу API keys.",
    stepRechargeTitle: "Пополните от $20",
    personalStepRechargeBody: "Начните с бонуса $5 и проверьте свой рабочий процесс.",
    stepUseTitle: "Используйте любую поддерживаемую модель",
    personalStepUseBody: "Направьте apps, scripts, Codex или Claude Code на Flatkey.",
    personalFaq1Q: "Баланс сгорает?",
    personalFaq1A: "Предоплаченный баланс Flatkey рассчитан на использование со временем, а не как теряемая месячная подписка.",
    personalFaq2Q: "Качество модели снижается?",
    personalFaq2A: "Нет. Flatkey маршрутизирует через официальные upstream-токены и сохраняет качество провайдера.",
    personalFaq3Q: "Можно начать с малого?",
    personalFaq3A: "Да. Пополнение $20 с бонусом $5 предназначено для проверки перед большим использованием.",
    personalFinalTitle: "Начните с небольшой проверки key",
    personalFinalBody: "Создайте key, проверьте реальный сценарий и решайте после оценки цены и качества.",
    ctoEyebrow: "Экономия ИИ для CTO",
    ctoBadge: "Снизьте расходы на ИИ на 40% сегодня",
    ctoTitle: "Снизьте стоимость AI API и инженерного ИИ на 40%",
    ctoAccent: "без смены стека",
    ctoDescription: "Flatkey даёт команде совместимый gateway для продуктового ИИ, developer agents, логов, предоплаты и меньшего числа quota-блокировок.",
    ctoOfferTitle: "Проверьте с $20 + $5 бонуса",
    ctoOfferBody: "Сначала запустите реальную нагрузку. Если routing, качество и логи подходят, свяжитесь с нами для командных объёмов.",
    createTestKey: "Создать тестовый key",
    ctoProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая модель работает через свои официальные upstream-токены, с доверенными источниками и подлинным качеством для команд.",
    ctoEvidenceGatewayTitle: "Gateway для продуктового ИИ",
    ctoEvidenceGatewayBody: "Добавляйте ИИ в систему с совместимым key и понятным следом использования.",
    ctoEvidenceAgentsTitle: "Дешевле developer agents",
    ctoEvidenceAgentsBody: "Маршрутизируйте Codex, Claude Code и инженерные циклы через более дешёвое измеряемое использование.",
    ctoEvidenceQuotaTitle: "Меньше quota-блокировок",
    ctoEvidenceQuotaBody: "Снижайте трение, когда официальные аккаунты упираются в rate, quota или операционные лимиты.",
    ctoStepKeyTitle: "Создайте тестовый key",
    ctoStepKeyBody: "Используйте регистрацию, чтобы создать контролируемый key для проверки.",
    ctoStepWorkloadTitle: "Запустите реальную нагрузку",
    ctoStepWorkloadBody: "Сравните задержку, качество, логи и стоимость с текущим routing.",
    ctoStepScaleTitle: "Масштабируйте после проверки",
    ctoStepScaleBody: "Переходите на крупные предоплаченные пакеты или запросите командный план.",
    ctoFaq1Q: "Нужно много менять в коде?",
    ctoFaq1A: "Большинству OpenAI-compatible интеграций достаточно поменять base URL и key.",
    ctoFaq2Q: "Можно проверить до обязательств?",
    ctoFaq2A: "Да. Начните с $20 плюс $5 бонуса и измерьте реальную нагрузку.",
    ctoFaq3Q: "Подходит для нескольких инженеров?",
    ctoFaq3A: "Да. Flatkey централизует keys, балансы и логи для контроля общего использования.",
    ctoFinalTitle: "Докажите 40% экономии на своей нагрузке",
    ctoFinalBody: "Начните с небольшого key, проверьте качество routing и решите, масштабировать ли команду.",
    imageEyebrow: "Image Buddy для операционных команд",
    imageBadge: "Workflow изображений с меньшей стоимостью",
    imageTitle: "Создавайте campaign images быстрее с ИИ на 40% дешевле",
    imageAccent: "и повторяемыми workflows",
    imageDescription: "Flatkey снижает стоимость генерации изображений, а Image Buddy даёт готовые workflows вместо постоянного поиска prompts.",
    imageOfferTitle: "Создайте key, затем установите Image Buddy",
    imageOfferBody: "Используйте Flatkey для мощности и цены. Используйте templates Image Buddy для продукта, рекламы, marketplace и кампаний.",
    createKeyFirst: "Сначала создать key",
    imageProofTitle: "Стабильное качество для регулярной генерации",
    imageProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая image и text model работает через свои официальные upstream-токены, надёжная основа для регулярной генерации.",
    imageEvidencePromptTitle: "Меньше поиска prompts",
    imageEvidencePromptBody: "Начинайте с повторяемых workflows Image Buddy вместо переписывания image prompts.",
    imageEvidenceQuotaTitle: "Меньше остановок из-за quota",
    imageEvidenceQuotaBody: "Используйте routing Flatkey, чтобы снизить трение от частых лимитов генерации.",
    imageEvidenceAssetTitle: "Assets для кампаний",
    imageEvidenceAssetBody: "Быстрее создавайте product visuals, ads, marketplace и social creatives.",
    imageStepKeyTitle: "Создайте key Flatkey",
    imageStepKeyBody: "Зарегистрируйтесь и создайте key, который будет использовать Image Buddy.",
    imageStepInstallTitle: "Установите Image Buddy",
    imageStepInstallBody: "Следуйте GitHub guide, чтобы добавить workflow в окружение.",
    imageStepGenerateTitle: "Генерируйте с templates",
    imageStepGenerateBody: "Выберите workflow, добавьте product context и создавайте полезные изображения.",
    imageFaq1Q: "Image Buddy только для разработчиков?",
    imageFaq1A: "Нет. Он упаковывает image prompts в повторяемые workflows для operations и команд.",
    imageFaq2Q: "Почему сначала создать key?",
    imageFaq2A: "Key включает routing Flatkey и capacity генерации до запросов Image Buddy.",
    imageFaq3Q: "Подходит для ecommerce?",
    imageFaq3A: "Да. Поддерживает product shots, marketplace cards, ads и регулярные creative needs.",
    imageFinalTitle: "Создайте key перед следующей партией изображений",
    imageFinalBody: "Сначала настройте Flatkey, затем используйте Image Buddy быстрее и дешевле.",
  },
  ja: {
    sectionLabels: {
      startEyebrow: "開始手順",
      startTitle: "メールクリックから使えるkeyまで",
      faqEyebrow: "質問",
      faqTitle: "試す前の短い回答",
    },
    personalEyebrow: "個人向けAI節約",
    personalBadge: "$20チャージで$5ボーナス",
    personalTitle: "主要AIモデルを40%安いtokenで利用",
    personalAccent: "残高は失効しにくい",
    personalDescription: "Flatkey API keyを作成し、小額チャージで試し、多くの有名モデルを固定月額プランなしで使えます。",
    personalHighlight: "Plusを月$20のプランとして見ているなら、Flatkeyは同じ$20をもっと長く使えます。$5ボーナス、40%安い公式token、月ごとに消えない約3xのAI予算です。",
    personalOfferTitle: "期限切れしにくいGPT風パワープラン",
    personalOfferBody: "$20をチャージして$5ボーナスを獲得。高額チャージではさらに大きなボーナスがあり、個人の高頻度利用には$200枠も使えます。",
    createKey: "keyを作成して試す",
    proofTitle: "公式tokenによる信頼できる品質",
    personalProofBody: "Flatkeyは10 billion tokens通過でOpenAIから認定を受けています。対応する全モデルはそれぞれの公式upstream tokensで提供され、信頼できるソースと本来のモデル品質を保ちます。",
    evidenceCheapTitle: "tokenが40%安い",
    personalCheapBody: "同じ予算でより多くのprompt、coding run、画像テストを実行できます。",
    evidenceModelsTitle: "多くの有名モデル",
    personalModelsBody: "GPT、Claude、Gemini、画像モデルなどを1つの互換keyで利用できます。",
    evidenceAgentsTitle: "CodexとClaude Code対応",
    personalAgentsBody: "key作成後、開発ツールを接続でき、複数残高を管理する必要がありません。",
    stepKeyTitle: "keyを作成",
    personalStepKeyBody: "登録後、そのままAPI keyページへ移動します。",
    stepRechargeTitle: "$20からチャージ",
    personalStepRechargeBody: "$5ボーナスで自分のworkflowを検証できます。",
    stepUseTitle: "対応モデルを利用",
    personalStepUseBody: "apps、scripts、Codex、Claude CodeをFlatkeyへ向けます。",
    personalFaq1Q: "残高は失効しますか？",
    personalFaq1A: "Flatkeyのプリペイド残高は継続利用向けで、未使用分を失う月額プランではありません。",
    personalFaq2Q: "モデル品質は落ちますか？",
    personalFaq2A: "いいえ。Flatkeyは公式upstream tokens経由でroutingし、provider品質を保ちます。",
    personalFaq3Q: "小さく始められますか？",
    personalFaq3A: "はい。$20チャージと$5ボーナスは、本格利用前の検証用です。",
    personalFinalTitle: "小さなkeyテストから開始",
    personalFinalBody: "keyを作成し、実際のworkflowでコストと品質を確認してから判断できます。",
    ctoEyebrow: "CTO向けAIコスト削減",
    ctoBadge: "今日からAI支出を40%削減",
    ctoTitle: "AI APIと開発AIコストを40%削減",
    ctoAccent: "既存stackのままで",
    ctoDescription: "Flatkeyはproduct AI、developer agents、logs、prepaid balance、quota問題を1つの互換gatewayにまとめます。",
    ctoOfferTitle: "$20 + $5ボーナスで検証",
    ctoOfferBody: "まず実 workload を流してください。routing、品質、logsが基準を満たせば、大容量team pricingへ進めます。",
    createTestKey: "テストkeyを作成",
    ctoProofBody: "Flatkeyは10 billion tokens通過でOpenAIから認定を受けています。対応する全モデルはそれぞれの公式upstream tokensで提供され、team向けにも信頼できるソースと本来の品質を保ちます。",
    ctoEvidenceGatewayTitle: "Product AI gateway",
    ctoEvidenceGatewayBody: "互換keyと明確なusage trailで、既存システムにAI能力を追加できます。",
    ctoEvidenceAgentsTitle: "開発agentを低コスト化",
    ctoEvidenceAgentsBody: "Codex、Claude Code、engineering loopを低コストな従量課金へroutingします。",
    ctoEvidenceQuotaTitle: "quota詰まりを軽減",
    ctoEvidenceQuotaBody: "公式アカウントのrate、quota、運用制限に当たる摩擦を減らします。",
    ctoStepKeyTitle: "テストkeyを作成",
    ctoStepKeyBody: "登録flowで管理しやすい検証用keyを作ります。",
    ctoStepWorkloadTitle: "実 workload を実行",
    ctoStepWorkloadBody: "現在のroutingとlatency、品質、logs、コストを比較します。",
    ctoStepScaleTitle: "検証後にscale",
    ctoStepScaleBody: "大きなprepaid packageまたはteam planへ移行できます。",
    ctoFaq1Q: "多くのコード変更が必要ですか？",
    ctoFaq1A: "多くのOpenAI-compatible integrationはbase URLとkey変更だけで済みます。",
    ctoFaq2Q: "契約前に検証できますか？",
    ctoFaq2A: "はい。$20と$5ボーナスで実 workload を測定できます。",
    ctoFaq3Q: "複数エンジニアに向きますか？",
    ctoFaq3A: "はい。Flatkeyはkeys、balance、logsを集中管理し、shared usageを制御できます。",
    ctoFinalTitle: "自社workloadで40%削減を確認",
    ctoFinalBody: "小さなkeyから始め、routing品質を確認してteam scaleを判断できます。",
    imageEyebrow: "運用向けImage Buddy",
    imageBadge: "低コスト画像生成workflow",
    imageTitle: "40%安いAI usageでcampaign imagesをより速く生成",
    imageAccent: "再利用可能workflow付き",
    imageDescription: "Flatkeyは画像生成コストを下げ、Image Buddyは毎回promptを探さずに使えるworkflowを提供します。",
    imageOfferTitle: "key作成後にImage Buddyをinstall",
    imageOfferBody: "Flatkeyで生成capacityと低コストを確保し、Image Buddy templatesでproduct、ads、marketplace、campaign画像を作ります。",
    createKeyFirst: "先にkeyを作成",
    imageProofTitle: "継続的な生成でも安定した品質",
    imageProofBody: "Flatkeyは10 billion tokens通過でOpenAI認定を受けています。対応する画像・テキストモデルはそれぞれの公式upstream tokensで提供され、継続的なcreative generationの信頼できる基盤になります。",
    imageEvidencePromptTitle: "prompt探しを削減",
    imageEvidencePromptBody: "毎回image promptを書き直す代わりに、Image Buddyの再利用workflowから始めます。",
    imageEvidenceQuotaTitle: "quota停止を軽減",
    imageEvidenceQuotaBody: "Flatkey routingで、よくあるgeneration limitによる停止を減らします。",
    imageEvidenceAssetTitle: "campaign-ready assets",
    imageEvidenceAssetBody: "product visuals、ads、marketplace、social creativesをより速く作れます。",
    imageStepKeyTitle: "Flatkey keyを作成",
    imageStepKeyBody: "登録し、Image Buddyが使うkeyを作成します。",
    imageStepInstallTitle: "Image Buddyをinstall",
    imageStepInstallBody: "GitHub guideに従い、workflowを環境へ追加します。",
    imageStepGenerateTitle: "templatesで生成",
    imageStepGenerateBody: "workflowを選び、product contextを加えて使える画像を作ります。",
    imageFaq1Q: "Image Buddyは開発者専用ですか？",
    imageFaq1A: "いいえ。画像promptをoperationsやteam向けの反復可能workflowにします。",
    imageFaq2Q: "なぜ先にkeyを作るのですか？",
    imageFaq2A: "keyがFlatkey routingとgeneration capacityを有効にし、その後Image Buddyがrequestを送ります。",
    imageFaq3Q: "ecommerceに使えますか？",
    imageFaq3A: "はい。product shots、marketplace cards、adsなど反復creative needsに使えます。",
    imageFinalTitle: "次の画像バッチ前にkeyを作成",
    imageFinalBody: "まずFlatkeyを設定し、Image Buddyで反復creative workを速く安くします。",
  },
  vi: {
    sectionLabels: {
      startEyebrow: "Đường bắt đầu",
      startTitle: "Từ click email đến key dùng được",
      faqEyebrow: "Câu hỏi",
      faqTitle: "Câu trả lời ngắn trước khi thử",
    },
    personalEyebrow: "Tiết kiệm AI cá nhân",
    personalBadge: "Nạp $20 nhận $5 bonus",
    personalTitle: "Dùng các mô hình AI nổi tiếng với token rẻ hơn 40%",
    personalAccent: "và số dư không mất theo tháng",
    personalDescription: "Tạo một API key Flatkey, thử bằng khoản nạp nhỏ và dùng nhiều mô hình nổi tiếng mà không cần thêm gói tháng cố định.",
    personalHighlight: "Nếu bạn xem Plus là gói $20/tháng, Flatkey giúp cùng $20 dùng được lâu hơn: thêm $5 bonus, token chính thức rẻ hơn 40% và gần 3x ngân sách AI khả dụng không bị reset mỗi tháng.",
    personalOfferTitle: "Một gói mạnh kiểu GPT không hết hạn",
    personalOfferBody: "Nạp $20 và nhận $5 bonus. Các mức nạp lớn hơn có bonus lớn hơn, gồm mức $200 cho cá nhân dùng nhiều.",
    createKey: "Tạo key và thử",
    proofTitle: "Chất lượng đáng tin từ token chính thức",
    personalProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình được hỗ trợ đều dùng upstream tokens chính thức tương ứng, từ nguồn đáng tin cậy và giữ chất lượng nguyên bản.",
    evidenceCheapTitle: "Token rẻ hơn 40%",
    personalCheapBody: "Cùng ngân sách có thể chạy nhiều prompt, lượt code và thử nghiệm ảnh hơn.",
    evidenceModelsTitle: "Nhiều mô hình nổi tiếng",
    personalModelsBody: "Dùng GPT, Claude, Gemini, mô hình ảnh và nhiều mô hình khác sau một key tương thích.",
    evidenceAgentsTitle: "Sẵn sàng cho Codex và Claude Code",
    personalAgentsBody: "Kết nối công cụ lập trình sau khi tạo key, không cần quản lý nhiều số dư.",
    stepKeyTitle: "Tạo key của bạn",
    personalStepKeyBody: "Đăng ký và vào thẳng trang API keys.",
    stepRechargeTitle: "Nạp từ $20",
    personalStepRechargeBody: "Bắt đầu với $5 bonus và kiểm tra workflow của bạn.",
    stepUseTitle: "Dùng mọi mô hình hỗ trợ",
    personalStepUseBody: "Trỏ apps, scripts, Codex hoặc Claude Code tới Flatkey.",
    personalFaq1Q: "Số dư có hết hạn không?",
    personalFaq1A: "Số dư trả trước Flatkey dành cho sử dụng lâu dài, không phải gói tháng bị mất nếu không dùng.",
    personalFaq2Q: "Chất lượng mô hình có giảm không?",
    personalFaq2A: "Không. Flatkey route qua upstream tokens chính thức và giữ chất lượng provider.",
    personalFaq3Q: "Tôi có thể bắt đầu nhỏ không?",
    personalFaq3A: "Có. Nạp $20 cùng $5 bonus là để thử trước khi dùng nhiều hơn.",
    personalFinalTitle: "Bắt đầu bằng một key nhỏ",
    personalFinalBody: "Tạo key, thử workflow thật rồi quyết định sau khi thấy chi phí và chất lượng.",
    ctoEyebrow: "Tiết kiệm AI cho CTO",
    ctoBadge: "Giảm 40% chi phí AI ngay hôm nay",
    ctoTitle: "Giảm 40% chi phí AI API và AI cho kỹ thuật",
    ctoAccent: "không cần đổi stack",
    ctoDescription: "Flatkey cho đội ngũ một gateway tương thích cho AI sản phẩm, developer agents, logs, số dư trả trước và ít nghẽn quota hơn.",
    ctoOfferTitle: "Xác minh với $20 + $5 bonus",
    ctoOfferBody: "Chạy workload thật trước. Nếu routing, chất lượng và logs đạt chuẩn, hãy liên hệ để có giá team volume cao hơn.",
    createTestKey: "Tạo key thử nghiệm",
    ctoProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình được hỗ trợ đều dùng upstream tokens chính thức tương ứng, từ nguồn đáng tin cậy và giữ chất lượng nguyên bản cho đội ngũ.",
    ctoEvidenceGatewayTitle: "Gateway AI cho sản phẩm",
    ctoEvidenceGatewayBody: "Thêm AI vào hệ thống bằng một key tương thích và đường ghi nhận usage rõ ràng.",
    ctoEvidenceAgentsTitle: "Developer agents rẻ hơn",
    ctoEvidenceAgentsBody: "Route Codex, Claude Code và vòng lặp kỹ thuật qua mức sử dụng đo đếm chi phí thấp hơn.",
    ctoEvidenceQuotaTitle: "Ít bị kẹt quota hơn",
    ctoEvidenceQuotaBody: "Giảm ma sát khi tài khoản chính thức gặp rate, quota hoặc giới hạn vận hành.",
    ctoStepKeyTitle: "Tạo key thử nghiệm",
    ctoStepKeyBody: "Dùng luồng đăng ký để tạo key kiểm chứng có kiểm soát.",
    ctoStepWorkloadTitle: "Chạy workload thật",
    ctoStepWorkloadBody: "So sánh latency, chất lượng, logs và chi phí với routing hiện tại.",
    ctoStepScaleTitle: "Mở rộng sau khi xác minh",
    ctoStepScaleBody: "Chuyển sang gói trả trước lớn hơn hoặc hỏi plan team.",
    ctoFaq1Q: "Có cần đổi nhiều code không?",
    ctoFaq1A: "Phần lớn tích hợp OpenAI-compatible chỉ cần đổi base URL và key.",
    ctoFaq2Q: "Có thể xác minh trước cam kết không?",
    ctoFaq2A: "Có. Bắt đầu với $20 cộng $5 bonus và đo workload thật.",
    ctoFaq3Q: "Có phù hợp nhiều kỹ sư không?",
    ctoFaq3A: "Có. Flatkey tập trung keys, số dư và logs để kiểm soát usage chung.",
    ctoFinalTitle: "Chứng minh 40% tiết kiệm trên workload của bạn",
    ctoFinalBody: "Bắt đầu bằng key nhỏ, kiểm tra chất lượng routing rồi quyết định mở rộng team.",
    imageEyebrow: "Image Buddy cho vận hành",
    imageBadge: "Workflow ảnh chi phí thấp hơn",
    imageTitle: "Tạo campaign images nhanh hơn với AI rẻ hơn 40%",
    imageAccent: "và workflow tái sử dụng",
    imageDescription: "Flatkey giảm chi phí tạo ảnh, còn Image Buddy cung cấp workflow sẵn dùng thay vì phải tìm prompt mỗi lần.",
    imageOfferTitle: "Tạo key rồi cài Image Buddy",
    imageOfferBody: "Dùng Flatkey cho capacity và chi phí thấp hơn. Dùng templates Image Buddy cho sản phẩm, ads, marketplace và campaign.",
    createKeyFirst: "Tạo key trước",
    imageProofTitle: "Chất lượng ổn định cho sáng tạo lặp lại",
    imageProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình ảnh và văn bản được hỗ trợ đều dùng upstream tokens chính thức tương ứng, là nền tảng đáng tin cậy cho sáng tạo lặp lại.",
    imageEvidencePromptTitle: "Ít phải tìm prompt",
    imageEvidencePromptBody: "Bắt đầu từ workflow Image Buddy tái sử dụng thay vì viết lại image prompts.",
    imageEvidenceQuotaTitle: "Ít dừng vì quota",
    imageEvidenceQuotaBody: "Dùng Flatkey routing để giảm ma sát từ các giới hạn tạo ảnh thường gặp.",
    imageEvidenceAssetTitle: "Assets sẵn cho campaign",
    imageEvidenceAssetBody: "Tạo product visuals, ads, marketplace và social creatives nhanh hơn.",
    imageStepKeyTitle: "Tạo key Flatkey",
    imageStepKeyBody: "Đăng ký và tạo key mà Image Buddy sẽ dùng.",
    imageStepInstallTitle: "Cài Image Buddy",
    imageStepInstallBody: "Theo hướng dẫn GitHub để thêm workflow vào môi trường của bạn.",
    imageStepGenerateTitle: "Tạo bằng templates",
    imageStepGenerateBody: "Chọn workflow, thêm ngữ cảnh sản phẩm và tạo ảnh dùng được.",
    imageFaq1Q: "Image Buddy chỉ dành cho developer?",
    imageFaq1A: "Không. Nó đóng gói image prompts thành workflow lặp lại cho vận hành và đội nhóm.",
    imageFaq2Q: "Vì sao tạo key trước?",
    imageFaq2A: "Key mở Flatkey routing và capacity tạo ảnh trước khi Image Buddy gửi request.",
    imageFaq3Q: "Có dùng cho ecommerce không?",
    imageFaq3A: "Có. Hỗ trợ product shots, marketplace cards, ads và nhu cầu sáng tạo lặp lại.",
    imageFinalTitle: "Tạo key trước batch ảnh tiếp theo",
    imageFinalBody: "Cài Flatkey trước, rồi dùng Image Buddy để làm nhanh hơn và rẻ hơn.",
  },
  de: {
    sectionLabels: {
      startEyebrow: "Startpfad",
      startTitle: "Vom E-Mail-Klick zum funktionierenden key",
      faqEyebrow: "Fragen",
      faqTitle: "Kurze Antworten vor dem Test",
    },
    personalEyebrow: "Persönliche KI-Ersparnis",
    personalBadge: "$20 aufladen und $5 Bonus erhalten",
    personalTitle: "Nutze bekannte KI-Modelle mit 40% günstigeren Tokens",
    personalAccent: "und Guthaben ohne Monatsverfall",
    personalDescription: "Erstelle einen Flatkey API key, teste mit kleiner Aufladung und nutze viele bekannte Modelle ohne weiteres fixes Monatsabo.",
    personalHighlight: "Wenn du Plus als $20/Monat-Plan kennst, macht Flatkey dieselben $20 ergiebiger: $5 Bonus, 40% günstigere offizielle Tokens und fast 3x nutzbares KI-Budget ohne monatlichen Reset.",
    personalOfferTitle: "Ein starkes GPT-ähnliches Paket ohne Verfall",
    personalOfferBody: "Lade $20 auf und erhalte $5 Bonus. Größere Aufladungen bringen mehr Bonus, inklusive $200-Optionen für intensive private Nutzung.",
    createKey: "Key erstellen und testen",
    proofTitle: "Verlässliche Qualität über offizielle Tokens",
    personalProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Modell läuft über seine offiziellen upstream Tokens, mit vertrauenswürdigen Quellen und authentischer Modellqualität.",
    evidenceCheapTitle: "Tokens 40% günstiger",
    personalCheapBody: "Dasselbe Budget reicht für mehr Prompts, Coding-Läufe und Bildtests.",
    evidenceModelsTitle: "Viele bekannte Modelle",
    personalModelsBody: "Nutze GPT, Claude, Gemini, Bildmodelle und mehr mit einem kompatiblen key.",
    evidenceAgentsTitle: "Bereit für Codex und Claude Code",
    personalAgentsBody: "Verbinde Developer-Tools nach dem key-Erstellen, ohne mehrere Guthaben zu pflegen.",
    stepKeyTitle: "Erstelle deinen key",
    personalStepKeyBody: "Registriere dich und lande direkt auf der API-key-Seite.",
    stepRechargeTitle: "Ab $20 aufladen",
    personalStepRechargeBody: "Starte mit $5 Bonus und prüfe deinen eigenen Workflow.",
    stepUseTitle: "Nutze jedes unterstützte Modell",
    personalStepUseBody: "Richte apps, scripts, Codex oder Claude Code auf Flatkey.",
    personalFaq1Q: "Verfällt das Guthaben?",
    personalFaq1A: "Flatkey-Prepaid-Guthaben ist für Nutzung über Zeit gedacht, nicht als verlorenes Monatsabo.",
    personalFaq2Q: "Sinkt die Modellqualität?",
    personalFaq2A: "Nein. Flatkey routet über offizielle upstream tokens und hält Provider-Qualität.",
    personalFaq3Q: "Kann ich klein anfangen?",
    personalFaq3A: "Ja. $20 Aufladung plus $5 Bonus ist für schnelles Testen vor größerer Nutzung gedacht.",
    personalFinalTitle: "Starte mit einem kleinen key-Test",
    personalFinalBody: "Erstelle einen key, teste deinen echten Workflow und entscheide anhand von Kosten und Qualität.",
    ctoEyebrow: "KI-Ersparnis für CTOs",
    ctoBadge: "Heute 40% KI-Kosten senken",
    ctoTitle: "Senke AI API und Engineering-KI-Kosten um 40%",
    ctoAccent: "ohne Stack-Wechsel",
    ctoDescription: "Flatkey gibt deinem Team ein kompatibles Gateway für Produkt-KI, Developer Agents, Logs, Prepaid-Guthaben und weniger quota-Blockaden.",
    ctoOfferTitle: "Mit $20 + $5 Bonus validieren",
    ctoOfferBody: "Führe zuerst reale Last aus. Wenn routing, Qualität und logs passen, kontaktiere uns für Team-Preise mit höherem Volumen.",
    createTestKey: "Test-key erstellen",
    ctoProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Modell läuft über seine offiziellen upstream Tokens, mit vertrauenswürdigen Quellen und authentischer Qualität für Teams.",
    ctoEvidenceGatewayTitle: "Produkt-KI-Gateway",
    ctoEvidenceGatewayBody: "Füge deinem System KI hinzu, mit kompatiblem key und klarer Nutzungsspur.",
    ctoEvidenceAgentsTitle: "Günstigere Developer Agents",
    ctoEvidenceAgentsBody: "Route Codex, Claude Code und Engineering-Schleifen über günstiger gemessene Nutzung.",
    ctoEvidenceQuotaTitle: "Weniger quota-Blockaden",
    ctoEvidenceQuotaBody: "Reduziere Reibung, wenn offizielle Konten rate, quota oder Betriebslimits erreichen.",
    ctoStepKeyTitle: "Test-key erstellen",
    ctoStepKeyBody: "Nutze Signup, um einen kontrollierten key für Validierung zu erstellen.",
    ctoStepWorkloadTitle: "Reale Last ausführen",
    ctoStepWorkloadBody: "Vergleiche Latenz, Qualität, logs und Kosten mit aktuellem routing.",
    ctoStepScaleTitle: "Nach Validierung skalieren",
    ctoStepScaleBody: "Wechsle zu größeren Prepaid-Paketen oder frage nach einem Team-Plan.",
    ctoFaq1Q: "Brauchen wir viele Codeänderungen?",
    ctoFaq1A: "Die meisten OpenAI-compatible Integrationen ändern nur base URL und key.",
    ctoFaq2Q: "Können wir vor Commitment validieren?",
    ctoFaq2A: "Ja. Starte mit $20 plus $5 Bonus und miss eine reale Last.",
    ctoFaq3Q: "Passt es für mehrere Engineers?",
    ctoFaq3A: "Ja. Flatkey zentralisiert keys, Guthaben und logs für gemeinsame Nutzungskontrolle.",
    ctoFinalTitle: "Beweise 40% Ersparnis mit deiner Last",
    ctoFinalBody: "Starte mit kleinem key, prüfe routing-Qualität und entscheide dann über Team-Skalierung.",
    imageEyebrow: "Image Buddy für Operations",
    imageBadge: "Bild-Workflow mit geringeren Kosten",
    imageTitle: "Erstelle campaign images schneller mit 40% günstigerer KI",
    imageAccent: "und wiederverwendbaren Workflows",
    imageDescription: "Flatkey senkt Bildgenerierungskosten, während Image Buddy fertige Workflows statt ständiger prompt-Suche liefert.",
    imageOfferTitle: "Key erstellen, dann Image Buddy installieren",
    imageOfferBody: "Nutze Flatkey für capacity und geringere Kosten. Nutze Image Buddy templates für Produkte, Anzeigen, Marketplace und Kampagnen.",
    createKeyFirst: "Zuerst key erstellen",
    imageProofTitle: "Stabile Qualität für wiederholte Kreativarbeit",
    imageProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Bild- und Textmodell läuft über seine offiziellen upstream Tokens, eine vertrauenswürdige Basis für wiederholte Kreativarbeit.",
    imageEvidencePromptTitle: "Weniger prompt-Suche",
    imageEvidencePromptBody: "Starte mit wiederverwendbaren Image Buddy Workflows statt jedes image prompt neu zu schreiben.",
    imageEvidenceQuotaTitle: "Weniger quota-Stopps",
    imageEvidenceQuotaBody: "Nutze Flatkey routing, um Reibung durch häufige Generierungslimits zu senken.",
    imageEvidenceAssetTitle: "Assets für Kampagnen",
    imageEvidenceAssetBody: "Erstelle Produktbilder, ads, Marketplace-Assets und social creatives schneller.",
    imageStepKeyTitle: "Flatkey key erstellen",
    imageStepKeyBody: "Registriere dich und erstelle den key, den Image Buddy nutzt.",
    imageStepInstallTitle: "Image Buddy installieren",
    imageStepInstallBody: "Folge der GitHub-Anleitung, um den Workflow in deine Umgebung einzubinden.",
    imageStepGenerateTitle: "Mit templates generieren",
    imageStepGenerateBody: "Wähle Workflow, füge Produktkontext hinzu und erstelle nutzbare Bilder.",
    imageFaq1Q: "Ist Image Buddy nur für Developer?",
    imageFaq1A: "Nein. Es verpackt image prompts in wiederholbare Workflows für Operations und Teams.",
    imageFaq2Q: "Warum zuerst einen key erstellen?",
    imageFaq2A: "Der key aktiviert Flatkey routing und Generierungskapazität, bevor Image Buddy requests sendet.",
    imageFaq3Q: "Geht das für ecommerce?",
    imageFaq3A: "Ja. Unterstützt product shots, marketplace cards, ads und wiederkehrende creative needs.",
    imageFinalTitle: "Erstelle den key vor dem nächsten Bild-Batch",
    imageFinalBody: "Richte Flatkey zuerst ein und nutze Image Buddy schneller und günstiger.",
  },
};

export function getEdmCampaign(campaignId: EdmCampaignId, locale: Locale): EdmCampaignCopy {
  return CAMPAIGN_COPY[locale][campaignId];
}

export function getEdmCtaUrl(origin?: string): string {
  return origin ? `${origin.replace(/\/+$/, "")}/sign-up?redirect=/keys` : consoleUrl("/sign-up", "redirect=/keys");
}

export function getEdmMetadataInput(campaignId: EdmCampaignId, locale: Locale): SeoInput {
  const campaign = getEdmCampaign(campaignId, locale);
  return {
    title: `${campaign.hero.title} ${campaign.hero.accent}`,
    description: campaign.hero.description,
    pathname: EDM_LANDING_PATHS[campaignId],
    locale,
    noIndex: true,
  };
}
