import { consoleUrl } from "@/lib/origins";
import type { Locale } from "@/lib/locales";
import type { SeoInput } from "@/lib/seo";

export const EDM_CAMPAIGN_IDS = ["personal-ai", "cto-ai-savings", "image-buddy"] as const;
export type EdmCampaignId = (typeof EDM_CAMPAIGN_IDS)[number];

export const EDM_LANDING_PATHS: Record<EdmCampaignId, string> = {
  "personal-ai": "/lp/personal-ai",
  "cto-ai-savings": "/lp/cto-ai-savings",
  "image-buddy": "/lp/image-buddy",
};

export type EdmCampaignCopy = {
  eyebrow: string;
  badge: string;
  hero: {
    title: string;
    accent: string;
    description: string;
    highlight?: string;
  };
  offer: {
    title: string;
    body: string;
  };
  primaryCta: string;
  ctaNote: string;
  secondaryCta?: {
    label: string;
    href: string;
  };
  heroPanel?: {
    kicker: string;
    title: string;
    rows: Array<{ label: string; value: string; body: string }>;
    footnote: string;
  };
  quickStart?: {
    title: string;
    body: string;
    agentAction: string;
    sdkAction: string;
  };
  showcase?: Array<{ src: string; title: string; body: string; alt: string; wide?: boolean }>;
  proof: {
    title: string;
    body: string;
  };
  evidence: Array<{ title: string; body: string }>;
  steps: Array<{ title: string; body: string }>;
  faqs: Array<{ question: string; answer: string }>;
  sectionLabels: {
    startEyebrow: string;
    startTitle: string;
    faqEyebrow: string;
    faqTitle: string;
  };
  finalTitle: string;
  finalBody: string;
};

type CampaignRecord = Record<EdmCampaignId, EdmCampaignCopy>;

const imageBuddyLink = {
  label: "GitHub: flatkey-ai/awesome-images",
  href: "https://github.com/flatkey-ai/awesome-images",
};

const imageBuddyShowcases: Record<Locale, EdmCampaignCopy["showcase"]> = {
  en: [
    {
      src: "/use-case/image-buddy/premium-product-hero.jpg",
      title: "Premium product hero",
      body: "Turn a short product idea into a landing-page or campaign hero image.",
      alt: "Generated hero image of a ceramic coffee mug near a sunny beach",
      wide: true,
    },
    {
      src: "/use-case/image-buddy/marketplace-main-image.jpg",
      title: "Marketplace main image",
      body: "Create clean ecommerce listing images for Amazon-style marketplaces.",
      alt: "Generated marketplace product image of a stainless steel water bottle on white background",
    },
    {
      src: "/use-case/image-buddy/ugc-ad-still.jpg",
      title: "UGC ad still",
      body: "Generate social ad stills and lifestyle scenes from reusable prompt workflows.",
      alt: "Generated UGC style image of a hand holding amber skincare serum in a bright bathroom",
    },
  ],
  zh: [
    {
      src: "/use-case/image-buddy/premium-product-hero.jpg",
      title: "高端产品主视觉",
      body: "把一句产品想法变成落地页或活动主视觉。",
      alt: "生成的海边阳光陶瓷咖啡杯主视觉",
      wide: true,
    },
    {
      src: "/use-case/image-buddy/marketplace-main-image.jpg",
      title: "Marketplace 主图",
      body: "生成适合 Amazon 等电商 listing 的干净产品主图。",
      alt: "生成的白底不锈钢水瓶电商主图",
    },
    {
      src: "/use-case/image-buddy/ugc-ad-still.jpg",
      title: "UGC 广告图",
      body: "用可复用提示词工作流生成社媒广告图和生活方式场景。",
      alt: "生成的手持琥珀色护肤精华瓶 UGC 风格图片",
    },
  ],
  es: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero de producto premium", body: "Convierte una idea corta en un hero para landing page o campaña.", alt: "Hero generado de una taza cerámica junto a una playa soleada", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Imagen principal marketplace", body: "Crea imágenes limpias para listings ecommerce tipo Amazon.", alt: "Imagen generada de botella de acero inoxidable sobre fondo blanco" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Still de anuncio UGC", body: "Genera anuncios sociales y escenas lifestyle desde workflows reutilizables.", alt: "Imagen UGC generada de una mano con serum ámbar en un baño luminoso" },
  ],
  fr: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero produit premium", body: "Transformez une idée produit courte en hero de landing page ou de campagne.", alt: "Hero généré d'un mug en céramique près d'une plage ensoleillée", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Image principale marketplace", body: "Créez des images propres pour listings ecommerce type Amazon.", alt: "Image générée d'une gourde inox sur fond blanc" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Visuel publicitaire UGC", body: "Générez des visuels social ads et scènes lifestyle via workflows réutilisables.", alt: "Image UGC générée d'une main tenant un sérum ambré dans une salle de bain lumineuse" },
  ],
  pt: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero premium de produto", body: "Transforme uma ideia curta em hero para landing page ou campanha.", alt: "Hero gerado de uma caneca cerâmica perto de uma praia ensolarada", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Imagem principal marketplace", body: "Crie imagens limpas para listings ecommerce estilo Amazon.", alt: "Imagem gerada de garrafa inox em fundo branco" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Still de anúncio UGC", body: "Gere social ads e cenas lifestyle com workflows reutilizáveis.", alt: "Imagem UGC gerada de uma mão segurando sérum âmbar em banheiro claro" },
  ],
  ru: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Премиальный product hero", body: "Превращайте короткую идею продукта в hero для лендинга или кампании.", alt: "Сгенерированный hero-визуал керамической кружки у солнечного пляжа", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Главное изображение marketplace", body: "Создавайте чистые ecommerce listing images для marketplace вроде Amazon.", alt: "Сгенерированное изображение стальной бутылки на белом фоне" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC ad still", body: "Генерируйте social ads и lifestyle-сцены из повторяемых workflows.", alt: "Сгенерированное UGC-изображение руки с янтарной сывороткой в светлой ванной" },
  ],
  ja: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "プレミアム商品 hero", body: "短い商品アイデアを landing page や campaign の hero に変換します。", alt: "晴れた海辺の陶器マグを生成した hero 画像", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Marketplace メイン画像", body: "Amazon listing 向けのクリーンな ecommerce 商品画像を作成します。", alt: "白背景のステンレスボトルを生成した商品画像" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC 広告画像", body: "再利用workflowから social ad と lifestyle scene を生成します。", alt: "明るい浴室で琥珀色の美容液を持つ手の UGC 風生成画像" },
  ],
  vi: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Hero sản phẩm premium", body: "Biến ý tưởng sản phẩm ngắn thành hero cho landing page hoặc campaign.", alt: "Ảnh hero được tạo của ly gốm cạnh bãi biển nắng", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Ảnh chính marketplace", body: "Tạo ảnh listing ecommerce sạch cho marketplace kiểu Amazon.", alt: "Ảnh sản phẩm bình nước inox nền trắng được tạo" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "Ảnh quảng cáo UGC", body: "Tạo social ads và cảnh lifestyle từ workflow prompt tái sử dụng.", alt: "Ảnh UGC được tạo của tay cầm serum màu hổ phách trong phòng tắm sáng" },
  ],
  de: [
    { src: "/use-case/image-buddy/premium-product-hero.jpg", title: "Premium Product Hero", body: "Verwandle eine kurze Produktidee in ein Hero-Bild für Landingpage oder Kampagne.", alt: "Generiertes Hero-Bild eines Keramikbechers an einem sonnigen Strand", wide: true },
    { src: "/use-case/image-buddy/marketplace-main-image.jpg", title: "Marketplace-Hauptbild", body: "Erstelle saubere ecommerce Listing-Bilder für Amazon-ähnliche Marketplaces.", alt: "Generiertes Produktbild einer Edelstahlflasche auf weißem Hintergrund" },
    { src: "/use-case/image-buddy/ugc-ad-still.jpg", title: "UGC-Ad-Still", body: "Generiere social ads und lifestyle scenes aus wiederverwendbaren workflows.", alt: "Generiertes UGC-Bild einer Hand mit bernsteinfarbenem Serum in hellem Bad" },
  ],
};

const CAMPAIGN_COPY: Record<Locale, CampaignRecord> = {
  en: {
    "personal-ai": {
      eyebrow: "Personal AI savings",
      badge: "Free signup · create the key first",
      hero: {
        title: "Cut personal AI API costs by 40%",
        accent: "with one OpenAI-compatible key",
        description:
          "For individual developers: connect Codex and Claude Code quickly, add AI capability to your own product, and use text, audio, video, and image models through official upstream channels.",
        highlight:
          "Registration is free. Create the key first; recharge later only when you are ready to run real usage.",
      },
      offer: {
        title: "Create the API key before you pay",
        body: "Use the signup flow to land on the API key page. When you are ready, recharge from $20 and get a $5 bonus to validate real usage.",
      },
      primaryCta: "Create a free API key",
      ctaNote: "After signup, you go straight to the API key page.",
      quickStart: {
        title: "Use your existing OpenAI SDK",
        body: "Change only the base_url and API key, then run your current script against Flatkey.",
        agentAction: "Set up Codex / Claude Code",
        sdkAction: "Copy SDK examples",
      },
      heroPanel: {
        kicker: "Direct test path",
        title: "Free signup -> create key -> connect test",
        rows: [
          { label: "Token price", value: "-40%", body: "More prompts, coding runs, and image tests from the same budget." },
          { label: "Start", value: "Free key", body: "Create the key first; recharge later when you are ready." },
          { label: "Access", value: "1 key", body: "Codex, Claude Code, GPT, Claude, Gemini, text, audio, video, and image models." },
        ],
        footnote: "Balance is prepaid and built for usage over time, not a fixed monthly plan.",
      },
      proof: {
        title: "Official model-token quality you can trust",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported model is served through its official upstream tokens, giving you authentic model quality from trusted sources.",
      },
      evidence: [
        { title: "40% cheaper tokens", body: "Stretch the same personal budget across more prompts, coding runs, and image tests." },
        { title: "Built for individual developers", body: "Use one key for coding agents and for the AI features inside your own software." },
        { title: "Official upstream channels", body: "Access text, audio, video, and image models through official provider routes for safer, lower-friction usage." },
      ],
      steps: [
        { title: "Create your key", body: "Sign up for free and land directly on the API key page." },
        { title: "Connect a test", body: "Change base_url in your existing OpenAI SDK setup." },
        { title: "Use agents or product AI", body: "Point Codex, Claude Code, apps, scripts, or your own product backend at Flatkey." },
      ],
      faqs: [
        { question: "Does balance expire?", answer: "Flatkey prepaid balance is designed for usage over time, not a monthly plan you lose if unused." },
        { question: "Is this only for chat?", answer: "No. You can use it for coding agents and product AI features across text, audio, video, and image workloads." },
        { question: "Do I need to pay before signup?", answer: "No. Signup and API key creation are free. Recharge later when you are ready to test real usage." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "Create your API key in 3 steps",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Create the API key first",
      finalBody: "Register for free, connect one real script, then decide after seeing cost and quality yourself.",
    },
    "cto-ai-savings": {
      eyebrow: "CTO AI savings",
      badge: "Cut AI spend by 40% today",
      hero: {
        title: "Reduce AI API and engineering AI cost by 40%",
        accent: "without changing your stack",
        description:
          "Flatkey gives your team one compatible gateway for product AI, developer agents, logs, prepaid balance, and fewer quota bottlenecks.",
      },
      offer: {
        title: "Validate with $20 + $5 bonus",
        body: "Run a real workload first. If routing, quality, and logs meet your bar, contact us for higher-volume team pricing.",
      },
      primaryCta: "Create a test key",
      ctaNote: "After signup, you go straight to the API key page.",
      heroPanel: {
        kicker: "Low-risk pilot",
        title: "Test one real workload before scaling team usage",
        rows: [
          { label: "Cost target", value: "-40%", body: "Cut API and engineering-agent spend without changing your stack." },
          { label: "Pilot budget", value: "$20 + $5", body: "Run latency, quality, log, and cost checks on real traffic." },
          { label: "Team path", value: "1 gateway", body: "Centralize keys, prepaid balance, and quota relief for product and engineering." },
        ],
        footnote: "After validation, move to larger prepaid packages or contact us for team pricing.",
      },
      proof: {
        title: "Trusted official-token quality for teams",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported model is served through its official upstream tokens, giving teams trusted sources and authentic model quality.",
      },
      evidence: [
        { title: "Product AI gateway", body: "Add AI capability to your system while keeping one compatible key and usage trail." },
        { title: "Cheaper developer agents", body: "Route Codex, Claude Code, and engineering loops through lower-cost metered usage." },
        { title: "Quota relief", body: "Reduce friction when official accounts hit rate, quota, or operational limits." },
      ],
      steps: [
        { title: "Create a team test key", body: "Use the signup flow to create a key for controlled validation." },
        { title: "Run one real workload", body: "Compare latency, quality, logs, and cost against current routing." },
        { title: "Scale after validation", body: "Move to larger prepaid packages or contact us for a team plan." },
      ],
      faqs: [
        { question: "Do we need code changes?", answer: "Most OpenAI-compatible integrations only need base URL and key changes." },
        { question: "Can we validate before committing?", answer: "Yes. Start with $20 plus $5 bonus and measure a real workload." },
        { question: "Is this suitable for multiple engineers?", answer: "Yes. Flatkey centralizes keys, balances, and logs for shared usage control." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "Create your API key in 3 steps",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Prove the 40% saving on your own workload",
      finalBody: "Start with a small key, test routing quality, then decide whether to scale the team package.",
    },
    "image-buddy": {
      eyebrow: "Image Buddy for operators",
      badge: "Lower-cost image generation workflow",
      hero: {
        title: "Generate campaign images faster with 40% cheaper AI usage",
        accent: "and reusable prompt workflows",
        description:
          "Flatkey unlocks lower-cost image generation, while Image Buddy gives operators ready workflows instead of repeated prompt hunting.",
      },
      offer: {
        title: "Create a key, then install Image Buddy",
        body: "Use Flatkey for generation capacity and lower cost. Use Image Buddy templates for product shots, ads, marketplace images, and campaign visuals.",
      },
      primaryCta: "Create a key first",
      ctaNote: "After signup, you go straight to the API key page.",
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases.en,
      proof: {
        title: "Reliable token quality for repeat creative work",
        body: "Flatkey has received OpenAI recognition for passing 10 billion tokens. Every supported image and text model is served through its official upstream tokens, giving operators trusted sources for repeat creative work.",
      },
      evidence: [
        { title: "Less prompt hunting", body: "Start from reusable Image Buddy workflows instead of rewriting image prompts every time." },
        { title: "Fewer quota stops", body: "Use Flatkey routing to reduce friction from common generation limits." },
        { title: "Campaign-ready assets", body: "Create product visuals, ad stills, marketplace images, and social creatives faster." },
      ],
      steps: [
        { title: "Create a Flatkey key", body: "Sign up and create the key that Image Buddy will use." },
        { title: "Install Image Buddy", body: "Use the GitHub guide to add the workflow to your environment." },
        { title: "Generate with templates", body: "Pick a workflow, add product context, and create usable images." },
      ],
      faqs: [
        { question: "Is Image Buddy only for developers?", answer: "No. It is designed to package image prompts into repeatable workflows for operators and teams." },
        { question: "Why create the key first?", answer: "The key unlocks Flatkey routing and generation capacity before Image Buddy sends requests." },
        { question: "Can I use it for ecommerce?", answer: "Yes. It supports product shots, marketplace cards, ads, and other recurring creative needs." },
      ],
      sectionLabels: {
        startEyebrow: "Start path",
        startTitle: "Create your API key in 3 steps",
        faqEyebrow: "Questions",
        faqTitle: "Short answers before you test",
      },
      finalTitle: "Create the key before your next image batch",
      finalBody: "Set up Flatkey first, then use Image Buddy to make repeat creative work faster and cheaper.",
    },
  },
  zh: {
    "personal-ai": {
      eyebrow: "个人 AI 省钱方案",
      badge: "免费注册 · 先创建 API key",
      hero: {
        title: "个人开发者的 AI API 成本降低 40%",
        accent: "一个 OpenAI 兼容 key 接入多模型",
        description: "如果你是个人开发者，可以快速接入 Codex、Claude Code，也能给自己的软件系统增加 AI 能力；文本、语音、视频、图片模型都可通过官方上游渠道使用。",
        highlight:
          "注册免费，先发 key；充值可以稍后进行。准备跑真实用量时，再从 $20 充值并领取 $5 奖励。",
      },
      offer: {
        title: "先创建 API key，再决定是否充值",
        body: "注册后直接进入 API key 页面。准备验证真实工作流时，可从 $20 充值并获得 $5 奖励额度。",
      },
      primaryCta: "免费创建 API key",
      ctaNote: "注册后会直接进入 API key 页面。",
      quickStart: {
        title: "沿用现有 OpenAI SDK",
        body: "只改 base_url 和 API key，即可把现有脚本切到 Flatkey 测试。",
        agentAction: "配置 Codex / Claude Code",
        sdkAction: "复制 SDK 示例",
      },
      heroPanel: {
        kicker: "最短测试链路",
        title: "免费注册 -> 创建 key -> 接入测试",
        rows: [
          { label: "Token 成本", value: "-40%", body: "同样预算跑更多提示词、编程任务和图片测试。" },
          { label: "开始方式", value: "免费 key", body: "先创建 key，准备跑真实用量时再充值。" },
          { label: "接入范围", value: "1 key", body: "Codex、Claude Code、GPT、Claude、Gemini、文本、语音、视频与图片模型。" },
        ],
        footnote: "余额按预付使用，不是每月不用就浪费的固定套餐。",
      },
      proof: {
        title: "模型 token 质量可靠，可放心使用",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的模型都走对应官方上游 token，来源可信赖，模型质量保真、稳定、放心。",
      },
      evidence: [
        { title: "token 便宜 40%", body: "同样预算可以跑更多提示词、编程任务和图片测试。" },
        { title: "更适合个人开发者", body: "一个 key 同时支持 coding agent，也能支持你自己产品里的 AI 功能。" },
        { title: "官方上游渠道", body: "文本、语音、视频、图片模型通过官方供应商路径使用，更安全、更省心。" },
      ],
      steps: [
        { title: "创建你的 key", body: "免费注册后直接进入 API key 页面。" },
        { title: "接入一次测试", body: "把现有 OpenAI SDK 的 base_url 改到 Flatkey。" },
        { title: "接入 Agent 或产品 AI", body: "把 Codex、Claude Code、脚本、App 或你的产品后端指向 Flatkey。" },
      ],
      faqs: [
        { question: "余额会过期吗？", answer: "Flatkey 预付余额面向长期使用，不是不用就浪费的月费套餐。" },
        { question: "只能用来聊天吗？", answer: "不是。它既能接 Codex、Claude Code，也能支撑你产品里的文本、语音、视频和图片 AI 能力。" },
        { question: "注册前必须付费吗？", answer: "不需要。注册和创建 API key 都免费，准备验证真实用量时再充值。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "3 步创建可用 API key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "先免费创建 API key",
      finalBody: "注册、拿 key、接入一个真实脚本；看到成本和质量后，再决定是否充值使用。",
    },
    "cto-ai-savings": {
      eyebrow: "CTO AI 成本优化",
      badge: "今天开始省 40% AI 成本",
      hero: {
        title: "让公司 AI API 与研发 AI 成本降低 40%",
        accent: "无需重做技术栈",
        description: "Flatkey 为团队提供兼容网关，统一产品 AI、开发者 Agent、日志、预付余额，并减少 quota 卡点。",
      },
      offer: {
        title: "用 $20 + $5 奖励先验证",
        body: "先跑一段真实工作负载。确认路由、质量与日志满足要求后，再联系升级大额团队套餐。",
      },
      primaryCta: "创建测试 key",
      ctaNote: "注册后会直接进入 API key 页面。",
      heroPanel: {
        kicker: "低风险试点",
        title: "先跑一个真实 workload，再决定团队扩容",
        rows: [
          { label: "成本目标", value: "-40%", body: "不重做技术栈，先降低 API 与研发 Agent 用量成本。" },
          { label: "试点预算", value: "$20 + $5", body: "用真实流量验证延迟、质量、日志和成本。" },
          { label: "团队路径", value: "1 gateway", body: "统一 key、预付余额、用量日志，并缓解 quota 卡点。" },
        ],
        footnote: "验证通过后再升级大额预付包，或联系配置团队方案。",
      },
      proof: {
        title: "团队可依赖的官方 token 质量",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的模型都走对应官方上游 token，团队可依赖可信来源和保真的模型质量。",
      },
      evidence: [
        { title: "产品 AI 网关", body: "为系统提供 AI 能力，同时保留一个兼容 key 和完整用量轨迹。" },
        { title: "开发者 Agent 更省", body: "把 Codex、Claude Code 与研发循环转到更低成本的计费路径。" },
        { title: "减少 quota 限制", body: "当官方账号遇到速率、额度或运维限制时，降低阻塞概率。" },
      ],
      steps: [
        { title: "创建团队测试 key", body: "通过注册流程创建一个可控验证 key。" },
        { title: "跑一个真实 workload", body: "对比当前路由的延迟、质量、日志和成本。" },
        { title: "验证后再扩容", body: "确认结果后使用更大预付包，或联系我们配置团队方案。" },
      ],
      faqs: [
        { question: "需要改很多代码吗？", answer: "多数 OpenAI 兼容集成只需要替换 base URL 和 key。" },
        { question: "能先验证再采购吗？", answer: "可以。先用 $20 加 $5 奖励跑真实工作负载。" },
        { question: "适合多名工程师使用吗？", answer: "适合。Flatkey 可集中管理 key、余额和日志，便于团队控制。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "3 步创建可用 API key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "用自己的 workload 证明 40% 节省",
      finalBody: "先建一个小额测试 key，验证路由质量，再决定是否扩大团队使用。",
    },
    "image-buddy": {
      eyebrow: "运营生图工作流",
      badge: "更低成本的图片生成",
      hero: {
        title: "用便宜 40% 的 AI 用量更快生成活动图片",
        accent: "并复用成熟提示词流程",
        description: "Flatkey 降低生图成本、缓解额度限制，Image Buddy 帮运营直接使用可复用工作流，不再反复找提示词。",
      },
      offer: {
        title: "先创建 key，再安装 Image Buddy",
        body: "用 Flatkey 提供生成能力与更低成本，再用 Image Buddy 模板生成产品图、广告图、电商图和活动素材。",
      },
      primaryCta: "先创建 key",
      ctaNote: "注册后会直接进入 API key 页面。",
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases.zh,
      proof: {
        title: "长期生图也稳定的 token 质量",
        body: "Flatkey 已获得 OpenAI 100 亿 token 用量纪念认可。所有支持的图片与文本模型都走对应官方上游 token，为长期生图提供可信赖的质量基础。",
      },
      evidence: [
        { title: "少找提示词", body: "从 Image Buddy 可复用流程开始，不用每次重写图片提示词。" },
        { title: "减少额度卡顿", body: "通过 Flatkey 路由降低常见生成限制带来的中断。" },
        { title: "更快做活动素材", body: "更快生成产品图、广告封面、电商图片和社媒创意。" },
      ],
      steps: [
        { title: "创建 Flatkey key", body: "注册并创建 Image Buddy 调用所需的 key。" },
        { title: "安装 Image Buddy", body: "按照 GitHub 文档把工作流加入你的环境。" },
        { title: "用模板生成", body: "选择工作流，补充产品信息，生成可用图片。" },
      ],
      faqs: [
        { question: "Image Buddy 只给开发者用吗？", answer: "不是。它把图片提示词封装成可重复流程，适合运营和团队。" },
        { question: "为什么先创建 key？", answer: "key 用来开启 Flatkey 路由和生成能力，Image Buddy 会用它发送请求。" },
        { question: "能做电商图吗？", answer: "可以。支持产品图、详情卡、广告图等高频素材需求。" },
      ],
      sectionLabels: {
        startEyebrow: "开始路径",
        startTitle: "3 步创建可用 API key",
        faqEyebrow: "常见问题",
        faqTitle: "测试前先看这几条",
      },
      finalTitle: "下次批量作图前先创建 key",
      finalBody: "先接好 Flatkey，再用 Image Buddy 更快、更便宜地处理重复创意工作。",
    },
  },
  get es() {
    return createWesternCopy("es");
  },
  get fr() {
    return createWesternCopy("fr");
  },
  get pt() {
    return createWesternCopy("pt");
  },
  get ru() {
    return createWesternCopy("ru");
  },
  get ja() {
    return createWesternCopy("ja");
  },
  get vi() {
    return createWesternCopy("vi");
  },
  get de() {
    return createWesternCopy("de");
  },
};

function createWesternCopy(locale: Exclude<Locale, "en" | "zh">): CampaignRecord {
  const t = localizedTemplates[locale];
  const personalStartValue = locale === "ja" ? "無料APIキー" : "Free key";
  const personalAccessValue = locale === "ja" ? "1つのAPIキーで一括利用" : "1 key";
  return {
    "personal-ai": {
      eyebrow: t.personalEyebrow,
      badge: t.personalBadge,
      hero: {
        title: t.personalTitle,
        accent: t.personalAccent,
        description: t.personalDescription,
        highlight: t.personalHighlight,
      },
      offer: { title: t.personalOfferTitle, body: t.personalOfferBody },
      primaryCta: t.createKey,
      ctaNote: t.ctaNote,
      quickStart: {
        title: t.personalQuickStartTitle,
        body: t.personalQuickStartBody,
        agentAction: t.personalAgentAction,
        sdkAction: t.personalSdkAction,
      },
      heroPanel: {
        kicker: t.personalPanelKicker,
        title: t.personalOfferTitle,
        rows: [
          { label: t.evidenceCheapTitle, value: "-40%", body: t.personalCheapBody },
          { label: t.stepRechargeTitle, value: personalStartValue, body: t.personalStepRechargeBody },
          { label: t.evidenceModelsTitle, value: personalAccessValue, body: t.personalModelsBody },
        ],
        footnote: t.personalOfferBody,
      },
      proof: { title: t.proofTitle, body: t.personalProofBody },
      evidence: [
        { title: t.evidenceCheapTitle, body: t.personalCheapBody },
        { title: t.evidenceModelsTitle, body: t.personalModelsBody },
        { title: t.evidenceAgentsTitle, body: t.personalAgentsBody },
      ],
      steps: [
        { title: t.stepKeyTitle, body: t.personalStepKeyBody },
        { title: t.stepRechargeTitle, body: t.personalStepRechargeBody },
        { title: t.stepUseTitle, body: t.personalStepUseBody },
      ],
      faqs: [
        { question: t.personalFaq1Q, answer: t.personalFaq1A },
        { question: t.personalFaq2Q, answer: t.personalFaq2A },
        { question: t.personalFaq3Q, answer: t.personalFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.personalFinalTitle,
      finalBody: t.personalFinalBody,
    },
    "cto-ai-savings": {
      eyebrow: t.ctoEyebrow,
      badge: t.ctoBadge,
      hero: {
        title: t.ctoTitle,
        accent: t.ctoAccent,
        description: t.ctoDescription,
      },
      offer: { title: t.ctoOfferTitle, body: t.ctoOfferBody },
      primaryCta: t.createTestKey,
      ctaNote: t.ctaNote,
      heroPanel: {
        kicker: t.ctoBadge,
        title: t.ctoOfferTitle,
        rows: [
          { label: t.ctoEvidenceAgentsTitle, value: "-40%", body: t.ctoEvidenceAgentsBody },
          { label: t.ctoStepWorkloadTitle, value: "$20 + $5", body: t.ctoStepWorkloadBody },
          { label: t.ctoEvidenceQuotaTitle, value: "1 gateway", body: t.ctoEvidenceQuotaBody },
        ],
        footnote: t.ctoFinalBody,
      },
      proof: { title: t.proofTitle, body: t.ctoProofBody },
      evidence: [
        { title: t.ctoEvidenceGatewayTitle, body: t.ctoEvidenceGatewayBody },
        { title: t.ctoEvidenceAgentsTitle, body: t.ctoEvidenceAgentsBody },
        { title: t.ctoEvidenceQuotaTitle, body: t.ctoEvidenceQuotaBody },
      ],
      steps: [
        { title: t.ctoStepKeyTitle, body: t.ctoStepKeyBody },
        { title: t.ctoStepWorkloadTitle, body: t.ctoStepWorkloadBody },
        { title: t.ctoStepScaleTitle, body: t.ctoStepScaleBody },
      ],
      faqs: [
        { question: t.ctoFaq1Q, answer: t.ctoFaq1A },
        { question: t.ctoFaq2Q, answer: t.ctoFaq2A },
        { question: t.ctoFaq3Q, answer: t.ctoFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.ctoFinalTitle,
      finalBody: t.ctoFinalBody,
    },
    "image-buddy": {
      eyebrow: t.imageEyebrow,
      badge: t.imageBadge,
      hero: {
        title: t.imageTitle,
        accent: t.imageAccent,
        description: t.imageDescription,
      },
      offer: { title: t.imageOfferTitle, body: t.imageOfferBody },
      primaryCta: t.createKeyFirst,
      ctaNote: t.ctaNote,
      secondaryCta: imageBuddyLink,
      showcase: imageBuddyShowcases[locale],
      proof: { title: t.imageProofTitle, body: t.imageProofBody },
      evidence: [
        { title: t.imageEvidencePromptTitle, body: t.imageEvidencePromptBody },
        { title: t.imageEvidenceQuotaTitle, body: t.imageEvidenceQuotaBody },
        { title: t.imageEvidenceAssetTitle, body: t.imageEvidenceAssetBody },
      ],
      steps: [
        { title: t.imageStepKeyTitle, body: t.imageStepKeyBody },
        { title: t.imageStepInstallTitle, body: t.imageStepInstallBody },
        { title: t.imageStepGenerateTitle, body: t.imageStepGenerateBody },
      ],
      faqs: [
        { question: t.imageFaq1Q, answer: t.imageFaq1A },
        { question: t.imageFaq2Q, answer: t.imageFaq2A },
        { question: t.imageFaq3Q, answer: t.imageFaq3A },
      ],
      sectionLabels: t.sectionLabels,
      finalTitle: t.imageFinalTitle,
      finalBody: t.imageFinalBody,
    },
  };
}

const localizedTemplates = {
  es: {
    sectionLabels: {
      startEyebrow: "Ruta de inicio",
      startTitle: "Crea tu API key en 3 pasos",
      faqEyebrow: "Preguntas",
      faqTitle: "Respuestas breves antes de probar",
    },
    ctaNote: "Después del registro, irás directo a la página de API keys.",
    personalEyebrow: "Ahorro de IA personal",
    personalBadge: "Registro gratis · crea la key primero",
    personalPanelKicker: "Siguiente paso",
    personalTitle: "Reduce 40% el coste de API de IA personal",
    personalAccent: "con una key compatible con OpenAI",
    personalDescription: "Para desarrolladores individuales: conecta Codex y Claude Code rápido, añade IA a tu propio producto y usa texto, audio, vídeo e imagen por canales upstream oficiales.",
    personalHighlight: "El registro es gratis. Crea la key primero; recarga después solo cuando quieras ejecutar uso real.",
    personalOfferTitle: "Crea la API key antes de pagar",
    personalOfferBody: "El registro te lleva a la página de API keys. Cuando estés listo, recarga desde $20 y recibe $5 de bono para validar uso real.",
    createKey: "Crear API key gratis",
    personalQuickStartTitle: "Usa tu SDK de OpenAI actual",
    personalQuickStartBody: "Cambia solo base_url y API key, luego ejecuta tu script actual contra Flatkey.",
    personalAgentAction: "Configurar Codex / Claude Code",
    personalSdkAction: "Copiar ejemplos SDK",
    proofTitle: "Calidad confiable con tokens oficiales",
    personalProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo soportado usa sus tokens oficiales upstream, con fuentes confiables y calidad auténtica.",
    evidenceCheapTitle: "Tokens 40% más baratos",
    personalCheapBody: "El mismo presupuesto rinde más prompts, ejecuciones de código y pruebas de imagen.",
    evidenceModelsTitle: "Muchos modelos conocidos",
    personalModelsBody: "Usa una key para coding agents y para las funciones de IA dentro de tu propio software.",
    evidenceAgentsTitle: "Listo para Codex y Claude Code",
    personalAgentsBody: "Accede a modelos de texto, audio, vídeo e imagen por rutas oficiales de proveedores, con menos fricción.",
    stepKeyTitle: "Crea tu key",
    personalStepKeyBody: "Regístrate y llega directamente a la página de API keys.",
    stepRechargeTitle: "Conecta una prueba",
    personalStepRechargeBody: "Crea la key primero; recarga después cuando estés listo.",
    stepUseTitle: "Usa cualquier modelo soportado",
    personalStepUseBody: "Apunta Codex, Claude Code, apps, scripts o tu backend de producto a Flatkey.",
    personalFaq1Q: "¿El saldo caduca?",
    personalFaq1A: "El saldo prepago de Flatkey está pensado para usarse con el tiempo, no como una mensualidad que pierdes.",
    personalFaq2Q: "¿Solo sirve para chat?",
    personalFaq2A: "No. Sirve para coding agents y para funciones de IA de producto en texto, audio, vídeo e imagen.",
    personalFaq3Q: "¿Debo pagar antes de registrarme?",
    personalFaq3A: "No. El registro y la API key son gratis. Recarga después, cuando vayas a probar uso real.",
    personalFinalTitle: "Crea primero la API key",
    personalFinalBody: "Regístrate gratis, conecta un script real y decide tras ver coste y calidad.",
    ctoEyebrow: "Ahorro de IA para CTO",
    ctoBadge: "Reduce 40% el gasto de IA hoy",
    ctoTitle: "Reduce 40% el coste de APIs de IA e IA para ingeniería",
    ctoAccent: "sin cambiar tu stack",
    ctoDescription: "Flatkey da a tu equipo una puerta compatible para IA de producto, agentes de desarrollo, logs, saldo prepago y menos bloqueos de cuota.",
    ctoOfferTitle: "Valida con $20 + $5 de bono",
    ctoOfferBody: "Ejecuta primero una carga real. Si routing, calidad y logs cumplen, contáctanos para precios de equipo de mayor volumen.",
    createTestKey: "Crear key de prueba",
    ctoProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo soportado usa sus tokens oficiales upstream, con fuentes confiables y calidad auténtica para equipos.",
    ctoEvidenceGatewayTitle: "Gateway de IA de producto",
    ctoEvidenceGatewayBody: "Añade IA a tu sistema con una key compatible y una trazabilidad clara de uso.",
    ctoEvidenceAgentsTitle: "Agentes de desarrollo más baratos",
    ctoEvidenceAgentsBody: "Ruta Codex, Claude Code y ciclos de ingeniería por uso medido de menor coste.",
    ctoEvidenceQuotaTitle: "Menos bloqueo por cuotas",
    ctoEvidenceQuotaBody: "Reduce fricción cuando cuentas oficiales alcanzan límites de rate, cuota u operación.",
    ctoStepKeyTitle: "Crea una key de prueba",
    ctoStepKeyBody: "Usa el registro para crear una key controlada de validación.",
    ctoStepWorkloadTitle: "Ejecuta una carga real",
    ctoStepWorkloadBody: "Compara latencia, calidad, logs y coste frente a tu routing actual.",
    ctoStepScaleTitle: "Escala después de validar",
    ctoStepScaleBody: "Pasa a paquetes prepago mayores o habla con nosotros sobre un plan de equipo.",
    ctoFaq1Q: "¿Necesitamos cambiar mucho código?",
    ctoFaq1A: "La mayoría de integraciones compatibles con OpenAI solo cambian base URL y key.",
    ctoFaq2Q: "¿Podemos validar antes de comprometernos?",
    ctoFaq2A: "Sí. Empieza con $20 más $5 de bono y mide una carga real.",
    ctoFaq3Q: "¿Sirve para varios ingenieros?",
    ctoFaq3A: "Sí. Flatkey centraliza keys, saldos y logs para controlar uso compartido.",
    ctoFinalTitle: "Demuestra el 40% de ahorro en tu propia carga",
    ctoFinalBody: "Empieza con una key pequeña, valida calidad de routing y decide si escalar.",
    imageEyebrow: "Image Buddy para operaciones",
    imageBadge: "Flujo de imágenes con menor coste",
    imageTitle: "Genera imágenes de campaña más rápido con IA 40% más barata",
    imageAccent: "y flujos reutilizables",
    imageDescription: "Flatkey reduce el coste de generación de imágenes e Image Buddy da flujos listos para no buscar prompts cada vez.",
    imageOfferTitle: "Crea una key y luego instala Image Buddy",
    imageOfferBody: "Usa Flatkey para capacidad y menor coste. Usa plantillas de Image Buddy para producto, anuncios, marketplace y campañas.",
    createKeyFirst: "Crear key primero",
    imageProofTitle: "Calidad estable para creación repetida",
    imageProofBody: "Flatkey recibió reconocimiento de OpenAI por superar 10 mil millones de tokens. Cada modelo de imagen y texto soportado usa sus tokens oficiales upstream, una base confiable para creación repetida.",
    imageEvidencePromptTitle: "Menos búsqueda de prompts",
    imageEvidencePromptBody: "Parte de flujos reutilizables de Image Buddy en vez de reescribir prompts de imagen.",
    imageEvidenceQuotaTitle: "Menos paradas por cuota",
    imageEvidenceQuotaBody: "Usa routing de Flatkey para reducir fricción de límites frecuentes de generación.",
    imageEvidenceAssetTitle: "Assets listos para campañas",
    imageEvidenceAssetBody: "Crea producto, anuncios, marketplace y social creatives más rápido.",
    imageStepKeyTitle: "Crea una key de Flatkey",
    imageStepKeyBody: "Regístrate y crea la key que usará Image Buddy.",
    imageStepInstallTitle: "Instala Image Buddy",
    imageStepInstallBody: "Sigue la guía de GitHub para añadir el flujo a tu entorno.",
    imageStepGenerateTitle: "Genera con plantillas",
    imageStepGenerateBody: "Elige un flujo, añade contexto del producto y crea imágenes útiles.",
    imageFaq1Q: "¿Image Buddy es solo para desarrolladores?",
    imageFaq1A: "No. Empaqueta prompts de imagen en flujos repetibles para operaciones y equipos.",
    imageFaq2Q: "¿Por qué crear la key primero?",
    imageFaq2A: "La key activa routing y capacidad de generación antes de que Image Buddy envíe solicitudes.",
    imageFaq3Q: "¿Sirve para ecommerce?",
    imageFaq3A: "Sí. Soporta producto, tarjetas de marketplace, anuncios y necesidades creativas recurrentes.",
    imageFinalTitle: "Crea la key antes del próximo lote de imágenes",
    imageFinalBody: "Configura Flatkey primero y usa Image Buddy para trabajar más rápido y barato.",
  },
  fr: {
    sectionLabels: {
      startEyebrow: "Chemin de départ",
      startTitle: "Créez votre clé API en 3 étapes",
      faqEyebrow: "Questions",
      faqTitle: "Réponses courtes avant de tester",
    },
    ctaNote: "Après l'inscription, vous arrivez directement sur la page des clés API.",
    personalEyebrow: "Économies IA personnelles",
    personalBadge: "Inscription gratuite · créez la clé d'abord",
    personalPanelKicker: "Prochaine étape",
    personalTitle: "Réduisez de 40% le coût API IA personnel",
    personalAccent: "avec une clé compatible OpenAI",
    personalDescription: "Pour développeurs indépendants : connectez Codex et Claude Code vite, ajoutez l'IA à votre produit et utilisez texte, audio, vidéo et image via des canaux upstream officiels.",
    personalHighlight: "L'inscription est gratuite. Créez la clé d'abord ; rechargez ensuite seulement lorsque vous êtes prêt à lancer un usage réel.",
    personalOfferTitle: "Créez la clé API avant de payer",
    personalOfferBody: "L'inscription vous amène à la page des clés API. Quand vous êtes prêt, rechargez dès $20 et recevez $5 de bonus pour valider un usage réel.",
    createKey: "Créer une clé API gratuite",
    personalQuickStartTitle: "Gardez votre SDK OpenAI actuel",
    personalQuickStartBody: "Changez seulement base_url et la clé API, puis exécutez votre script actuel avec Flatkey.",
    personalAgentAction: "Configurer Codex / Claude Code",
    personalSdkAction: "Copier les exemples SDK",
    proofTitle: "Qualité fiable via tokens officiels",
    personalProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle supporté utilise ses tokens upstream officiels, avec des sources fiables et une qualité authentique.",
    evidenceCheapTitle: "Tokens 40% moins chers",
    personalCheapBody: "Le même budget couvre plus de prompts, de runs de code et de tests image.",
    evidenceModelsTitle: "Nombreux modèles connus",
    personalModelsBody: "Utilisez une clé pour les coding agents et pour les fonctions IA de votre propre logiciel.",
    evidenceAgentsTitle: "Prêt pour Codex et Claude Code",
    personalAgentsBody: "Accédez aux modèles texte, audio, vidéo et image via des routes fournisseurs officielles, avec moins de friction.",
    stepKeyTitle: "Créez votre clé",
    personalStepKeyBody: "Inscrivez-vous et arrivez directement sur la page des clés API.",
    stepRechargeTitle: "Connectez un test",
    personalStepRechargeBody: "Créez la clé d'abord ; rechargez ensuite quand vous êtes prêt.",
    stepUseTitle: "Utilisez tout modèle supporté",
    personalStepUseBody: "Pointez Codex, Claude Code, apps, scripts ou votre backend produit vers Flatkey.",
    personalFaq1Q: "Le solde expire-t-il ?",
    personalFaq1A: "Le solde prépayé Flatkey est fait pour être utilisé dans le temps, pas perdu comme un forfait mensuel.",
    personalFaq2Q: "Est-ce seulement pour le chat ?",
    personalFaq2A: "Non. Cela sert aux coding agents et aux fonctions IA produit en texte, audio, vidéo et image.",
    personalFaq3Q: "Faut-il payer avant l'inscription ?",
    personalFaq3A: "Non. L'inscription et la création de clé API sont gratuites. Rechargez ensuite quand vous testez un usage réel.",
    personalFinalTitle: "Créez d'abord la clé API",
    personalFinalBody: "Inscrivez-vous gratuitement, connectez un vrai script, puis décidez avec coût et qualité visibles.",
    ctoEyebrow: "Économies IA pour CTO",
    ctoBadge: "Réduisez 40% du coût IA aujourd'hui",
    ctoTitle: "Réduisez de 40% le coût API IA et l'IA d'ingénierie",
    ctoAccent: "sans changer votre stack",
    ctoDescription: "Flatkey donne à votre équipe une gateway compatible pour IA produit, agents développeur, logs, solde prépayé et moins de blocages quota.",
    ctoOfferTitle: "Validez avec $20 + $5 de bonus",
    ctoOfferBody: "Lancez d'abord une charge réelle. Si routing, qualité et logs conviennent, contactez-nous pour un prix équipe plus élevé.",
    createTestKey: "Créer une clé de test",
    ctoProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle supporté utilise ses tokens upstream officiels, avec des sources fiables et une qualité authentique pour les équipes.",
    ctoEvidenceGatewayTitle: "Gateway IA produit",
    ctoEvidenceGatewayBody: "Ajoutez l'IA à votre système avec une clé compatible et une trace d'usage claire.",
    ctoEvidenceAgentsTitle: "Agents développeur moins chers",
    ctoEvidenceAgentsBody: "Routez Codex, Claude Code et boucles d'ingénierie vers un usage mesuré moins coûteux.",
    ctoEvidenceQuotaTitle: "Moins de blocage quota",
    ctoEvidenceQuotaBody: "Réduisez la friction quand les comptes officiels touchent rate limit, quota ou limites opérationnelles.",
    ctoStepKeyTitle: "Créez une clé de test",
    ctoStepKeyBody: "Utilisez l'inscription pour créer une clé de validation contrôlée.",
    ctoStepWorkloadTitle: "Lancez une charge réelle",
    ctoStepWorkloadBody: "Comparez latence, qualité, logs et coût avec votre routing actuel.",
    ctoStepScaleTitle: "Scale après validation",
    ctoStepScaleBody: "Passez à des packs prépayés plus grands ou demandez un plan équipe.",
    ctoFaq1Q: "Faut-il beaucoup changer le code ?",
    ctoFaq1A: "La plupart des intégrations compatibles OpenAI changent seulement base URL et clé.",
    ctoFaq2Q: "Peut-on valider avant engagement ?",
    ctoFaq2A: "Oui. Commencez avec $20 plus $5 de bonus et mesurez une charge réelle.",
    ctoFaq3Q: "Est-ce adapté à plusieurs ingénieurs ?",
    ctoFaq3A: "Oui. Flatkey centralise clés, soldes et logs pour contrôler l'usage partagé.",
    ctoFinalTitle: "Prouvez les 40% d'économie sur votre charge",
    ctoFinalBody: "Commencez avec une petite clé, validez la qualité, puis décidez de scaler.",
    imageEyebrow: "Image Buddy pour opérations",
    imageBadge: "Workflow image à coût réduit",
    imageTitle: "Générez des images de campagne plus vite avec une IA 40% moins chère",
    imageAccent: "et des workflows réutilisables",
    imageDescription: "Flatkey réduit le coût de génération d'images, et Image Buddy donne des workflows prêts au lieu de chercher des prompts.",
    imageOfferTitle: "Créez une clé, puis installez Image Buddy",
    imageOfferBody: "Utilisez Flatkey pour capacité et coût réduit. Utilisez Image Buddy pour produit, ads, marketplace et campagnes.",
    createKeyFirst: "Créer la clé d'abord",
    imageProofTitle: "Qualité stable pour création répétée",
    imageProofBody: "Flatkey a reçu une reconnaissance OpenAI pour plus de 10 milliards de tokens. Chaque modèle image et texte supporté utilise ses tokens upstream officiels, base fiable pour la création répétée.",
    imageEvidencePromptTitle: "Moins de recherche de prompts",
    imageEvidencePromptBody: "Partez de workflows Image Buddy réutilisables au lieu de réécrire chaque prompt image.",
    imageEvidenceQuotaTitle: "Moins d'arrêts quota",
    imageEvidenceQuotaBody: "Utilisez le routing Flatkey pour réduire les limites fréquentes de génération.",
    imageEvidenceAssetTitle: "Assets prêts pour campagnes",
    imageEvidenceAssetBody: "Créez plus vite visuels produit, ads, marketplace et contenus sociaux.",
    imageStepKeyTitle: "Créez une clé Flatkey",
    imageStepKeyBody: "Inscrivez-vous et créez la clé utilisée par Image Buddy.",
    imageStepInstallTitle: "Installez Image Buddy",
    imageStepInstallBody: "Suivez le guide GitHub pour ajouter le workflow à votre environnement.",
    imageStepGenerateTitle: "Générez avec templates",
    imageStepGenerateBody: "Choisissez un workflow, ajoutez le contexte produit et créez des images utiles.",
    imageFaq1Q: "Image Buddy est-il réservé aux développeurs ?",
    imageFaq1A: "Non. Il transforme les prompts image en workflows répétables pour opérations et équipes.",
    imageFaq2Q: "Pourquoi créer la clé d'abord ?",
    imageFaq2A: "La clé active le routing Flatkey et la capacité de génération avant les requêtes Image Buddy.",
    imageFaq3Q: "Est-ce utile pour ecommerce ?",
    imageFaq3A: "Oui. Il couvre produit, marketplace, ads et besoins créatifs récurrents.",
    imageFinalTitle: "Créez la clé avant votre prochain lot d'images",
    imageFinalBody: "Configurez Flatkey puis utilisez Image Buddy pour travailler plus vite et moins cher.",
  },
  pt: {
    sectionLabels: {
      startEyebrow: "Caminho inicial",
      startTitle: "Crie sua API key em 3 passos",
      faqEyebrow: "Perguntas",
      faqTitle: "Respostas curtas antes de testar",
    },
    ctaNote: "Depois do cadastro, você vai direto para a página de API keys.",
    personalEyebrow: "Economia pessoal com IA",
    personalBadge: "Cadastro grátis · crie a key primeiro",
    personalPanelKicker: "Próximo passo",
    personalTitle: "Reduza 40% do custo de API de IA pessoal",
    personalAccent: "com uma key compatível com OpenAI",
    personalDescription: "Para desenvolvedores individuais: conecte Codex e Claude Code rápido, adicione IA ao seu produto e use texto, áudio, vídeo e imagem por canais upstream oficiais.",
    personalHighlight: "O cadastro é grátis. Crie a key primeiro; recarregue depois só quando estiver pronto para uso real.",
    personalOfferTitle: "Crie a API key antes de pagar",
    personalOfferBody: "O cadastro leva direto à página de API keys. Quando estiver pronto, recarregue a partir de $20 e receba $5 de bônus para validar uso real.",
    createKey: "Criar API key grátis",
    personalQuickStartTitle: "Use seu SDK OpenAI atual",
    personalQuickStartBody: "Troque apenas base_url e API key, depois rode seu script atual com Flatkey.",
    personalAgentAction: "Configurar Codex / Claude Code",
    personalSdkAction: "Copiar exemplos SDK",
    proofTitle: "Qualidade confiável com tokens oficiais",
    personalProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo suportado usa seus tokens upstream oficiais, com fontes confiáveis e qualidade autêntica.",
    evidenceCheapTitle: "Tokens 40% mais baratos",
    personalCheapBody: "O mesmo orçamento rende mais prompts, execuções de código e testes de imagem.",
    evidenceModelsTitle: "Muitos modelos conhecidos",
    personalModelsBody: "Use uma key para coding agents e para os recursos de IA dentro do seu próprio software.",
    evidenceAgentsTitle: "Pronto para Codex e Claude Code",
    personalAgentsBody: "Acesse modelos de texto, áudio, vídeo e imagem por rotas oficiais de provedores, com menos atrito.",
    stepKeyTitle: "Crie sua key",
    personalStepKeyBody: "Cadastre-se e vá direto para a página de API keys.",
    stepRechargeTitle: "Conecte um teste",
    personalStepRechargeBody: "Crie a key primeiro; recarregue depois quando estiver pronto.",
    stepUseTitle: "Use qualquer modelo suportado",
    personalStepUseBody: "Aponte Codex, Claude Code, apps, scripts ou o backend do seu produto para Flatkey.",
    personalFaq1Q: "O saldo expira?",
    personalFaq1A: "O saldo pré-pago Flatkey foi feito para uso ao longo do tempo, não como mensalidade perdida.",
    personalFaq2Q: "Serve só para chat?",
    personalFaq2A: "Não. Serve para coding agents e recursos de IA do produto em texto, áudio, vídeo e imagem.",
    personalFaq3Q: "Preciso pagar antes de me cadastrar?",
    personalFaq3A: "Não. Cadastro e criação de API key são grátis. Recarregue depois, quando for testar uso real.",
    personalFinalTitle: "Crie primeiro a API key",
    personalFinalBody: "Cadastre-se grátis, conecte um script real e decida vendo custo e qualidade.",
    ctoEyebrow: "Economia de IA para CTO",
    ctoBadge: "Reduza 40% do gasto de IA hoje",
    ctoTitle: "Reduza 40% do custo de API de IA e IA de engenharia",
    ctoAccent: "sem trocar seu stack",
    ctoDescription: "Flatkey dá à equipe um gateway compatível para IA de produto, agentes de desenvolvimento, logs, saldo pré-pago e menos bloqueios de quota.",
    ctoOfferTitle: "Valide com $20 + $5 de bônus",
    ctoOfferBody: "Rode primeiro uma carga real. Se routing, qualidade e logs passarem, fale conosco para preço de equipe em maior volume.",
    createTestKey: "Criar key de teste",
    ctoProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo suportado usa seus tokens upstream oficiais, com fontes confiáveis e qualidade autêntica para equipes.",
    ctoEvidenceGatewayTitle: "Gateway de IA para produto",
    ctoEvidenceGatewayBody: "Adicione IA ao sistema com uma key compatível e trilha clara de uso.",
    ctoEvidenceAgentsTitle: "Agentes de desenvolvimento mais baratos",
    ctoEvidenceAgentsBody: "Roteie Codex, Claude Code e ciclos de engenharia por uso medido mais barato.",
    ctoEvidenceQuotaTitle: "Menos bloqueio por quota",
    ctoEvidenceQuotaBody: "Reduza atrito quando contas oficiais atingem limites de rate, quota ou operação.",
    ctoStepKeyTitle: "Crie uma key de teste",
    ctoStepKeyBody: "Use o cadastro para criar uma key controlada de validação.",
    ctoStepWorkloadTitle: "Rode uma carga real",
    ctoStepWorkloadBody: "Compare latência, qualidade, logs e custo contra seu routing atual.",
    ctoStepScaleTitle: "Escale após validar",
    ctoStepScaleBody: "Passe para pacotes pré-pagos maiores ou peça um plano de equipe.",
    ctoFaq1Q: "Precisamos mudar muito código?",
    ctoFaq1A: "A maioria das integrações compatíveis com OpenAI só muda base URL e key.",
    ctoFaq2Q: "Podemos validar antes de compromisso?",
    ctoFaq2A: "Sim. Comece com $20 mais $5 de bônus e meça uma carga real.",
    ctoFaq3Q: "Serve para vários engenheiros?",
    ctoFaq3A: "Sim. Flatkey centraliza keys, saldos e logs para controlar uso compartilhado.",
    ctoFinalTitle: "Comprove 40% de economia na sua carga",
    ctoFinalBody: "Comece com uma key pequena, valide qualidade e decida se escala.",
    imageEyebrow: "Image Buddy para operações",
    imageBadge: "Fluxo de imagem com menor custo",
    imageTitle: "Gere imagens de campanha mais rápido com IA 40% mais barata",
    imageAccent: "e workflows reutilizáveis",
    imageDescription: "Flatkey reduz custo de geração de imagens, e Image Buddy traz workflows prontos em vez de procurar prompts sempre.",
    imageOfferTitle: "Crie uma key e depois instale Image Buddy",
    imageOfferBody: "Use Flatkey para capacidade e menor custo. Use templates Image Buddy para produto, anúncios, marketplace e campanhas.",
    createKeyFirst: "Criar key primeiro",
    imageProofTitle: "Qualidade estável para criação recorrente",
    imageProofBody: "Flatkey recebeu reconhecimento da OpenAI por passar 10 bilhões de tokens. Cada modelo de imagem e texto suportado usa seus tokens upstream oficiais, uma base confiável para criação recorrente.",
    imageEvidencePromptTitle: "Menos busca de prompts",
    imageEvidencePromptBody: "Comece com workflows reutilizáveis Image Buddy em vez de reescrever prompts de imagem.",
    imageEvidenceQuotaTitle: "Menos paradas por quota",
    imageEvidenceQuotaBody: "Use routing Flatkey para reduzir limites frequentes de geração.",
    imageEvidenceAssetTitle: "Assets prontos para campanha",
    imageEvidenceAssetBody: "Crie produto, anúncios, marketplace e criativos sociais mais rápido.",
    imageStepKeyTitle: "Crie uma key Flatkey",
    imageStepKeyBody: "Cadastre-se e crie a key que Image Buddy usará.",
    imageStepInstallTitle: "Instale Image Buddy",
    imageStepInstallBody: "Siga o guia GitHub para adicionar o workflow ao seu ambiente.",
    imageStepGenerateTitle: "Gere com templates",
    imageStepGenerateBody: "Escolha um workflow, adicione contexto do produto e crie imagens úteis.",
    imageFaq1Q: "Image Buddy é só para devs?",
    imageFaq1A: "Não. Ele empacota prompts de imagem em workflows repetíveis para operações e equipes.",
    imageFaq2Q: "Por que criar a key primeiro?",
    imageFaq2A: "A key ativa routing e capacidade de geração antes das requisições do Image Buddy.",
    imageFaq3Q: "Serve para ecommerce?",
    imageFaq3A: "Sim. Suporta produto, cards de marketplace, anúncios e criativos recorrentes.",
    imageFinalTitle: "Crie a key antes do próximo lote de imagens",
    imageFinalBody: "Configure Flatkey primeiro e use Image Buddy para trabalhar mais rápido e barato.",
  },
  ru: {
    sectionLabels: {
      startEyebrow: "Путь запуска",
      startTitle: "Создайте API key за 3 шага",
      faqEyebrow: "Вопросы",
      faqTitle: "Короткие ответы перед проверкой",
    },
    ctaNote: "После регистрации вы сразу перейдёте на страницу API keys.",
    personalEyebrow: "Экономия на ИИ для личного использования",
    personalBadge: "Бесплатная регистрация · сначала создайте key",
    personalPanelKicker: "Следующий шаг",
    personalTitle: "Снизьте личные расходы на AI API на 40%",
    personalAccent: "через один OpenAI-compatible key",
    personalDescription: "Для индивидуальных разработчиков: быстро подключайте Codex и Claude Code, добавляйте AI в свой продукт и используйте текст, аудио, видео и изображения через официальные upstream-каналы.",
    personalHighlight: "Регистрация бесплатна. Сначала создайте key; пополняйте баланс позже, когда будете готовы запускать реальное использование.",
    personalOfferTitle: "Создайте API key до оплаты",
    personalOfferBody: "Регистрация ведёт прямо на страницу API keys. Когда будете готовы, пополните от $20 и получите $5 бонуса для проверки реального использования.",
    createKey: "Создать бесплатный API key",
    personalQuickStartTitle: "Используйте текущий OpenAI SDK",
    personalQuickStartBody: "Измените только base_url и API key, затем запустите текущий script через Flatkey.",
    personalAgentAction: "Настроить Codex / Claude Code",
    personalSdkAction: "Скопировать SDK examples",
    proofTitle: "Надёжное качество через официальные токены",
    personalProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая модель работает через свои официальные upstream-токены, с доверенными источниками и подлинным качеством.",
    evidenceCheapTitle: "Токены на 40% дешевле",
    personalCheapBody: "Тот же бюджет даёт больше промптов, запусков кода и тестов изображений.",
    evidenceModelsTitle: "Много известных моделей",
    personalModelsBody: "Используйте один key для coding agents и AI-функций внутри вашего собственного продукта.",
    evidenceAgentsTitle: "Готово для Codex и Claude Code",
    personalAgentsBody: "Получайте доступ к text, audio, video и image models через официальные маршруты провайдеров с меньшим трением.",
    stepKeyTitle: "Создайте key",
    personalStepKeyBody: "Зарегистрируйтесь и сразу перейдите на страницу API keys.",
    stepRechargeTitle: "Подключите тест",
    personalStepRechargeBody: "Сначала создайте key; пополняйте позже, когда будете готовы.",
    stepUseTitle: "Используйте любую поддерживаемую модель",
    personalStepUseBody: "Направьте Codex, Claude Code, apps, scripts или backend вашего продукта на Flatkey.",
    personalFaq1Q: "Баланс сгорает?",
    personalFaq1A: "Предоплаченный баланс Flatkey рассчитан на использование со временем, а не как теряемая месячная подписка.",
    personalFaq2Q: "Это только для чата?",
    personalFaq2A: "Нет. Это подходит для coding agents и AI-функций продукта в тексте, аудио, видео и изображениях.",
    personalFaq3Q: "Нужно платить до регистрации?",
    personalFaq3A: "Нет. Регистрация и создание API key бесплатны. Пополняйте позже, когда будете тестировать реальное использование.",
    personalFinalTitle: "Сначала создайте API key",
    personalFinalBody: "Зарегистрируйтесь бесплатно, подключите реальный script и решайте после оценки цены и качества.",
    ctoEyebrow: "Экономия ИИ для CTO",
    ctoBadge: "Снизьте расходы на ИИ на 40% сегодня",
    ctoTitle: "Снизьте стоимость AI API и инженерного ИИ на 40%",
    ctoAccent: "без смены стека",
    ctoDescription: "Flatkey даёт команде совместимый gateway для продуктового ИИ, developer agents, логов, предоплаты и меньшего числа quota-блокировок.",
    ctoOfferTitle: "Проверьте с $20 + $5 бонуса",
    ctoOfferBody: "Сначала запустите реальную нагрузку. Если routing, качество и логи подходят, свяжитесь с нами для командных объёмов.",
    createTestKey: "Создать тестовый key",
    ctoProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая модель работает через свои официальные upstream-токены, с доверенными источниками и подлинным качеством для команд.",
    ctoEvidenceGatewayTitle: "Gateway для продуктового ИИ",
    ctoEvidenceGatewayBody: "Добавляйте ИИ в систему с совместимым key и понятным следом использования.",
    ctoEvidenceAgentsTitle: "Дешевле developer agents",
    ctoEvidenceAgentsBody: "Маршрутизируйте Codex, Claude Code и инженерные циклы через более дешёвое измеряемое использование.",
    ctoEvidenceQuotaTitle: "Меньше quota-блокировок",
    ctoEvidenceQuotaBody: "Снижайте трение, когда официальные аккаунты упираются в rate, quota или операционные лимиты.",
    ctoStepKeyTitle: "Создайте тестовый key",
    ctoStepKeyBody: "Используйте регистрацию, чтобы создать контролируемый key для проверки.",
    ctoStepWorkloadTitle: "Запустите реальную нагрузку",
    ctoStepWorkloadBody: "Сравните задержку, качество, логи и стоимость с текущим routing.",
    ctoStepScaleTitle: "Масштабируйте после проверки",
    ctoStepScaleBody: "Переходите на крупные предоплаченные пакеты или запросите командный план.",
    ctoFaq1Q: "Нужно много менять в коде?",
    ctoFaq1A: "Большинству OpenAI-compatible интеграций достаточно поменять base URL и key.",
    ctoFaq2Q: "Можно проверить до обязательств?",
    ctoFaq2A: "Да. Начните с $20 плюс $5 бонуса и измерьте реальную нагрузку.",
    ctoFaq3Q: "Подходит для нескольких инженеров?",
    ctoFaq3A: "Да. Flatkey централизует keys, балансы и логи для контроля общего использования.",
    ctoFinalTitle: "Докажите 40% экономии на своей нагрузке",
    ctoFinalBody: "Начните с небольшого key, проверьте качество routing и решите, масштабировать ли команду.",
    imageEyebrow: "Image Buddy для операционных команд",
    imageBadge: "Workflow изображений с меньшей стоимостью",
    imageTitle: "Создавайте campaign images быстрее с ИИ на 40% дешевле",
    imageAccent: "и повторяемыми workflows",
    imageDescription: "Flatkey снижает стоимость генерации изображений, а Image Buddy даёт готовые workflows вместо постоянного поиска prompts.",
    imageOfferTitle: "Создайте key, затем установите Image Buddy",
    imageOfferBody: "Используйте Flatkey для мощности и цены. Используйте templates Image Buddy для продукта, рекламы, marketplace и кампаний.",
    createKeyFirst: "Сначала создать key",
    imageProofTitle: "Стабильное качество для регулярной генерации",
    imageProofBody: "Flatkey получил признание OpenAI за прохождение 10 миллиардов токенов. Каждая поддерживаемая image и text model работает через свои официальные upstream-токены, надёжная основа для регулярной генерации.",
    imageEvidencePromptTitle: "Меньше поиска prompts",
    imageEvidencePromptBody: "Начинайте с повторяемых workflows Image Buddy вместо переписывания image prompts.",
    imageEvidenceQuotaTitle: "Меньше остановок из-за quota",
    imageEvidenceQuotaBody: "Используйте routing Flatkey, чтобы снизить трение от частых лимитов генерации.",
    imageEvidenceAssetTitle: "Assets для кампаний",
    imageEvidenceAssetBody: "Быстрее создавайте product visuals, ads, marketplace и social creatives.",
    imageStepKeyTitle: "Создайте key Flatkey",
    imageStepKeyBody: "Зарегистрируйтесь и создайте key, который будет использовать Image Buddy.",
    imageStepInstallTitle: "Установите Image Buddy",
    imageStepInstallBody: "Следуйте GitHub guide, чтобы добавить workflow в окружение.",
    imageStepGenerateTitle: "Генерируйте с templates",
    imageStepGenerateBody: "Выберите workflow, добавьте product context и создавайте полезные изображения.",
    imageFaq1Q: "Image Buddy только для разработчиков?",
    imageFaq1A: "Нет. Он упаковывает image prompts в повторяемые workflows для operations и команд.",
    imageFaq2Q: "Почему сначала создать key?",
    imageFaq2A: "Key включает routing Flatkey и capacity генерации до запросов Image Buddy.",
    imageFaq3Q: "Подходит для ecommerce?",
    imageFaq3A: "Да. Поддерживает product shots, marketplace cards, ads и регулярные creative needs.",
    imageFinalTitle: "Создайте key перед следующей партией изображений",
    imageFinalBody: "Сначала настройте Flatkey, затем используйте Image Buddy быстрее и дешевле.",
  },
  ja: {
    sectionLabels: {
      startEyebrow: "開始手順",
      startTitle: "3ステップで利用開始",
      faqEyebrow: "質問",
      faqTitle: "試す前の短い回答",
    },
    ctaNote: "登録後、そのままAPIキーページへ移動します。",
    personalEyebrow: "個人向けAI利用コスト削減",
    personalBadge: "登録無料・まずAPIキーを発行",
    personalPanelKicker: "次にやること",
    personalTitle: "個人開発者向け、AI APIコストを40%削減",
    personalAccent: "1つのOpenAI互換APIキーで接続",
    personalDescription: "個人開発者なら、CodexやClaude Codeをすぐ接続でき、自分のソフトウェアにもAI機能を追加できます。テキスト・音声・動画・画像モデルを公式上流チャネル経由で利用できます。",
    personalHighlight: "登録無料。APIキー作成後、チャージは実際に使う段階で可能です。",
    personalOfferTitle: "接続方法を選んで、すぐ試す",
    personalOfferBody: "Codex / Claude Codeなら一行コマンド、SDKならbase_urlを差し替えるだけです。",
    createKey: "無料でAPIキーを作成",
    personalQuickStartTitle: "既存のOpenAI SDKをそのまま利用",
    personalQuickStartBody: "base_urlとAPIキーを差し替えるだけで、現在のスクリプトをFlatkey経由でテストできます。",
    personalAgentAction: "Codex / Claude Code を設定",
    personalSdkAction: "SDK サンプルをコピー",
    proofTitle: "公式上流トークンによる安定したモデル品質を実現",
    personalProofBody: "Flatkeyは100億トークンの利用実績を達成し、OpenAIより認定を取得しています。対応するすべてのモデルは各社公式の上流トークンによって提供され、信頼性の高い配信元と本来のモデル品質を維持します。",
    evidenceCheapTitle: "トークン利用料が40%割安",
    personalCheapBody: "同じ予算でより多くのプロンプト実行・コーディング・画像生成テストが可能です。",
    evidenceModelsTitle: "各種人気AIモデル",
    personalModelsBody: "コーディングエージェントにも、自分のプロダクト内のAI機能にも、1つのAPIキーで対応できます。",
    evidenceAgentsTitle: "CodexとClaude Code対応",
    personalAgentsBody: "テキスト・音声・動画・画像モデルを公式プロバイダー経路で利用でき、より安全で管理も簡単です。",
    stepKeyTitle: "無料登録",
    personalStepKeyBody: "登録後、そのままAPIキーページへ移動します。",
    stepRechargeTitle: "接続方法を選択",
    personalStepRechargeBody: "Codex / Claude Codeに接続するか、OpenAI SDKのサンプルで動作確認できます。",
    stepUseTitle: "AIモデルを利用開始",
    personalStepUseBody: "Codex、Claude Code、アプリ、スクリプト、または自分のプロダクトバックエンドをFlatkeyに接続します。",
    personalFaq1Q: "残高は失効しますか？",
    personalFaq1A: "Flatkeyのプリペイド残高は継続利用向けで、月額プランのように毎月未使用残高が失われることはありません。",
    personalFaq2Q: "チャット用途だけですか？",
    personalFaq2A: "いいえ。CodexやClaude Codeのほか、自分のプロダクトに組み込むテキスト・音声・動画・画像AI機能にも使えます。",
    personalFaq3Q: "登録前に支払いが必要ですか？",
    personalFaq3A: "いいえ。登録とAPIキー作成は無料です。実際の利用を試す段階でチャージできます。",
    personalFinalTitle: "まず無料でAPIキーを作成",
    personalFinalBody: "登録後、そのままAPIキーページへ移動します。実際のスクリプトを接続し、コストと品質を確認してから利用判断できます。",
    ctoEyebrow: "CTO向けAIコスト削減",
    ctoBadge: "今日からAI支出を40%削減",
    ctoTitle: "AI APIと開発AIコストを40%削減",
    ctoAccent: "既存stackのままで",
    ctoDescription: "Flatkeyはproduct AI、developer agents、logs、prepaid balance、quota問題を1つの互換gatewayにまとめます。",
    ctoOfferTitle: "$20 + $5ボーナスで検証",
    ctoOfferBody: "まず実 workload を流してください。routing、品質、logsが基準を満たせば、大容量team pricingへ進めます。",
    createTestKey: "テストkeyを作成",
    ctoProofBody: "Flatkeyは10 billion tokens通過でOpenAIから認定を受けています。対応する全モデルはそれぞれの公式upstream tokensで提供され、team向けにも信頼できるソースと本来の品質を保ちます。",
    ctoEvidenceGatewayTitle: "Product AI gateway",
    ctoEvidenceGatewayBody: "互換keyと明確なusage trailで、既存システムにAI能力を追加できます。",
    ctoEvidenceAgentsTitle: "開発agentを低コスト化",
    ctoEvidenceAgentsBody: "Codex、Claude Code、engineering loopを低コストな従量課金へroutingします。",
    ctoEvidenceQuotaTitle: "quota詰まりを軽減",
    ctoEvidenceQuotaBody: "公式アカウントのrate、quota、運用制限に当たる摩擦を減らします。",
    ctoStepKeyTitle: "テストkeyを作成",
    ctoStepKeyBody: "登録flowで管理しやすい検証用keyを作ります。",
    ctoStepWorkloadTitle: "実 workload を実行",
    ctoStepWorkloadBody: "現在のroutingとlatency、品質、logs、コストを比較します。",
    ctoStepScaleTitle: "検証後にscale",
    ctoStepScaleBody: "大きなprepaid packageまたはteam planへ移行できます。",
    ctoFaq1Q: "多くのコード変更が必要ですか？",
    ctoFaq1A: "多くのOpenAI-compatible integrationはbase URLとkey変更だけで済みます。",
    ctoFaq2Q: "契約前に検証できますか？",
    ctoFaq2A: "はい。$20と$5ボーナスで実 workload を測定できます。",
    ctoFaq3Q: "複数エンジニアに向きますか？",
    ctoFaq3A: "はい。Flatkeyはkeys、balance、logsを集中管理し、shared usageを制御できます。",
    ctoFinalTitle: "自社workloadで40%削減を確認",
    ctoFinalBody: "小さなkeyから始め、routing品質を確認してteam scaleを判断できます。",
    imageEyebrow: "運用向けImage Buddy",
    imageBadge: "低コスト画像生成workflow",
    imageTitle: "40%安いAI usageでcampaign imagesをより速く生成",
    imageAccent: "再利用可能workflow付き",
    imageDescription: "Flatkeyは画像生成コストを下げ、Image Buddyは毎回promptを探さずに使えるworkflowを提供します。",
    imageOfferTitle: "key作成後にImage Buddyをinstall",
    imageOfferBody: "Flatkeyで生成capacityと低コストを確保し、Image Buddy templatesでproduct、ads、marketplace、campaign画像を作ります。",
    createKeyFirst: "先にkeyを作成",
    imageProofTitle: "継続的な生成でも安定した品質",
    imageProofBody: "Flatkeyは10 billion tokens通過でOpenAI認定を受けています。対応する画像・テキストモデルはそれぞれの公式upstream tokensで提供され、継続的なcreative generationの信頼できる基盤になります。",
    imageEvidencePromptTitle: "prompt探しを削減",
    imageEvidencePromptBody: "毎回image promptを書き直す代わりに、Image Buddyの再利用workflowから始めます。",
    imageEvidenceQuotaTitle: "quota停止を軽減",
    imageEvidenceQuotaBody: "Flatkey routingで、よくあるgeneration limitによる停止を減らします。",
    imageEvidenceAssetTitle: "campaign-ready assets",
    imageEvidenceAssetBody: "product visuals、ads、marketplace、social creativesをより速く作れます。",
    imageStepKeyTitle: "Flatkey keyを作成",
    imageStepKeyBody: "登録し、Image Buddyが使うkeyを作成します。",
    imageStepInstallTitle: "Image Buddyをinstall",
    imageStepInstallBody: "GitHub guideに従い、workflowを環境へ追加します。",
    imageStepGenerateTitle: "templatesで生成",
    imageStepGenerateBody: "workflowを選び、product contextを加えて使える画像を作ります。",
    imageFaq1Q: "Image Buddyは開発者専用ですか？",
    imageFaq1A: "いいえ。画像promptをoperationsやteam向けの反復可能workflowにします。",
    imageFaq2Q: "なぜ先にkeyを作るのですか？",
    imageFaq2A: "keyがFlatkey routingとgeneration capacityを有効にし、その後Image Buddyがrequestを送ります。",
    imageFaq3Q: "ecommerceに使えますか？",
    imageFaq3A: "はい。product shots、marketplace cards、adsなど反復creative needsに使えます。",
    imageFinalTitle: "次の画像バッチ前にkeyを作成",
    imageFinalBody: "まずFlatkeyを設定し、Image Buddyで反復creative workを速く安くします。",
  },
  vi: {
    sectionLabels: {
      startEyebrow: "Đường bắt đầu",
      startTitle: "Tạo API key trong 3 bước",
      faqEyebrow: "Câu hỏi",
      faqTitle: "Câu trả lời ngắn trước khi thử",
    },
    ctaNote: "Sau khi đăng ký, bạn sẽ vào thẳng trang API keys.",
    personalEyebrow: "Tiết kiệm AI cá nhân",
    personalBadge: "Đăng ký miễn phí · tạo key trước",
    personalPanelKicker: "Bước tiếp theo",
    personalTitle: "Giảm 40% chi phí AI API cá nhân",
    personalAccent: "với một key tương thích OpenAI",
    personalDescription: "Cho developer cá nhân: kết nối Codex và Claude Code nhanh, thêm AI vào sản phẩm của bạn, và dùng text, audio, video, image qua kênh upstream chính thức.",
    personalHighlight: "Đăng ký miễn phí. Tạo key trước; nạp tiền sau khi bạn sẵn sàng chạy usage thật.",
    personalOfferTitle: "Tạo API key trước khi trả tiền",
    personalOfferBody: "Luồng đăng ký đưa bạn thẳng đến trang API keys. Khi sẵn sàng, nạp từ $20 và nhận $5 bonus để kiểm tra usage thật.",
    createKey: "Tạo API key miễn phí",
    personalQuickStartTitle: "Dùng SDK OpenAI hiện có",
    personalQuickStartBody: "Chỉ đổi base_url và API key, rồi chạy script hiện tại qua Flatkey.",
    personalAgentAction: "Cài Codex / Claude Code",
    personalSdkAction: "Sao chép ví dụ SDK",
    proofTitle: "Chất lượng đáng tin từ token chính thức",
    personalProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình được hỗ trợ đều dùng upstream tokens chính thức tương ứng, từ nguồn đáng tin cậy và giữ chất lượng nguyên bản.",
    evidenceCheapTitle: "Token rẻ hơn 40%",
    personalCheapBody: "Cùng ngân sách có thể chạy nhiều prompt, lượt code và thử nghiệm ảnh hơn.",
    evidenceModelsTitle: "Nhiều mô hình nổi tiếng",
    personalModelsBody: "Dùng một key cho coding agents và cho tính năng AI trong phần mềm của bạn.",
    evidenceAgentsTitle: "Sẵn sàng cho Codex và Claude Code",
    personalAgentsBody: "Truy cập text, audio, video và image models qua tuyến provider chính thức, ít ma sát hơn.",
    stepKeyTitle: "Tạo key của bạn",
    personalStepKeyBody: "Đăng ký và vào thẳng trang API keys.",
    stepRechargeTitle: "Kết nối thử",
    personalStepRechargeBody: "Tạo key trước; nạp tiền sau khi bạn sẵn sàng.",
    stepUseTitle: "Dùng mọi mô hình hỗ trợ",
    personalStepUseBody: "Trỏ Codex, Claude Code, apps, scripts hoặc backend sản phẩm của bạn tới Flatkey.",
    personalFaq1Q: "Số dư có hết hạn không?",
    personalFaq1A: "Số dư trả trước Flatkey dành cho sử dụng lâu dài, không phải gói tháng bị mất nếu không dùng.",
    personalFaq2Q: "Chỉ dùng cho chat?",
    personalFaq2A: "Không. Dùng được cho coding agents và tính năng AI sản phẩm với text, audio, video và image.",
    personalFaq3Q: "Có cần trả tiền trước khi đăng ký?",
    personalFaq3A: "Không. Đăng ký và tạo API key miễn phí. Nạp tiền sau khi bạn muốn thử usage thật.",
    personalFinalTitle: "Tạo API key trước",
    personalFinalBody: "Đăng ký miễn phí, kết nối một script thật rồi quyết định sau khi thấy chi phí và chất lượng.",
    ctoEyebrow: "Tiết kiệm AI cho CTO",
    ctoBadge: "Giảm 40% chi phí AI ngay hôm nay",
    ctoTitle: "Giảm 40% chi phí AI API và AI cho kỹ thuật",
    ctoAccent: "không cần đổi stack",
    ctoDescription: "Flatkey cho đội ngũ một gateway tương thích cho AI sản phẩm, developer agents, logs, số dư trả trước và ít nghẽn quota hơn.",
    ctoOfferTitle: "Xác minh với $20 + $5 bonus",
    ctoOfferBody: "Chạy workload thật trước. Nếu routing, chất lượng và logs đạt chuẩn, hãy liên hệ để có giá team volume cao hơn.",
    createTestKey: "Tạo key thử nghiệm",
    ctoProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình được hỗ trợ đều dùng upstream tokens chính thức tương ứng, từ nguồn đáng tin cậy và giữ chất lượng nguyên bản cho đội ngũ.",
    ctoEvidenceGatewayTitle: "Gateway AI cho sản phẩm",
    ctoEvidenceGatewayBody: "Thêm AI vào hệ thống bằng một key tương thích và đường ghi nhận usage rõ ràng.",
    ctoEvidenceAgentsTitle: "Developer agents rẻ hơn",
    ctoEvidenceAgentsBody: "Route Codex, Claude Code và vòng lặp kỹ thuật qua mức sử dụng đo đếm chi phí thấp hơn.",
    ctoEvidenceQuotaTitle: "Ít bị kẹt quota hơn",
    ctoEvidenceQuotaBody: "Giảm ma sát khi tài khoản chính thức gặp rate, quota hoặc giới hạn vận hành.",
    ctoStepKeyTitle: "Tạo key thử nghiệm",
    ctoStepKeyBody: "Dùng luồng đăng ký để tạo key kiểm chứng có kiểm soát.",
    ctoStepWorkloadTitle: "Chạy workload thật",
    ctoStepWorkloadBody: "So sánh latency, chất lượng, logs và chi phí với routing hiện tại.",
    ctoStepScaleTitle: "Mở rộng sau khi xác minh",
    ctoStepScaleBody: "Chuyển sang gói trả trước lớn hơn hoặc hỏi plan team.",
    ctoFaq1Q: "Có cần đổi nhiều code không?",
    ctoFaq1A: "Phần lớn tích hợp OpenAI-compatible chỉ cần đổi base URL và key.",
    ctoFaq2Q: "Có thể xác minh trước cam kết không?",
    ctoFaq2A: "Có. Bắt đầu với $20 cộng $5 bonus và đo workload thật.",
    ctoFaq3Q: "Có phù hợp nhiều kỹ sư không?",
    ctoFaq3A: "Có. Flatkey tập trung keys, số dư và logs để kiểm soát usage chung.",
    ctoFinalTitle: "Chứng minh 40% tiết kiệm trên workload của bạn",
    ctoFinalBody: "Bắt đầu bằng key nhỏ, kiểm tra chất lượng routing rồi quyết định mở rộng team.",
    imageEyebrow: "Image Buddy cho vận hành",
    imageBadge: "Workflow ảnh chi phí thấp hơn",
    imageTitle: "Tạo campaign images nhanh hơn với AI rẻ hơn 40%",
    imageAccent: "và workflow tái sử dụng",
    imageDescription: "Flatkey giảm chi phí tạo ảnh, còn Image Buddy cung cấp workflow sẵn dùng thay vì phải tìm prompt mỗi lần.",
    imageOfferTitle: "Tạo key rồi cài Image Buddy",
    imageOfferBody: "Dùng Flatkey cho capacity và chi phí thấp hơn. Dùng templates Image Buddy cho sản phẩm, ads, marketplace và campaign.",
    createKeyFirst: "Tạo key trước",
    imageProofTitle: "Chất lượng ổn định cho sáng tạo lặp lại",
    imageProofBody: "Flatkey đã được OpenAI ghi nhận vì vượt 10 tỷ tokens. Mọi mô hình ảnh và văn bản được hỗ trợ đều dùng upstream tokens chính thức tương ứng, là nền tảng đáng tin cậy cho sáng tạo lặp lại.",
    imageEvidencePromptTitle: "Ít phải tìm prompt",
    imageEvidencePromptBody: "Bắt đầu từ workflow Image Buddy tái sử dụng thay vì viết lại image prompts.",
    imageEvidenceQuotaTitle: "Ít dừng vì quota",
    imageEvidenceQuotaBody: "Dùng Flatkey routing để giảm ma sát từ các giới hạn tạo ảnh thường gặp.",
    imageEvidenceAssetTitle: "Assets sẵn cho campaign",
    imageEvidenceAssetBody: "Tạo product visuals, ads, marketplace và social creatives nhanh hơn.",
    imageStepKeyTitle: "Tạo key Flatkey",
    imageStepKeyBody: "Đăng ký và tạo key mà Image Buddy sẽ dùng.",
    imageStepInstallTitle: "Cài Image Buddy",
    imageStepInstallBody: "Theo hướng dẫn GitHub để thêm workflow vào môi trường của bạn.",
    imageStepGenerateTitle: "Tạo bằng templates",
    imageStepGenerateBody: "Chọn workflow, thêm ngữ cảnh sản phẩm và tạo ảnh dùng được.",
    imageFaq1Q: "Image Buddy chỉ dành cho developer?",
    imageFaq1A: "Không. Nó đóng gói image prompts thành workflow lặp lại cho vận hành và đội nhóm.",
    imageFaq2Q: "Vì sao tạo key trước?",
    imageFaq2A: "Key mở Flatkey routing và capacity tạo ảnh trước khi Image Buddy gửi request.",
    imageFaq3Q: "Có dùng cho ecommerce không?",
    imageFaq3A: "Có. Hỗ trợ product shots, marketplace cards, ads và nhu cầu sáng tạo lặp lại.",
    imageFinalTitle: "Tạo key trước batch ảnh tiếp theo",
    imageFinalBody: "Cài Flatkey trước, rồi dùng Image Buddy để làm nhanh hơn và rẻ hơn.",
  },
  de: {
    sectionLabels: {
      startEyebrow: "Startpfad",
      startTitle: "API key in 3 Schritten erstellen",
      faqEyebrow: "Fragen",
      faqTitle: "Kurze Antworten vor dem Test",
    },
    ctaNote: "Nach dem Signup landest du direkt auf der API-key-Seite.",
    personalEyebrow: "Persönliche KI-Ersparnis",
    personalBadge: "Kostenlos registrieren · key zuerst erstellen",
    personalPanelKicker: "Nächster Schritt",
    personalTitle: "Senke persönliche KI-API-Kosten um 40%",
    personalAccent: "mit einem OpenAI-kompatiblen key",
    personalDescription: "Für einzelne Entwickler: Verbinde Codex und Claude Code schnell, füge deinem eigenen Produkt KI hinzu und nutze Text, Audio, Video und Bild über offizielle upstream-Kanäle.",
    personalHighlight: "Registrierung ist kostenlos. Erstelle zuerst den key; lade später auf, wenn du echte Nutzung testen willst.",
    personalOfferTitle: "API key vor der Zahlung erstellen",
    personalOfferBody: "Der Signup führt dich direkt zur API-key-Seite. Wenn du bereit bist, lade ab $20 auf und erhalte $5 Bonus für echte Tests.",
    createKey: "Kostenlosen API key erstellen",
    personalQuickStartTitle: "Nutze dein vorhandenes OpenAI SDK",
    personalQuickStartBody: "Ändere nur base_url und API key, dann führe dein aktuelles script über Flatkey aus.",
    personalAgentAction: "Codex / Claude Code einrichten",
    personalSdkAction: "SDK-Beispiele kopieren",
    proofTitle: "Verlässliche Qualität über offizielle Tokens",
    personalProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Modell läuft über seine offiziellen upstream Tokens, mit vertrauenswürdigen Quellen und authentischer Modellqualität.",
    evidenceCheapTitle: "Tokens 40% günstiger",
    personalCheapBody: "Dasselbe Budget reicht für mehr Prompts, Coding-Läufe und Bildtests.",
    evidenceModelsTitle: "Viele bekannte Modelle",
    personalModelsBody: "Nutze einen key für coding agents und für KI-Funktionen in deiner eigenen Software.",
    evidenceAgentsTitle: "Bereit für Codex und Claude Code",
    personalAgentsBody: "Greife auf Text-, Audio-, Video- und Bildmodelle über offizielle Provider-Routen zu, mit weniger Reibung.",
    stepKeyTitle: "Erstelle deinen key",
    personalStepKeyBody: "Registriere dich und lande direkt auf der API-key-Seite.",
    stepRechargeTitle: "Test verbinden",
    personalStepRechargeBody: "Erstelle zuerst den key; lade später auf, wenn du bereit bist.",
    stepUseTitle: "Nutze jedes unterstützte Modell",
    personalStepUseBody: "Richte Codex, Claude Code, apps, scripts oder dein Produkt-Backend auf Flatkey.",
    personalFaq1Q: "Verfällt das Guthaben?",
    personalFaq1A: "Flatkey-Prepaid-Guthaben ist für Nutzung über Zeit gedacht, nicht als verlorenes Monatsabo.",
    personalFaq2Q: "Ist es nur für Chat?",
    personalFaq2A: "Nein. Es passt für coding agents und Produkt-KI-Funktionen mit Text, Audio, Video und Bild.",
    personalFaq3Q: "Muss ich vor der Registrierung zahlen?",
    personalFaq3A: "Nein. Registrierung und API-key-Erstellung sind kostenlos. Lade später auf, wenn du echte Nutzung testest.",
    personalFinalTitle: "Erstelle zuerst den API key",
    personalFinalBody: "Registriere dich kostenlos, verbinde ein echtes script und entscheide anhand von Kosten und Qualität.",
    ctoEyebrow: "KI-Ersparnis für CTOs",
    ctoBadge: "Heute 40% KI-Kosten senken",
    ctoTitle: "Senke AI API und Engineering-KI-Kosten um 40%",
    ctoAccent: "ohne Stack-Wechsel",
    ctoDescription: "Flatkey gibt deinem Team ein kompatibles Gateway für Produkt-KI, Developer Agents, Logs, Prepaid-Guthaben und weniger quota-Blockaden.",
    ctoOfferTitle: "Mit $20 + $5 Bonus validieren",
    ctoOfferBody: "Führe zuerst reale Last aus. Wenn routing, Qualität und logs passen, kontaktiere uns für Team-Preise mit höherem Volumen.",
    createTestKey: "Test-key erstellen",
    ctoProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Modell läuft über seine offiziellen upstream Tokens, mit vertrauenswürdigen Quellen und authentischer Qualität für Teams.",
    ctoEvidenceGatewayTitle: "Produkt-KI-Gateway",
    ctoEvidenceGatewayBody: "Füge deinem System KI hinzu, mit kompatiblem key und klarer Nutzungsspur.",
    ctoEvidenceAgentsTitle: "Günstigere Developer Agents",
    ctoEvidenceAgentsBody: "Route Codex, Claude Code und Engineering-Schleifen über günstiger gemessene Nutzung.",
    ctoEvidenceQuotaTitle: "Weniger quota-Blockaden",
    ctoEvidenceQuotaBody: "Reduziere Reibung, wenn offizielle Konten rate, quota oder Betriebslimits erreichen.",
    ctoStepKeyTitle: "Test-key erstellen",
    ctoStepKeyBody: "Nutze Signup, um einen kontrollierten key für Validierung zu erstellen.",
    ctoStepWorkloadTitle: "Reale Last ausführen",
    ctoStepWorkloadBody: "Vergleiche Latenz, Qualität, logs und Kosten mit aktuellem routing.",
    ctoStepScaleTitle: "Nach Validierung skalieren",
    ctoStepScaleBody: "Wechsle zu größeren Prepaid-Paketen oder frage nach einem Team-Plan.",
    ctoFaq1Q: "Brauchen wir viele Codeänderungen?",
    ctoFaq1A: "Die meisten OpenAI-compatible Integrationen ändern nur base URL und key.",
    ctoFaq2Q: "Können wir vor Commitment validieren?",
    ctoFaq2A: "Ja. Starte mit $20 plus $5 Bonus und miss eine reale Last.",
    ctoFaq3Q: "Passt es für mehrere Engineers?",
    ctoFaq3A: "Ja. Flatkey zentralisiert keys, Guthaben und logs für gemeinsame Nutzungskontrolle.",
    ctoFinalTitle: "Beweise 40% Ersparnis mit deiner Last",
    ctoFinalBody: "Starte mit kleinem key, prüfe routing-Qualität und entscheide dann über Team-Skalierung.",
    imageEyebrow: "Image Buddy für Operations",
    imageBadge: "Bild-Workflow mit geringeren Kosten",
    imageTitle: "Erstelle campaign images schneller mit 40% günstigerer KI",
    imageAccent: "und wiederverwendbaren Workflows",
    imageDescription: "Flatkey senkt Bildgenerierungskosten, während Image Buddy fertige Workflows statt ständiger prompt-Suche liefert.",
    imageOfferTitle: "Key erstellen, dann Image Buddy installieren",
    imageOfferBody: "Nutze Flatkey für capacity und geringere Kosten. Nutze Image Buddy templates für Produkte, Anzeigen, Marketplace und Kampagnen.",
    createKeyFirst: "Zuerst key erstellen",
    imageProofTitle: "Stabile Qualität für wiederholte Kreativarbeit",
    imageProofBody: "Flatkey erhielt OpenAI-Anerkennung für über 10 Milliarden Tokens. Jedes unterstützte Bild- und Textmodell läuft über seine offiziellen upstream Tokens, eine vertrauenswürdige Basis für wiederholte Kreativarbeit.",
    imageEvidencePromptTitle: "Weniger prompt-Suche",
    imageEvidencePromptBody: "Starte mit wiederverwendbaren Image Buddy Workflows statt jedes image prompt neu zu schreiben.",
    imageEvidenceQuotaTitle: "Weniger quota-Stopps",
    imageEvidenceQuotaBody: "Nutze Flatkey routing, um Reibung durch häufige Generierungslimits zu senken.",
    imageEvidenceAssetTitle: "Assets für Kampagnen",
    imageEvidenceAssetBody: "Erstelle Produktbilder, ads, Marketplace-Assets und social creatives schneller.",
    imageStepKeyTitle: "Flatkey key erstellen",
    imageStepKeyBody: "Registriere dich und erstelle den key, den Image Buddy nutzt.",
    imageStepInstallTitle: "Image Buddy installieren",
    imageStepInstallBody: "Folge der GitHub-Anleitung, um den Workflow in deine Umgebung einzubinden.",
    imageStepGenerateTitle: "Mit templates generieren",
    imageStepGenerateBody: "Wähle Workflow, füge Produktkontext hinzu und erstelle nutzbare Bilder.",
    imageFaq1Q: "Ist Image Buddy nur für Developer?",
    imageFaq1A: "Nein. Es verpackt image prompts in wiederholbare Workflows für Operations und Teams.",
    imageFaq2Q: "Warum zuerst einen key erstellen?",
    imageFaq2A: "Der key aktiviert Flatkey routing und Generierungskapazität, bevor Image Buddy requests sendet.",
    imageFaq3Q: "Geht das für ecommerce?",
    imageFaq3A: "Ja. Unterstützt product shots, marketplace cards, ads und wiederkehrende creative needs.",
    imageFinalTitle: "Erstelle den key vor dem nächsten Bild-Batch",
    imageFinalBody: "Richte Flatkey zuerst ein und nutze Image Buddy schneller und günstiger.",
  },
};

export function getEdmCampaign(campaignId: EdmCampaignId, locale: Locale): EdmCampaignCopy {
  return CAMPAIGN_COPY[locale][campaignId];
}

export function getEdmCtaUrl(origin?: string): string {
  return origin ? `${origin.replace(/\/+$/, "")}/sign-up?redirect=/keys` : consoleUrl("/sign-up", "redirect=/keys");
}

export function getEdmMetadataInput(campaignId: EdmCampaignId, locale: Locale): SeoInput {
  const campaign = getEdmCampaign(campaignId, locale);
  return {
    title: `${campaign.hero.title} ${campaign.hero.accent}`,
    description: campaign.hero.description,
    pathname: EDM_LANDING_PATHS[campaignId],
    locale,
    noIndex: true,
  };
}
