import type { ModelDirectoryMeta } from "./model-directory-meta";

export type ModelDirectoryMetaPatch = Partial<Omit<ModelDirectoryMeta, "rank" | "top10">>;

export const STAGING_PREVIEW_MODEL_DIRECTORY_META_PATCHES: Record<string, ModelDirectoryMetaPatch> = {
  "MiniMax-H3": { providers: ["Minimax"] },
  "claude-haiku-4-5-20251001": { providers: ["Anthropic", "Amazon Bedrock", "Google"] },
  "deepseek-v3.1": { providers: ["Alibaba", "Baidu", "Google"] },
  "gemini-3.1-flash-tts-preview": { providers: ["Google", "Google AI Studio"] },
  "gemini-embedding-001": { providers: ["Google", "Google AI Studio"], categories: ["Technology"] },
  "gemini-flash-latest": { providers: ["Google", "Google AI Studio"] },
  "gemini-flash-lite-latest": {
    providers: ["Google", "Google AI Studio"],
    releasedAt: "2026-06-20",
  },
  "gemini-pro-latest": { providers: ["Google", "Google AI Studio"] },
  "gemini-robotics-er-1.6-preview": {
    providers: ["Google", "Google AI Studio"],
    categories: ["Science", "Technology"],
  },
  "gemma-4-31b-it": { providers: ["Google"] },
  "gpt-image-2": { providers: ["OpenAI"] },
  "grok-imagine-image": { providers: ["xAI"] },
  "grok-imagine-image-pro": { providers: ["xAI"], releasedAt: "2026-08-04" },
  "grok-imagine-image-quality": { providers: ["xAI"] },
  "grok-imagine-video": { providers: ["xAI"] },
  "grok-imagine-video-1.5": { providers: ["xAI"] },
  "macaron-v1-coding-venti": { providers: ["Macaron"] },
  "macaron-v1-tall": {
    providers: ["Macaron"],
    categories: ["Programming", "Marketing", "SEO", "Technology", "Translation", "Trivia"],
  },
  "macaron-v1-venti": {
    providers: ["Macaron"],
    categories: ["Programming", "Marketing", "SEO", "Technology", "Translation", "Trivia"],
  },
  "nano-banana-pro-preview": { providers: ["Google", "Google AI Studio"] },
  "qwen3.5-plus-2026-02-15": { providers: ["Alibaba"] },
  "seedance-2.0-pro": { providers: ["ByteDance"] },
  "seedance-2.5": { providers: ["ByteDance"] },
  "sonilo-video-to-music": { providers: ["Sonilo"] },
  "veo-3.1-fast-generate-preview": { providers: ["Google", "Google AI Studio"] },
  "veo-3.1-generate-preview": { providers: ["Google", "Google AI Studio"] },
};

// Candidate metadata used only by the staging website build so product can
// review how newly discovered catalogue models behave in every directory
// filter. These rows are deliberately excluded from production builds. The
// provider/vendor identities are grounded in the staging pricing catalogue;
// release dates and use-case classifications remain preview values until the
// production-data review approves them.
export const STAGING_PREVIEW_MODEL_DIRECTORY_META: Record<string, ModelDirectoryMeta> = {
  "bytedance/seedance-2.0": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 101,
  },
  "bytedance/seedance-2.0-fast": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 102,
  },
  "claude-3-5-haiku-20241022": {
    series: "Claude",
    vendor: "Anthropic",
    providers: ["Anthropic", "Amazon Bedrock", "Google"],
    modalities: ["text", "image", "file"],
    contextTokens: 200000,
    categories: ["Programming", "Marketing", "SEO", "Technology", "Translation", "Trivia"],
    distillable: false,
    releasedAt: "2024-10-22",
    rank: 103,
  },
  "doubao/doubao-seedance-2-0-260128": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 104,
  },
  "gemini-2.0-flash": {
    series: "Gemini",
    vendor: "Google",
    providers: ["Google", "Google AI Studio"],
    modalities: ["text", "image", "file", "audio", "video"],
    contextTokens: 1048576,
    categories: ["Programming", "Roleplay", "Marketing", "SEO", "Technology", "Translation", "Trivia", "Academia"],
    distillable: false,
    releasedAt: "2025-02-05",
    rank: 105,
  },
  "jimeng-image-4.5": {
    series: "Jimeng",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 106,
  },
  "jimeng-image-5.0-lite": {
    series: "Jimeng",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-04-06",
    rank: 107,
  },
  "jimeng-video-3.0-fast": {
    series: "Jimeng",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 108,
  },
  "jimeng-video-3.0-pro": {
    series: "Jimeng",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 109,
  },
  "jimeng-video-seedance-2.0": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 110,
  },
  "jimeng-video-seedance-2.0-fast": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 111,
  },
  "jimeng-video-seedance-2.0-mini": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["Jimeng"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 112,
  },
  "mirothinker-1-7-deepresearch": {
    series: "MiroThinker",
    vendor: "MiroMind AI",
    providers: ["MiroMind AI"],
    modalities: ["text", "file"],
    contextTokens: 128000,
    categories: ["Academia", "Science", "Technology"],
    distillable: true,
    releasedAt: "2026-08-01",
    rank: 113,
  },
  "mirothinker-1-7-deepresearch-mini": {
    series: "MiroThinker",
    vendor: "MiroMind AI",
    providers: ["MiroMind AI"],
    modalities: ["text", "file"],
    contextTokens: 128000,
    categories: ["Academia", "Science", "Technology"],
    distillable: true,
    releasedAt: "2026-08-01",
    rank: 114,
  },
  "seedance-2.0": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 115,
  },
  "seedance-2.0-fast": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 116,
  },
  "seedance-2.0-mini": {
    series: "Seedance",
    vendor: "ByteDance",
    providers: ["ByteDance"],
    modalities: ["text", "image", "video"],
    contextTokens: null,
    categories: ["Marketing"],
    distillable: false,
    releasedAt: "2026-01-28",
    rank: 117,
  },
};
