import type { Locale } from "./locales";
import type { AgeBand, Modality } from "./model-directory-meta";
import type { DirectorySort } from "./model-directory-filters";

// User-facing strings for the /models directory. Every locale the site ships is
// translated here — an English fallback would render an untranslated sidebar on
// nine of the ten locales, so the tables below are exhaustive by construction
// (Record<Locale, …> makes a missing locale a type error).

export type DirectoryCopy = {
  filter: string;
  reset: string;
  searchPlaceholder: string;
  allModels: string;
  modelsFound: string;
  sortLabel: string;
  clearFilters: string;
  removeFilter: string;
  noResults: string;
  noResultsHint: string;
  colModel: string;
  colOfficial: string;
  colOurPrice: string;
  colDiscount: string;
  colLatency: string;
  colHealth: string;
  colContext: string;
  learnMore: string;
  featuredLabel: string;
  chooseSlide: string;
  groupModalities: string;
  groupContext: string;
  groupInputPrice: string;
  groupOutputPrice: string;
  groupSeries: string;
  groupCategories: string;
  groupAge: string;
  groupDistillable: string;
  yes: string;
  no: string;
  /** Page <title> and meta description for the unfiltered directory. */
  seoTitle: string;
  seoDescription: string;
  /**
   * Single-series views (/models?series=Claude) are indexable landing pages, so
   * they get their own title and description. {{series}} is the family name.
   */
  seoSeriesTitle: string;
  seoSeriesDescription: string;
};

export const DIRECTORY_COPY: Record<Locale, DirectoryCopy> = {
  en: {
    filter: "Filter",
    reset: "Reset",
    searchPlaceholder: "Search model name, provider, endpoint, or tag…",
    allModels: "All Models",
    modelsFound: "{{count}} models found",
    sortLabel: "Sort order",
    clearFilters: "Clear all filters",
    removeFilter: "Remove filter",
    noResults: "No models match these filters",
    noResultsHint: "Try loosening one of the conditions.",
    colModel: "Model",
    colOfficial: "Official",
    colOurPrice: "Our price",
    colDiscount: "Discount",
    colLatency: "Latency",
    colHealth: "Health score",
    colContext: "Context",
    learnMore: "Learn More",
    featuredLabel: "Featured models",
    chooseSlide: "Choose a featured model",
    groupModalities: "Input Modalities",
    groupContext: "Context Length",
    groupInputPrice: "Input Pricing",
    groupOutputPrice: "Output Pricing",
    groupSeries: "Series",
    groupCategories: "Categories",
    groupAge: "Model Age",
    groupDistillable: "Distillable",
    yes: "Yes",
    no: "No",
    seoTitle: "AI Model Directory — Compare 90+ Models by Price, Context & Speed",
    seoDescription:
      "Browse every AI model on flatkey.ai in one table: official vs. our price, context length, latency and live health. Filter by modality, context window, price band, series and use case.",
    seoSeriesTitle: "{{series}} API Pricing & Models — Compare Rates on flatkey.ai",
    seoSeriesDescription:
      "Every {{series}} model available through flatkey.ai, with official vs. our pricing, context length, latency and live health in one comparison table.",
  },
  zh: {
    filter: "筛选",
    reset: "重置",
    searchPlaceholder: "搜索模型名称、供应商、端点或标签…",
    allModels: "全部模型",
    modelsFound: "找到 {{count}} 个模型",
    sortLabel: "排序方式",
    clearFilters: "清除全部筛选",
    removeFilter: "移除筛选",
    noResults: "没有模型符合当前筛选条件",
    noResultsHint: "试试放宽其中一个条件。",
    colModel: "模型",
    colOfficial: "官方价",
    colOurPrice: "我们的价格",
    colDiscount: "折扣",
    colLatency: "延迟",
    colHealth: "健康评分",
    colContext: "上下文",
    learnMore: "了解更多",
    featuredLabel: "精选模型",
    chooseSlide: "选择精选模型",
    groupModalities: "输入模态",
    groupContext: "上下文长度",
    groupInputPrice: "输入价格",
    groupOutputPrice: "输出价格",
    groupSeries: "模型系列",
    groupCategories: "适用场景",
    groupAge: "发布时间",
    groupDistillable: "可蒸馏",
    yes: "是",
    no: "否",
    seoTitle: "AI 模型目录 — 90+ 模型价格、上下文与速度对比",
    seoDescription: "在一张表里浏览 flatkey.ai 全部 AI 模型：官方价与我们的价格对比、上下文长度、延迟与实时健康度。可按输入模态、上下文窗口、价格区间、系列与适用场景筛选。",
    seoSeriesTitle: "{{series}} API 价格与模型 — flatkey.ai 费率对比",
    seoSeriesDescription: "flatkey.ai 提供的全部 {{series}} 模型，官方价与我们的价格、上下文长度、延迟与实时健康度一表对比。",
  },
  es: {
    filter: "Filtrar",
    reset: "Restablecer",
    searchPlaceholder: "Busca por modelo, proveedor, endpoint o etiqueta…",
    allModels: "Todos los modelos",
    modelsFound: "{{count}} modelos encontrados",
    sortLabel: "Orden",
    clearFilters: "Borrar todos los filtros",
    removeFilter: "Quitar filtro",
    noResults: "Ningún modelo coincide con estos filtros",
    noResultsHint: "Prueba a relajar alguna de las condiciones.",
    colModel: "Modelo",
    colOfficial: "Oficial",
    colOurPrice: "Nuestro precio",
    colDiscount: "Descuento",
    colLatency: "Latencia",
    colHealth: "Puntuación de salud",
    colContext: "Contexto",
    learnMore: "Saber más",
    featuredLabel: "Modelos destacados",
    chooseSlide: "Elige un modelo destacado",
    groupModalities: "Modalidades de entrada",
    groupContext: "Longitud de contexto",
    groupInputPrice: "Precio de entrada",
    groupOutputPrice: "Precio de salida",
    groupSeries: "Serie",
    groupCategories: "Categorías",
    groupAge: "Antigüedad del modelo",
    groupDistillable: "Destilable",
    yes: "Sí",
    no: "No",
    seoTitle: "Directorio de modelos de IA: compara más de 90 modelos por precio, contexto y velocidad",
    seoDescription:
      "Consulta todos los modelos de IA de flatkey.ai en una sola tabla: precio oficial frente al nuestro, longitud de contexto, latencia y estado en vivo. Filtra por modalidad, ventana de contexto, rango de precio, serie y caso de uso.",
    seoSeriesTitle: "Precios y modelos de la API de {{series}} — Compara tarifas en flatkey.ai",
    seoSeriesDescription:
      "Todos los modelos {{series}} disponibles en flatkey.ai, con precio oficial frente al nuestro, longitud de contexto, latencia y estado en vivo en una tabla comparativa.",
  },
  fr: {
    filter: "Filtrer",
    reset: "Réinitialiser",
    searchPlaceholder: "Rechercher un modèle, un fournisseur, un endpoint ou un tag…",
    allModels: "Tous les modèles",
    modelsFound: "{{count}} modèles trouvés",
    sortLabel: "Tri",
    clearFilters: "Effacer tous les filtres",
    removeFilter: "Retirer le filtre",
    noResults: "Aucun modèle ne correspond à ces filtres",
    noResultsHint: "Essayez d'assouplir l'une des conditions.",
    colModel: "Modèle",
    colOfficial: "Officiel",
    colOurPrice: "Notre prix",
    colDiscount: "Remise",
    colLatency: "Latence",
    colHealth: "Score de santé",
    colContext: "Contexte",
    learnMore: "En savoir plus",
    featuredLabel: "Modèles en vedette",
    chooseSlide: "Choisir un modèle en vedette",
    groupModalities: "Modalités d'entrée",
    groupContext: "Longueur de contexte",
    groupInputPrice: "Prix en entrée",
    groupOutputPrice: "Prix en sortie",
    groupSeries: "Série",
    groupCategories: "Catégories",
    groupAge: "Ancienneté du modèle",
    groupDistillable: "Distillable",
    yes: "Oui",
    no: "Non",
    seoTitle: "Répertoire des modèles d'IA — Comparez plus de 90 modèles par prix, contexte et vitesse",
    seoDescription: "Parcourez tous les modèles d'IA de flatkey.ai dans un seul tableau : prix officiel contre le nôtre, longueur de contexte, latence et état en direct. Filtrez par modalité, fenêtre de contexte, tranche de prix, série et cas d'usage.",
    seoSeriesTitle: "Tarifs et modèles de l'API {{series}} — Comparez les prix sur flatkey.ai",
    seoSeriesDescription: "Tous les modèles {{series}} disponibles via flatkey.ai, avec prix officiel contre le nôtre, longueur de contexte, latence et état en direct dans un tableau comparatif.",
  },
  pt: {
    filter: "Filtrar",
    reset: "Redefinir",
    searchPlaceholder: "Pesquise por modelo, provedor, endpoint ou tag…",
    allModels: "Todos os modelos",
    modelsFound: "{{count}} modelos encontrados",
    sortLabel: "Ordenação",
    clearFilters: "Limpar todos os filtros",
    removeFilter: "Remover filtro",
    noResults: "Nenhum modelo corresponde a estes filtros",
    noResultsHint: "Tente afrouxar uma das condições.",
    colModel: "Modelo",
    colOfficial: "Oficial",
    colOurPrice: "Nosso preço",
    colDiscount: "Desconto",
    colLatency: "Latência",
    colHealth: "Pontuação de saúde",
    colContext: "Contexto",
    learnMore: "Saiba mais",
    featuredLabel: "Modelos em destaque",
    chooseSlide: "Escolha um modelo em destaque",
    groupModalities: "Modalidades de entrada",
    groupContext: "Tamanho do contexto",
    groupInputPrice: "Preço de entrada",
    groupOutputPrice: "Preço de saída",
    groupSeries: "Série",
    groupCategories: "Categorias",
    groupAge: "Idade do modelo",
    groupDistillable: "Destilável",
    yes: "Sim",
    no: "Não",
    seoTitle: "Diretório de modelos de IA — Compare mais de 90 modelos por preço, contexto e velocidade",
    seoDescription: "Veja todos os modelos de IA da flatkey.ai em uma única tabela: preço oficial versus o nosso, tamanho do contexto, latência e integridade em tempo real. Filtre por modalidade, janela de contexto, faixa de preço, série e caso de uso.",
    seoSeriesTitle: "Preços e modelos da API {{series}} — Compare taxas na flatkey.ai",
    seoSeriesDescription: "Todos os modelos {{series}} disponíveis na flatkey.ai, com preço oficial versus o nosso, tamanho do contexto, latência e integridade em tempo real em uma tabela comparativa.",
  },
  ru: {
    filter: "Фильтр",
    reset: "Сбросить",
    searchPlaceholder: "Поиск по модели, провайдеру, endpoint или тегу…",
    allModels: "Все модели",
    modelsFound: "Найдено моделей: {{count}}",
    sortLabel: "Сортировка",
    clearFilters: "Очистить все фильтры",
    removeFilter: "Убрать фильтр",
    noResults: "Нет моделей, соответствующих фильтрам",
    noResultsHint: "Попробуйте ослабить одно из условий.",
    colModel: "Модель",
    colOfficial: "Официальная",
    colOurPrice: "Наша цена",
    colDiscount: "Скидка",
    colLatency: "Задержка",
    colHealth: "Оценка здоровья",
    colContext: "Контекст",
    learnMore: "Подробнее",
    featuredLabel: "Избранные модели",
    chooseSlide: "Выберите избранную модель",
    groupModalities: "Входные модальности",
    groupContext: "Длина контекста",
    groupInputPrice: "Цена за ввод",
    groupOutputPrice: "Цена за вывод",
    groupSeries: "Серия",
    groupCategories: "Категории",
    groupAge: "Возраст модели",
    groupDistillable: "Дистиллируемая",
    yes: "Да",
    no: "Нет",
    seoTitle: "Каталог моделей ИИ — сравните более 90 моделей по цене, контексту и скорости",
    seoDescription: "Все модели ИИ на flatkey.ai в одной таблице: официальная цена против нашей, длина контекста, задержка и состояние в реальном времени. Фильтруйте по модальности, окну контекста, ценовому диапазону, серии и сценарию использования.",
    seoSeriesTitle: "Цены и модели API {{series}} — сравнение тарифов на flatkey.ai",
    seoSeriesDescription: "Все модели {{series}}, доступные через flatkey.ai: официальная цена против нашей, длина контекста, задержка и состояние в реальном времени в одной сравнительной таблице.",
  },
  ja: {
    filter: "絞り込み",
    reset: "リセット",
    searchPlaceholder: "モデル名、プロバイダー、endpoint、タグで検索…",
    allModels: "すべてのモデル",
    modelsFound: "{{count}} 件のモデルが見つかりました",
    sortLabel: "並び順",
    clearFilters: "すべての条件を解除",
    removeFilter: "条件を外す",
    noResults: "条件に一致するモデルがありません",
    noResultsHint: "いずれかの条件をゆるめてみてください。",
    colModel: "モデル",
    colOfficial: "公式価格",
    colOurPrice: "当社価格",
    colDiscount: "割引",
    colLatency: "レイテンシ",
    colHealth: "健全性スコア",
    colContext: "コンテキスト",
    learnMore: "詳しく見る",
    featuredLabel: "注目のモデル",
    chooseSlide: "注目のモデルを選ぶ",
    groupModalities: "入力モダリティ",
    groupContext: "コンテキスト長",
    groupInputPrice: "入力料金",
    groupOutputPrice: "出力料金",
    groupSeries: "シリーズ",
    groupCategories: "カテゴリ",
    groupAge: "モデルの新しさ",
    groupDistillable: "蒸留可能",
    yes: "可",
    no: "不可",
    seoTitle: "AI モデルディレクトリ — 90 以上のモデルを価格・コンテキスト・速度で比較",
    seoDescription: "flatkey.ai のすべての AI モデルを 1 つの表で確認できます。公式価格と当社価格、コンテキスト長、レイテンシ、リアルタイムの健全性を掲載。入力モダリティ、コンテキスト長、価格帯、シリーズ、用途で絞り込めます。",
    seoSeriesTitle: "{{series}} API の料金とモデル — flatkey.ai で料金を比較",
    seoSeriesDescription: "flatkey.ai で利用できるすべての {{series}} モデルを、公式価格と当社価格、コンテキスト長、レイテンシ、リアルタイムの健全性とともに 1 つの比較表で確認できます。",
  },
  vi: {
    filter: "Bộ lọc",
    reset: "Đặt lại",
    searchPlaceholder: "Tìm theo tên mô hình, nhà cung cấp, endpoint hoặc tag…",
    allModels: "Tất cả mô hình",
    modelsFound: "Tìm thấy {{count}} mô hình",
    sortLabel: "Sắp xếp",
    clearFilters: "Xóa tất cả bộ lọc",
    removeFilter: "Bỏ bộ lọc",
    noResults: "Không có mô hình nào khớp với bộ lọc",
    noResultsHint: "Hãy thử nới lỏng một trong các điều kiện.",
    colModel: "Mô hình",
    colOfficial: "Giá gốc",
    colOurPrice: "Giá của chúng tôi",
    colDiscount: "Giảm giá",
    colLatency: "Độ trễ",
    colHealth: "Điểm sức khỏe",
    colContext: "Ngữ cảnh",
    learnMore: "Tìm hiểu thêm",
    featuredLabel: "Mô hình nổi bật",
    chooseSlide: "Chọn mô hình nổi bật",
    groupModalities: "Phương thức đầu vào",
    groupContext: "Độ dài ngữ cảnh",
    groupInputPrice: "Giá đầu vào",
    groupOutputPrice: "Giá đầu ra",
    groupSeries: "Dòng mô hình",
    groupCategories: "Danh mục",
    groupAge: "Thời điểm ra mắt",
    groupDistillable: "Có thể chưng cất",
    yes: "Có",
    no: "Không",
    seoTitle: "Danh mục mô hình AI — So sánh hơn 90 mô hình theo giá, ngữ cảnh và tốc độ",
    seoDescription: "Xem toàn bộ mô hình AI trên flatkey.ai trong một bảng: giá gốc so với giá của chúng tôi, độ dài ngữ cảnh, độ trễ và tình trạng theo thời gian thực. Lọc theo phương thức đầu vào, cửa sổ ngữ cảnh, khoảng giá, dòng mô hình và mục đích sử dụng.",
    seoSeriesTitle: "Giá và mô hình API {{series}} — So sánh mức giá trên flatkey.ai",
    seoSeriesDescription: "Toàn bộ mô hình {{series}} khả dụng qua flatkey.ai, kèm giá gốc so với giá của chúng tôi, độ dài ngữ cảnh, độ trễ và tình trạng theo thời gian thực trong một bảng so sánh.",
  },
  de: {
    filter: "Filtern",
    reset: "Zurücksetzen",
    searchPlaceholder: "Nach Modell, Anbieter, Endpoint oder Tag suchen…",
    allModels: "Alle Modelle",
    modelsFound: "{{count}} Modelle gefunden",
    sortLabel: "Sortierung",
    clearFilters: "Alle Filter löschen",
    removeFilter: "Filter entfernen",
    noResults: "Keine Modelle passen zu diesen Filtern",
    noResultsHint: "Versuchen Sie, eine der Bedingungen zu lockern.",
    colModel: "Modell",
    colOfficial: "Offiziell",
    colOurPrice: "Unser Preis",
    colDiscount: "Rabatt",
    colLatency: "Latenz",
    colHealth: "Gesundheitswert",
    colContext: "Kontext",
    learnMore: "Mehr erfahren",
    featuredLabel: "Empfohlene Modelle",
    chooseSlide: "Empfohlenes Modell wählen",
    groupModalities: "Eingabemodalitäten",
    groupContext: "Kontextlänge",
    groupInputPrice: "Eingabepreis",
    groupOutputPrice: "Ausgabepreis",
    groupSeries: "Serie",
    groupCategories: "Kategorien",
    groupAge: "Modellalter",
    groupDistillable: "Destillierbar",
    yes: "Ja",
    no: "Nein",
    seoTitle: "KI-Modellverzeichnis — über 90 Modelle nach Preis, Kontext und Geschwindigkeit vergleichen",
    seoDescription: "Alle KI-Modelle auf flatkey.ai in einer Tabelle: offizieller Preis gegen unseren, Kontextlänge, Latenz und Live-Status. Filtern Sie nach Eingabemodalität, Kontextfenster, Preisspanne, Serie und Anwendungsfall.",
    seoSeriesTitle: "{{series}} API-Preise und Modelle — Tarife auf flatkey.ai vergleichen",
    seoSeriesDescription: "Alle über flatkey.ai verfügbaren {{series}}-Modelle mit offiziellem Preis gegen unseren, Kontextlänge, Latenz und Live-Status in einer Vergleichstabelle.",
  },
  id: {
    filter: "Filter",
    reset: "Atur ulang",
    searchPlaceholder: "Cari nama model, penyedia, endpoint, atau tag…",
    allModels: "Semua model",
    modelsFound: "{{count}} model ditemukan",
    sortLabel: "Urutan",
    clearFilters: "Hapus semua filter",
    removeFilter: "Hapus filter",
    noResults: "Tidak ada model yang cocok dengan filter ini",
    noResultsHint: "Coba longgarkan salah satu kondisinya.",
    colModel: "Model",
    colOfficial: "Resmi",
    colOurPrice: "Harga kami",
    colDiscount: "Diskon",
    colLatency: "Latensi",
    colHealth: "Skor kesehatan",
    colContext: "Konteks",
    learnMore: "Pelajari lebih lanjut",
    featuredLabel: "Model unggulan",
    chooseSlide: "Pilih model unggulan",
    groupModalities: "Modalitas masukan",
    groupContext: "Panjang konteks",
    groupInputPrice: "Harga masukan",
    groupOutputPrice: "Harga keluaran",
    groupSeries: "Seri",
    groupCategories: "Kategori",
    groupAge: "Usia model",
    groupDistillable: "Dapat didistilasi",
    yes: "Ya",
    no: "Tidak",
    seoTitle: "Direktori Model AI — Bandingkan 90+ Model berdasarkan Harga, Konteks, dan Kecepatan",
    seoDescription: "Jelajahi semua model AI di flatkey.ai dalam satu tabel: harga resmi versus harga kami, panjang konteks, latensi, dan kesehatan real-time. Saring berdasarkan modalitas masukan, jendela konteks, rentang harga, seri, dan kasus penggunaan.",
    seoSeriesTitle: "Harga dan Model API {{series}} — Bandingkan Tarif di flatkey.ai",
    seoSeriesDescription: "Semua model {{series}} yang tersedia melalui flatkey.ai, dengan harga resmi versus harga kami, panjang konteks, latensi, dan kesehatan real-time dalam satu tabel perbandingan.",
  },
};

export const MODALITY_LABELS: Record<Locale, Record<Modality, string>> = {
  en: { text: "Text", image: "Image", file: "File", audio: "Audio", video: "Video" },
  zh: { text: "文本", image: "图像", file: "文件", audio: "音频", video: "视频" },
  es: { text: "Texto", image: "Imagen", file: "Archivo", audio: "Audio", video: "Vídeo" },
  fr: { text: "Texte", image: "Image", file: "Fichier", audio: "Audio", video: "Vidéo" },
  pt: { text: "Texto", image: "Imagem", file: "Arquivo", audio: "Áudio", video: "Vídeo" },
  ru: { text: "Текст", image: "Изображение", file: "Файл", audio: "Аудио", video: "Видео" },
  ja: { text: "テキスト", image: "画像", file: "ファイル", audio: "音声", video: "動画" },
  vi: { text: "Văn bản", image: "Hình ảnh", file: "Tệp", audio: "Âm thanh", video: "Video" },
  de: { text: "Text", image: "Bild", file: "Datei", audio: "Audio", video: "Video" },
  id: { text: "Teks", image: "Gambar", file: "Berkas", audio: "Audio", video: "Video" },
};

export const AGE_BAND_LABELS: Record<Locale, Record<AgeBand, string>> = {
  en: { new: "New (< 1 month)", "1-3m": "1–3 months", "3-6m": "3–6 months", "6-12m": "6–12 months", "12m+": "12+ months" },
  zh: { new: "最新（1 个月内）", "1-3m": "1–3 个月", "3-6m": "3–6 个月", "6-12m": "6–12 个月", "12m+": "12 个月以上" },
  es: { new: "Nuevo (< 1 mes)", "1-3m": "1–3 meses", "3-6m": "3–6 meses", "6-12m": "6–12 meses", "12m+": "Más de 12 meses" },
  fr: { new: "Nouveau (< 1 mois)", "1-3m": "1–3 mois", "3-6m": "3–6 mois", "6-12m": "6–12 mois", "12m+": "Plus de 12 mois" },
  pt: { new: "Novo (< 1 mês)", "1-3m": "1–3 meses", "3-6m": "3–6 meses", "6-12m": "6–12 meses", "12m+": "Mais de 12 meses" },
  ru: { new: "Новые (< 1 месяца)", "1-3m": "1–3 месяца", "3-6m": "3–6 месяцев", "6-12m": "6–12 месяцев", "12m+": "Более 12 месяцев" },
  ja: { new: "新着（1 か月未満）", "1-3m": "1〜3 か月", "3-6m": "3〜6 か月", "6-12m": "6〜12 か月", "12m+": "12 か月以上" },
  vi: { new: "Mới (< 1 tháng)", "1-3m": "1–3 tháng", "3-6m": "3–6 tháng", "6-12m": "6–12 tháng", "12m+": "Trên 12 tháng" },
  de: { new: "Neu (< 1 Monat)", "1-3m": "1–3 Monate", "3-6m": "3–6 Monate", "6-12m": "6–12 Monate", "12m+": "Über 12 Monate" },
  id: { new: "Baru (< 1 bulan)", "1-3m": "1–3 bulan", "3-6m": "3–6 bulan", "6-12m": "6–12 bulan", "12m+": "Lebih dari 12 bulan" },
};

export const SORT_LABELS: Record<Locale, Record<DirectorySort, string>> = {
  en: { rank: "Most Popular", newest: "Newest", ctxDesc: "Longest context", name: "Name A–Z" },
  zh: { rank: "最受欢迎", newest: "最新发布", ctxDesc: "上下文最长", name: "名称 A–Z" },
  es: { rank: "Más populares", newest: "Más recientes", ctxDesc: "Mayor contexto", name: "Nombre A–Z" },
  fr: { rank: "Les plus populaires", newest: "Les plus récents", ctxDesc: "Contexte le plus long", name: "Nom A–Z" },
  pt: { rank: "Mais populares", newest: "Mais recentes", ctxDesc: "Maior contexto", name: "Nome A–Z" },
  ru: { rank: "Популярные", newest: "Новые", ctxDesc: "Наибольший контекст", name: "Название А–Я" },
  ja: { rank: "人気順", newest: "新着順", ctxDesc: "コンテキストが長い順", name: "名前 A–Z" },
  vi: { rank: "Phổ biến nhất", newest: "Mới nhất", ctxDesc: "Ngữ cảnh dài nhất", name: "Tên A–Z" },
  de: { rank: "Beliebteste", newest: "Neueste", ctxDesc: "Längster Kontext", name: "Name A–Z" },
  id: { rank: "Paling populer", newest: "Terbaru", ctxDesc: "Konteks terpanjang", name: "Nama A–Z" },
};

// Use-case categories come from the metadata table as English keys; these are
// their display forms. An unmapped category falls back to its raw key, which is
// already human-readable rather than an identifier.
export const CATEGORY_LABELS: Record<Locale, Record<string, string>> = {
  en: {},
  zh: {
    Programming: "编程",
    Marketing: "营销",
    Technology: "技术",
    SEO: "SEO",
    Trivia: "常识问答",
    Academia: "学术",
    Translation: "翻译",
    Roleplay: "角色扮演",
    Science: "科学",
    Finance: "金融",
    Legal: "法律",
    Health: "健康",
  },
  es: {
    Programming: "Programación",
    Marketing: "Marketing",
    Technology: "Tecnología",
    SEO: "SEO",
    Trivia: "Preguntas generales",
    Academia: "Academia",
    Translation: "Traducción",
    Roleplay: "Rol",
    Science: "Ciencia",
    Finance: "Finanzas",
    Legal: "Legal",
    Health: "Salud",
  },
  fr: {
    Programming: "Programmation",
    Marketing: "Marketing",
    Technology: "Technologie",
    SEO: "SEO",
    Trivia: "Culture générale",
    Academia: "Recherche",
    Translation: "Traduction",
    Roleplay: "Jeu de rôle",
    Science: "Science",
    Finance: "Finance",
    Legal: "Juridique",
    Health: "Santé",
  },
  pt: {
    Programming: "Programação",
    Marketing: "Marketing",
    Technology: "Tecnologia",
    SEO: "SEO",
    Trivia: "Conhecimentos gerais",
    Academia: "Academia",
    Translation: "Tradução",
    Roleplay: "Interpretação",
    Science: "Ciência",
    Finance: "Finanças",
    Legal: "Jurídico",
    Health: "Saúde",
  },
  ru: {
    Programming: "Программирование",
    Marketing: "Маркетинг",
    Technology: "Технологии",
    SEO: "SEO",
    Trivia: "Общие вопросы",
    Academia: "Наука и учёба",
    Translation: "Перевод",
    Roleplay: "Ролевые игры",
    Science: "Наука",
    Finance: "Финансы",
    Legal: "Право",
    Health: "Здоровье",
  },
  ja: {
    Programming: "プログラミング",
    Marketing: "マーケティング",
    Technology: "テクノロジー",
    SEO: "SEO",
    Trivia: "雑学",
    Academia: "学術",
    Translation: "翻訳",
    Roleplay: "ロールプレイ",
    Science: "科学",
    Finance: "金融",
    Legal: "法務",
    Health: "ヘルスケア",
  },
  vi: {
    Programming: "Lập trình",
    Marketing: "Tiếp thị",
    Technology: "Công nghệ",
    SEO: "SEO",
    Trivia: "Kiến thức chung",
    Academia: "Học thuật",
    Translation: "Dịch thuật",
    Roleplay: "Nhập vai",
    Science: "Khoa học",
    Finance: "Tài chính",
    Legal: "Pháp lý",
    Health: "Sức khỏe",
  },
  de: {
    Programming: "Programmierung",
    Marketing: "Marketing",
    Technology: "Technologie",
    SEO: "SEO",
    Trivia: "Allgemeinwissen",
    Academia: "Wissenschaft",
    Translation: "Übersetzung",
    Roleplay: "Rollenspiel",
    Science: "Naturwissenschaft",
    Finance: "Finanzen",
    Legal: "Recht",
    Health: "Gesundheit",
  },
  id: {
    Programming: "Pemrograman",
    Marketing: "Pemasaran",
    Technology: "Teknologi",
    SEO: "SEO",
    Trivia: "Pengetahuan umum",
    Academia: "Akademik",
    Translation: "Terjemahan",
    Roleplay: "Bermain peran",
    Science: "Sains",
    Finance: "Keuangan",
    Legal: "Hukum",
    Health: "Kesehatan",
  },
};

export function getDirectoryCopy(locale: Locale): DirectoryCopy {
  return DIRECTORY_COPY[locale] ?? DIRECTORY_COPY.en;
}

export function categoryLabel(locale: Locale, category: string): string {
  return CATEGORY_LABELS[locale]?.[category] ?? category;
}

export function formatCount(template: string, count: number): string {
  return template.replace("{{count}}", count.toLocaleString());
}
