import type { Locale } from "@/lib/locales";

type PhoneBindingCopy = {
  title: string;
  description: string;
  callingCode: string;
  phone: string;
  phonePlaceholder: string;
  code: string;
  codePlaceholder: string;
  send: string;
  submit: string;
  later: string;
  unavailable: string;
  close: string;
};

export const phoneBindingCopy: Record<Locale, PhoneBindingCopy> = {
  en: {
    title: "Link your phone number",
    description: "Add a phone number to help keep your account secure.",
    callingCode: "Country calling code",
    phone: "Phone number",
    phonePlaceholder: "Enter your phone number",
    code: "Verification code",
    codePlaceholder: "Enter verification code",
    send: "Send code",
    submit: "Link phone number",
    later: "Maybe later",
    unavailable: "Phone verification will be available soon.",
    close: "Close",
  },
  zh: {
    title: "绑定手机号",
    description: "添加手机号，帮助保障你的账号安全。",
    callingCode: "国际区号",
    phone: "手机号",
    phonePlaceholder: "请输入手机号",
    code: "验证码",
    codePlaceholder: "请输入验证码",
    send: "获取验证码",
    submit: "绑定手机号",
    later: "暂时跳过",
    unavailable: "手机验证即将开放。",
    close: "关闭",
  },
  es: {
    title: "Vincula tu número de teléfono",
    description: "Añade un número de teléfono para proteger tu cuenta.",
    callingCode: "Prefijo internacional",
    phone: "Número de teléfono",
    phonePlaceholder: "Introduce tu número de teléfono",
    code: "Código de verificación",
    codePlaceholder: "Introduce el código",
    send: "Enviar código",
    submit: "Vincular teléfono",
    later: "Más tarde",
    unavailable: "La verificación telefónica estará disponible pronto.",
    close: "Cerrar",
  },
  fr: {
    title: "Associez votre numéro de téléphone",
    description: "Ajoutez un numéro de téléphone pour protéger votre compte.",
    callingCode: "Indicatif international",
    phone: "Numéro de téléphone",
    phonePlaceholder: "Saisissez votre numéro",
    code: "Code de vérification",
    codePlaceholder: "Saisissez le code",
    send: "Envoyer le code",
    submit: "Associer le téléphone",
    later: "Plus tard",
    unavailable: "La vérification par téléphone sera bientôt disponible.",
    close: "Fermer",
  },
  pt: {
    title: "Vincule seu número de telefone",
    description: "Adicione um número de telefone para proteger sua conta.",
    callingCode: "Código internacional",
    phone: "Número de telefone",
    phonePlaceholder: "Digite seu número",
    code: "Código de verificação",
    codePlaceholder: "Digite o código",
    send: "Enviar código",
    submit: "Vincular telefone",
    later: "Mais tarde",
    unavailable: "A verificação por telefone estará disponível em breve.",
    close: "Fechar",
  },
  ru: {
    title: "Привяжите номер телефона",
    description: "Добавьте номер телефона для защиты аккаунта.",
    callingCode: "Международный код",
    phone: "Номер телефона",
    phonePlaceholder: "Введите номер телефона",
    code: "Код подтверждения",
    codePlaceholder: "Введите код",
    send: "Получить код",
    submit: "Привязать телефон",
    later: "Позже",
    unavailable: "Подтверждение по телефону скоро станет доступно.",
    close: "Закрыть",
  },
  ja: {
    title: "電話番号を登録",
    description: "電話番号を追加してアカウントを保護しましょう。",
    callingCode: "国際電話番号",
    phone: "電話番号",
    phonePlaceholder: "電話番号を入力",
    code: "認証コード",
    codePlaceholder: "認証コードを入力",
    send: "コードを送信",
    submit: "電話番号を登録",
    later: "後で",
    unavailable: "電話番号認証は近日公開予定です。",
    close: "閉じる",
  },
  vi: {
    title: "Liên kết số điện thoại",
    description: "Thêm số điện thoại để bảo vệ tài khoản của bạn.",
    callingCode: "Mã gọi quốc tế",
    phone: "Số điện thoại",
    phonePlaceholder: "Nhập số điện thoại",
    code: "Mã xác minh",
    codePlaceholder: "Nhập mã xác minh",
    send: "Gửi mã",
    submit: "Liên kết số điện thoại",
    later: "Để sau",
    unavailable: "Tính năng xác minh điện thoại sẽ sớm ra mắt.",
    close: "Đóng",
  },
  de: {
    title: "Telefonnummer verknüpfen",
    description: "Füge eine Telefonnummer hinzu, um dein Konto zu schützen.",
    callingCode: "Ländervorwahl",
    phone: "Telefonnummer",
    phonePlaceholder: "Telefonnummer eingeben",
    code: "Bestätigungscode",
    codePlaceholder: "Code eingeben",
    send: "Code senden",
    submit: "Telefon verknüpfen",
    later: "Später",
    unavailable: "Die Telefonverifizierung ist bald verfügbar.",
    close: "Schließen",
  },
  id: {
    title: "Tautkan nomor telepon",
    description: "Tambahkan nomor telepon untuk melindungi akun Anda.",
    callingCode: "Kode negara",
    phone: "Nomor telepon",
    phonePlaceholder: "Masukkan nomor telepon",
    code: "Kode verifikasi",
    codePlaceholder: "Masukkan kode verifikasi",
    send: "Kirim kode",
    submit: "Tautkan telepon",
    later: "Nanti saja",
    unavailable: "Verifikasi telepon akan segera tersedia.",
    close: "Tutup",
  },
};
