import type { Locale } from "./locales";

export type PromptGalleryPickerCopy = {
  allModels: string;
  allTags: string;
  clearFilters: string;
  copiedPrompt: string;
  copiedSelection: string;
  copyPrompt: string;
  copySelection: string;
  description: string;
  deselect: string;
  emptyBody: string;
  emptyTitle: string;
  eyebrow: string;
  errorBody: string;
  errorTitle: string;
  modelLabel: string;
  searchPlaceholder: string;
  select: string;
  selected: string;
  sourceLabel: string;
  title: string;
  total: string;
  translationLabel: string;
  visible: string;
  tagLabel: string;
};

const copy: Record<Locale, PromptGalleryPickerCopy> = {
  en: {
    allModels: "All models",
    allTags: "All tags",
    clearFilters: "Clear filters",
    copiedPrompt: "Copied",
    copiedSelection: "Selection copied",
    copyPrompt: "Copy prompt",
    copySelection: "Copy selected slugs",
    description: "A temporary local picker fed by the live prompt-gallery API. Choose the images you want to use in the Playground.",
    deselect: "Remove",
    emptyBody: "Try another keyword or clear the filters.",
    emptyTitle: "No matching images",
    eyebrow: "Temporary local picker",
    errorBody: "The prompt-gallery feed could not be loaded. Check the API origin and refresh.",
    errorTitle: "Feed unavailable",
    modelLabel: "Model",
    searchPlaceholder: "Search titles, prompts, tags, or models…",
    select: "Select",
    selected: "selected",
    sourceLabel: "via",
    title: "Pick Playground images",
    total: "total",
    translationLabel: "English translation",
    visible: "showing",
    tagLabel: "Tag",
  },
  zh: {
    allModels: "全部模型",
    allTags: "全部标签",
    clearFilters: "清空筛选",
    copiedPrompt: "已复制",
    copiedSelection: "已复制选择结果",
    copyPrompt: "复制提示词",
    copySelection: "复制已选标识",
    description: "由提示词图库接口驱动的临时本地挑选页。先挑出想放进 Playground 的图片。",
    deselect: "移除",
    emptyBody: "换个关键词，或清空筛选条件再试。",
    emptyTitle: "没有匹配的图片",
    eyebrow: "临时本地挑选页",
    errorBody: "提示词图库接口暂时无法加载，请检查 API 地址后刷新。",
    errorTitle: "接口暂不可用",
    modelLabel: "模型",
    searchPlaceholder: "搜索标题、提示词、标签或模型……",
    select: "选择",
    selected: "已选",
    sourceLabel: "来源",
    title: "挑选 Playground 图片",
    total: "总数",
    translationLabel: "英文翻译",
    visible: "当前显示",
    tagLabel: "标签",
  },
  es: {
    allModels: "Todos los modelos",
    allTags: "Todas las etiquetas",
    clearFilters: "Limpiar filtros",
    copiedPrompt: "Copiado",
    copiedSelection: "Selección copiada",
    copyPrompt: "Copiar prompt",
    copySelection: "Copiar slugs seleccionados",
    description: "Selector local temporal conectado al feed de prompts. Elige las imágenes que quieras usar en Playground.",
    deselect: "Quitar",
    emptyBody: "Prueba otra palabra clave o limpia los filtros.",
    emptyTitle: "No hay imágenes coincidentes",
    eyebrow: "Selector local temporal",
    errorBody: "No se pudo cargar el feed de prompts. Comprueba el origen de la API y actualiza.",
    errorTitle: "Feed no disponible",
    modelLabel: "Modelo",
    searchPlaceholder: "Buscar títulos, prompts, etiquetas o modelos…",
    select: "Seleccionar",
    selected: "seleccionadas",
    sourceLabel: "vía",
    title: "Elegir imágenes para Playground",
    total: "total",
    translationLabel: "Traducción al inglés",
    visible: "mostrando",
    tagLabel: "Etiqueta",
  },
  fr: {
    allModels: "Tous les modèles",
    allTags: "Tous les tags",
    clearFilters: "Effacer les filtres",
    copiedPrompt: "Copié",
    copiedSelection: "Sélection copiée",
    copyPrompt: "Copier le prompt",
    copySelection: "Copier les slugs sélectionnés",
    description: "Sélecteur local temporaire alimenté par le flux de prompts. Choisissez les images à utiliser dans Playground.",
    deselect: "Retirer",
    emptyBody: "Essayez un autre mot-clé ou effacez les filtres.",
    emptyTitle: "Aucune image correspondante",
    eyebrow: "Sélecteur local temporaire",
    errorBody: "Le flux de prompts n'a pas pu être chargé. Vérifiez l'origine de l'API et actualisez.",
    errorTitle: "Flux indisponible",
    modelLabel: "Modèle",
    searchPlaceholder: "Rechercher titres, prompts, tags ou modèles…",
    select: "Sélectionner",
    selected: "sélectionnées",
    sourceLabel: "via",
    title: "Choisir les images Playground",
    total: "total",
    translationLabel: "Traduction anglaise",
    visible: "affichées",
    tagLabel: "Tag",
  },
  pt: {
    allModels: "Todos os modelos",
    allTags: "Todas as tags",
    clearFilters: "Limpar filtros",
    copiedPrompt: "Copiado",
    copiedSelection: "Seleção copiada",
    copyPrompt: "Copiar prompt",
    copySelection: "Copiar slugs selecionados",
    description: "Seletor local temporário alimentado pelo feed de prompts. Escolha as imagens que deseja usar no Playground.",
    deselect: "Remover",
    emptyBody: "Tente outra palavra-chave ou limpe os filtros.",
    emptyTitle: "Nenhuma imagem encontrada",
    eyebrow: "Seletor local temporário",
    errorBody: "Não foi possível carregar o feed de prompts. Verifique a origem da API e atualize.",
    errorTitle: "Feed indisponível",
    modelLabel: "Modelo",
    searchPlaceholder: "Buscar títulos, prompts, tags ou modelos…",
    select: "Selecionar",
    selected: "selecionadas",
    sourceLabel: "via",
    title: "Escolher imagens do Playground",
    total: "total",
    translationLabel: "Tradução para inglês",
    visible: "exibindo",
    tagLabel: "Tag",
  },
  ru: {
    allModels: "Все модели",
    allTags: "Все теги",
    clearFilters: "Сбросить фильтры",
    copiedPrompt: "Скопировано",
    copiedSelection: "Выбор скопирован",
    copyPrompt: "Скопировать prompt",
    copySelection: "Скопировать выбранные slug",
    description: "Временный локальный выборщик из ленты prompt'ов. Выберите изображения для Playground.",
    deselect: "Убрать",
    emptyBody: "Попробуйте другой запрос или сбросьте фильтры.",
    emptyTitle: "Подходящих изображений нет",
    eyebrow: "Временный локальный выборщик",
    errorBody: "Ленту prompt'ов не удалось загрузить. Проверьте адрес API и обновите страницу.",
    errorTitle: "Лента недоступна",
    modelLabel: "Модель",
    searchPlaceholder: "Поиск по заголовку, prompt, тегу или модели…",
    select: "Выбрать",
    selected: "выбрано",
    sourceLabel: "источник",
    title: "Выберите изображения Playground",
    total: "всего",
    translationLabel: "Перевод на английский",
    visible: "показано",
    tagLabel: "Тег",
  },
  ja: {
    allModels: "すべてのモデル",
    allTags: "すべてのタグ",
    clearFilters: "フィルターをクリア",
    copiedPrompt: "コピー済み",
    copiedSelection: "選択内容をコピーしました",
    copyPrompt: "プロンプトをコピー",
    copySelection: "選択した slug をコピー",
    description: "プロンプト API のデータを使う一時ローカル選択ページです。Playground に使う画像を選んでください。",
    deselect: "外す",
    emptyBody: "別のキーワードを試すか、フィルターをクリアしてください。",
    emptyTitle: "一致する画像がありません",
    eyebrow: "一時ローカル選択ページ",
    errorBody: "プロンプトフィードを読み込めませんでした。API の接続先を確認して更新してください。",
    errorTitle: "フィードを利用できません",
    modelLabel: "モデル",
    searchPlaceholder: "タイトル、プロンプト、タグ、モデルを検索…",
    select: "選択",
    selected: "件選択",
    sourceLabel: "出典",
    title: "Playground 用画像を選ぶ",
    total: "合計",
    translationLabel: "英訳",
    visible: "表示中",
    tagLabel: "タグ",
  },
  vi: {
    allModels: "Tất cả model",
    allTags: "Tất cả tag",
    clearFilters: "Xóa bộ lọc",
    copiedPrompt: "Đã sao chép",
    copiedSelection: "Đã sao chép lựa chọn",
    copyPrompt: "Sao chép prompt",
    copySelection: "Sao chép slug đã chọn",
    description: "Trình chọn cục bộ tạm thời lấy dữ liệu từ API prompt. Hãy chọn ảnh muốn dùng trong Playground.",
    deselect: "Bỏ chọn",
    emptyBody: "Thử từ khóa khác hoặc xóa bộ lọc.",
    emptyTitle: "Không có ảnh phù hợp",
    eyebrow: "Trình chọn cục bộ tạm thời",
    errorBody: "Không thể tải feed prompt. Kiểm tra địa chỉ API rồi tải lại.",
    errorTitle: "Feed không khả dụng",
    modelLabel: "Model",
    searchPlaceholder: "Tìm tiêu đề, prompt, tag hoặc model…",
    select: "Chọn",
    selected: "đã chọn",
    sourceLabel: "nguồn",
    title: "Chọn ảnh cho Playground",
    total: "tổng",
    translationLabel: "Bản dịch tiếng Anh",
    visible: "đang hiển thị",
    tagLabel: "Tag",
  },
  de: {
    allModels: "Alle Modelle",
    allTags: "Alle Tags",
    clearFilters: "Filter löschen",
    copiedPrompt: "Kopiert",
    copiedSelection: "Auswahl kopiert",
    copyPrompt: "Prompt kopieren",
    copySelection: "Ausgewählte Slugs kopieren",
    description: "Temporärer lokaler Picker aus dem Prompt-Feed. Wähle die Bilder für das Playground aus.",
    deselect: "Entfernen",
    emptyBody: "Versuche ein anderes Stichwort oder lösche die Filter.",
    emptyTitle: "Keine passenden Bilder",
    eyebrow: "Temporärer lokaler Picker",
    errorBody: "Der Prompt-Feed konnte nicht geladen werden. Prüfe die API-Adresse und aktualisiere.",
    errorTitle: "Feed nicht verfügbar",
    modelLabel: "Modell",
    searchPlaceholder: "Titel, Prompts, Tags oder Modelle suchen…",
    select: "Auswählen",
    selected: "ausgewählt",
    sourceLabel: "via",
    title: "Playground-Bilder auswählen",
    total: "gesamt",
    translationLabel: "Englische Übersetzung",
    visible: "angezeigt",
    tagLabel: "Tag",
  },
  id: {
    allModels: "Semua model",
    allTags: "Semua tag",
    clearFilters: "Hapus filter",
    copiedPrompt: "Disalin",
    copiedSelection: "Pilihan disalin",
    copyPrompt: "Salin prompt",
    copySelection: "Salin slug yang dipilih",
    description: "Pemilih lokal sementara dari feed prompt. Pilih gambar yang ingin digunakan di Playground.",
    deselect: "Hapus",
    emptyBody: "Coba kata kunci lain atau hapus filter.",
    emptyTitle: "Tidak ada gambar yang cocok",
    eyebrow: "Pemilih lokal sementara",
    errorBody: "Feed prompt tidak dapat dimuat. Periksa asal API lalu muat ulang.",
    errorTitle: "Feed tidak tersedia",
    modelLabel: "Model",
    searchPlaceholder: "Cari judul, prompt, tag, atau model…",
    select: "Pilih",
    selected: "dipilih",
    sourceLabel: "sumber",
    title: "Pilih gambar Playground",
    total: "total",
    translationLabel: "Terjemahan Inggris",
    visible: "ditampilkan",
    tagLabel: "Tag",
  },
};

export function getPromptGalleryPickerCopy(locale: Locale): PromptGalleryPickerCopy {
  return copy[locale] ?? copy.en;
}
