/**
 * Industry briefs for the video prompt library.
 *
 * These are request blueprints, not claims that the poster was generated by
 * the model on the page.  The reference clips are deliberately object- and
 * environment-led so the gallery never quietly turns into a people/UGC
 * showcase.  A visitor can replace the bracketed values and send the brief
 * from the single playground example above.
 */
export type VideoPromptTemplate = {
  id: string;
  label: string;
  prompt: string;
  ratio: string;
  duration: number;
  poster: string;
  /** A playable reference clip; templates never claim it was generated by the page model. */
  video: string;
  tags: readonly string[];
};

const PRODUCT_ASSET = "/assets/model-examples/product-macro.png";
const FOOD_ASSET = "/assets/model-examples/food-motion.png";
const HOTEL_ASSET = "/assets/model-examples/image2/flatkey-image2-hotel.png";
const VEHICLE_ASSET = "/assets/model-examples/seedance-f1-wet-track.png";
const UI_ASSET = "/assets/prompts/awesome-images/saas-hero-phone.png";
const LANDSCAPE_ASSET = "/assets/model-showcase/coastal-landmark.png";
const CDN_VIDEO_BASE = "https://cdn.shulex-voc.com/flatkey/model-media/sample";
const cdnVideo = (slug: string) => `${CDN_VIDEO_BASE}/${slug}.mp4`;

const PRODUCT_VIDEO = "/assets/model-examples/product-macro.mp4";
const FOOD_VIDEO = "/assets/model-examples/food-motion.mp4";
const VEHICLE_VIDEO = "/assets/model-examples/seedance-f1-wet-track.mp4";
const PRODUCT_REVEAL_VIDEO = "/assets/cli/product-reveal.mp4";
const PRODUCT_VARIANTS_VIDEO = "/assets/cli/localized-variants.mp4";
const UI_MOTION_VIDEO = "/assets/cli/flatkey-seedance-brand-film.mp4";
const LANDSCAPE_VIDEO = "/assets/model-showcase/coastal-landmark.mp4";

export const VIDEO_PROMPT_TEMPLATES: readonly VideoPromptTemplate[] = [
  {
    id: "product-launch",
    label: "Product macro",
    prompt:
      "For ecommerce and consumer-brand teams, create a 6-second 9:16 product launch clip for [product]. Keep the supplied package, materials, proportions, and brand mark exact. Begin with a locked macro of the sealed package, make one slow 180-degree orbit, then settle into a front hero frame with safe space for a call to action. Use a clean studio tabletop, softbox key light, controlled reflections, crisp texture, and one subtle mechanical sound. No people, hands, faces, mannequins, extra products, invented text, watermark, or unsupported claims.",
    ratio: "9:16",
    duration: 6,
    poster: PRODUCT_ASSET,
    video: PRODUCT_VIDEO,
    tags: ["ecommerce", "consumer brands", "product film"],
  },
  {
    id: "food-beverage-loop",
    label: "Food and beverage",
    prompt:
      "For restaurant, beverage, and packaged-food teams, create a 6-second 9:16 menu or social clip for [dish or drink]. Show only the food and its serving vessel: ingredients assemble, steam rises, and one pour or cut completes the action. Move from overhead to a 45-degree hero angle in one continuous shot, with warm natural light, appetizing color, and a clean countertop. No people, hands, utensils entering from off-screen, labels, fake text, or extra portions.",
    ratio: "9:16",
    duration: 6,
    poster: FOOD_ASSET,
    video: FOOD_VIDEO,
    tags: ["restaurant", "beverage", "food packaging"],
  },
  {
    id: "hospitality-walkthrough",
    label: "Hospitality and travel",
    prompt:
      "For hotel, resort, and real-estate marketing teams, create a 10-second 16:9 property walkthrough of [room, lobby, or view]. Start at the doorway, make one smooth gimbal move through the space, reveal the hero view, and preserve architecture, furniture, materials, and daylight direction. Keep the room empty, staged, and booking-ready with safe space for room type and price copy. No people, silhouettes, mirrors showing people, signs, logos, or warped geometry.",
    ratio: "16:9",
    duration: 10,
    poster: HOTEL_ASSET,
    video: LANDSCAPE_VIDEO,
    tags: ["hospitality", "property marketing", "travel"],
  },
  {
    id: "mobility-launch",
    label: "Product motion",
    prompt:
      "For automotive and mobility teams, create a 6-second 16:9 launch shot for [vehicle or mobility product]. Keep the vehicle identity, wheel count, paint, and proportions exact. Use a low tracking camera for one controlled turn on a clean test road, then hold a three-quarter hero frame with realistic tire contact, reflections, and restrained motion blur. No driver, passengers, crowds, license plates, logos, text, duplicate vehicles, or deformation.",
    ratio: "16:9",
    duration: 6,
    poster: VEHICLE_ASSET,
    video: VEHICLE_VIDEO,
    tags: ["automotive", "mobility", "launch film"],
  },
  {
    id: "saas-product-demo",
    label: "Apps",
    prompt:
      "For SaaS and product teams, create an 8-second 16:9 UI demo for [app or workflow]. Animate only the supplied interface: open the dashboard, highlight [feature], complete one data transition, and end on a stable results state. Keep every supplied label, icon, number, and layout pixel-consistent; use a deliberate cursor path and screen-recording clarity. No people, hands, avatars, faces, fake code, notification spam, or brand changes.",
    ratio: "16:9",
    duration: 8,
    poster: UI_ASSET,
    video: UI_MOTION_VIDEO,
    tags: ["SaaS", "product demo", "UI motion"],
  },
  {
    id: "architecture-reveal",
    label: "Cinematic landscape",
    prompt:
      "For architecture, urban-design, and film-previs teams, create a 10-second 16:9 environment reveal of [building or structure]. Begin on a wide exterior, make one slow crane or orbit, pass through the entrance, and end on a strong geometric silhouette. Maintain scale, vanishing lines, materials, weather, and shadow continuity; keep the environment empty and physically plausible. No people, cars with occupants, signage, logos, text, or extra buildings.",
    ratio: "16:9",
    duration: 10,
    poster: LANDSCAPE_ASSET,
    video: LANDSCAPE_VIDEO,
    tags: ["architecture", "urban design", "film previs"],
  },
];

/**
 * Each dedicated video page gets its own six-poster reference set and six
 * playable clips. The sets intentionally rotate industries and visual
 * language: the cards are not a shared Seedance clip list disguised as
 * model-specific output.
 */
const VIDEO_MODEL_POSTER_SETS: Record<string, readonly string[]> = {
  "seedance-2-5": [
    PRODUCT_ASSET,
    FOOD_ASSET,
    HOTEL_ASSET,
    VEHICLE_ASSET,
    UI_ASSET,
    LANDSCAPE_ASSET,
  ],
  "seedance-2-0": [
    "/assets/cli/campaign-hero.png",
    "/assets/cli/localized-variants.png",
    "/assets/model-examples/image2/skincare.png",
    "/assets/prompts/awesome-images/sports-shoe.png",
    "/assets/model-examples/image2/saas.png",
    "/assets/model-cover-art/v2/observatory-gouache.png",
  ],
  "seedance-2-0-pro": [
    "/assets/cli/product-reveal.png",
    "/assets/prompts/awesome-images/ecommerce-skincare.png",
    "/assets/model-examples/image2/coffee.png",
    "/assets/model-showcase/racing-chase.png",
    "/assets/prompts/awesome-images/ai-agent-poster.png",
    "/assets/model-cover-art/v2/monastery-oil.png",
  ],
  "seedance-2-0-fast": [
    "/assets/model-examples/product-macro-reference.png",
    "/assets/prompts/awesome-images/liquid-bento.png",
    HOTEL_ASSET,
    VEHICLE_ASSET,
    UI_ASSET,
    "/assets/model-cover-art/v2/storm-collage.png",
  ],
  "seedance-2-0-mini": [
    "/assets/cli/campaign-hero.png",
    FOOD_ASSET,
    HOTEL_ASSET,
    "/assets/prompts/awesome-images/sports-shoe.png",
    "/assets/prompts/awesome-images/ai-agent-poster.png",
    "/assets/model-cover-art/v2/aurora-expressionist.png",
  ],
  "minimax-h3": [
    "/assets/cli/product-reveal.png",
    "/assets/model-examples/image2/coffee.png",
    "/assets/model-examples/image2/skincare.png",
    "/assets/model-showcase/racing-chase.png",
    "/assets/model-examples/image2/saas.png",
    "/assets/model-cover-art/v2/stained-sea.png",
  ],
  "grok-imagine-video": [
    "/assets/prompts/awesome-images/ecommerce-skincare.png",
    "/assets/prompts/awesome-images/liquid-bento.png",
    HOTEL_ASSET,
    LANDSCAPE_ASSET,
    UI_ASSET,
    "/assets/model-cover-art/v2/storm-collage.png",
  ],
  "grok-imagine-video-1-5": [
    "/assets/cli/localized-variants.png",
    PRODUCT_ASSET,
    "/assets/model-examples/image2/coffee.png",
    VEHICLE_ASSET,
    "/assets/prompts/awesome-images/ai-agent-poster.png",
    "/assets/model-cover-art/v2/observatory-gouache.png",
  ],
  "veo-3-1-generate-preview": [
    "/assets/cli/campaign-hero.png",
    FOOD_ASSET,
    HOTEL_ASSET,
    "/assets/model-showcase/racing-chase.png",
    "/assets/model-examples/image2/saas.png",
    "/assets/model-cover-art/v2/ink-waterfall.png",
  ],
  "veo-3-1-fast-generate-preview": [
    "/assets/cli/product-reveal.png",
    "/assets/model-examples/image2/skincare.png",
    HOTEL_ASSET,
    "/assets/prompts/awesome-images/sports-shoe.png",
    "/assets/prompts/awesome-images/liquid-bento.png",
    "/assets/model-cover-art/v2/bamboo-linocut.png",
  ],
};

/**
 * Playable reference clips for each dedicated video page. Most are the
 * model-specific CDN samples already used by the site; local object-only
 * clips fill pages whose upstream sample set is unavailable. They are paired
 * with the six industry briefs above, but remain explicitly labeled as
 * templates rather than results produced by the model on the page.
 */
const VIDEO_MODEL_VIDEO_SETS: Record<string, readonly string[]> = {
  "seedance-2-5": [PRODUCT_VIDEO, FOOD_VIDEO, VEHICLE_VIDEO, PRODUCT_REVEAL_VIDEO, PRODUCT_VARIANTS_VIDEO, LANDSCAPE_VIDEO],
  "seedance-2-0": [
    cdnVideo("seedance-2-0-w1"),
    cdnVideo("seedance-2-0-w2"),
    cdnVideo("seedance-2-0-w3"),
    cdnVideo("seedance-2-0-w4"),
    PRODUCT_VIDEO,
    LANDSCAPE_VIDEO,
  ],
  "seedance-2-0-pro": [
    cdnVideo("seedance-2-0-pro-l1"),
    cdnVideo("seedance-2-0-pro-l2"),
    cdnVideo("seedance-2-0-pro-l3"),
    cdnVideo("seedance-2-0-pro-w2"),
    cdnVideo("seedance-2-0-pro-w3"),
    cdnVideo("seedance-2-0-pro-w4"),
  ],
  "seedance-2-0-fast": [
    cdnVideo("seedance-2-0-fast-l1"),
    cdnVideo("seedance-2-0-fast-l2"),
    cdnVideo("seedance-2-0-fast-l3"),
    cdnVideo("seedance-2-0-fast-w1"),
    cdnVideo("seedance-2-0-fast-w2"),
    cdnVideo("seedance-2-0-fast-w3"),
  ],
  "seedance-2-0-mini": [
    cdnVideo("seedance-2-0-mini-w1"),
    cdnVideo("seedance-2-0-mini-w2"),
    cdnVideo("seedance-2-0-mini-w3"),
    cdnVideo("seedance-2-0-mini-w4"),
    cdnVideo("seedance-2-0-mini-l1"),
    cdnVideo("seedance-2-0-mini-l2"),
  ],
  "minimax-h3": [
    cdnVideo("minimax-h3-l2"),
    cdnVideo("minimax-h3-l3"),
    cdnVideo("minimax-h3-w2"),
    cdnVideo("minimax-h3-w3"),
    cdnVideo("minimax-h3-w4"),
    PRODUCT_VIDEO,
  ],
  "grok-imagine-video": [
    cdnVideo("grok-imagine-video-l1"),
    cdnVideo("grok-imagine-video-l2"),
    cdnVideo("grok-imagine-video-l3"),
    cdnVideo("grok-imagine-video-l4"),
    cdnVideo("grok-imagine-video-w1"),
    cdnVideo("grok-imagine-video-w4"),
  ],
  "grok-imagine-video-1-5": [
    cdnVideo("grok-imagine-video-1-5-l1"),
    cdnVideo("grok-imagine-video-1-5-l2"),
    cdnVideo("grok-imagine-video-1-5-l4"),
    cdnVideo("grok-imagine-video-1-5-w1"),
    cdnVideo("grok-imagine-video-1-5-w2"),
    PRODUCT_REVEAL_VIDEO,
  ],
  "veo-3-1-generate-preview": [
    cdnVideo("veo-3-1-generate-preview-w2"),
    cdnVideo("veo-3-1-generate-preview-l4"),
    FOOD_VIDEO,
    VEHICLE_VIDEO,
    PRODUCT_VIDEO,
    LANDSCAPE_VIDEO,
  ],
  "veo-3-1-fast-generate-preview": [
    PRODUCT_VIDEO,
    FOOD_VIDEO,
    VEHICLE_VIDEO,
    PRODUCT_REVEAL_VIDEO,
    PRODUCT_VARIANTS_VIDEO,
    LANDSCAPE_VIDEO,
  ],
};

// The brief stays industry-led, while this short model note makes the copy
// useful on the page where it appears: the same product shot can ask for
// continuity, speed, natural light, or compact motion depending on the model.
// Keeping the note in the prompt also means copying a card preserves the
// model-specific intent instead of silently collapsing every page to one
// generic sentence.
const VIDEO_MODEL_PROMPT_NOTES: Record<string, string> = {
  "seedance-2-5": "Favor multi-shot continuity and a clean, editable ending so the clip can be extended without changing the subject.",
  "seedance-2-0": "Favor a single readable take with stable subject identity and a deliberate camera path.",
  "seedance-2-0-pro": "Favor layered depth, precise material response, and controlled transitions between the key beats.",
  "seedance-2-0-fast": "Favor an efficient one-take motion path with an immediate hook and no ornamental camera drift.",
  "seedance-2-0-mini": "Favor a simple subject, uncluttered staging, and high-contrast motion that remains legible at small sizes.",
  "minimax-h3": "Favor natural ambient timing, clear contact shadows, and a stable composition that can be rendered at multiple durations.",
  "grok-imagine-video": "Favor expressive but physically coherent motion, with one controlled visual surprise near the midpoint.",
  "grok-imagine-video-1-5": "Favor polished surface detail, decisive camera movement, and a strong final hero frame for campaign cutdowns.",
  "veo-3-1-generate-preview": "Favor naturalistic light changes, believable environmental motion, and a calm cinematic pace.",
  "veo-3-1-fast-generate-preview": "Favor compact transitions, clear silhouettes, and a production-ready result in the shortest readable beat.",
};

export const VIDEO_MODEL_IDS = Object.freeze(Object.keys(VIDEO_MODEL_POSTER_SETS));

export function getVideoPromptTemplateFallbackPosters(modelId: string): readonly string[] {
  const slug = modelId
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return VIDEO_MODEL_POSTER_SETS[slug] ?? [];
}

/** Return six industry templates only for pages with a dedicated video set. */
export function getVideoPromptTemplates(modelId: string): readonly VideoPromptTemplate[] {
  const slug = modelId
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const posters = getVideoPromptTemplateFallbackPosters(modelId);
  const videos = VIDEO_MODEL_VIDEO_SETS[slug];
  const note = VIDEO_MODEL_PROMPT_NOTES[slug];
  if (posters.length !== VIDEO_PROMPT_TEMPLATES.length || videos?.length !== VIDEO_PROMPT_TEMPLATES.length || !note) return [];
  return VIDEO_PROMPT_TEMPLATES.map((template, index) => ({
    ...template,
    poster: posters[index],
    video: videos[index],
    prompt: `${template.prompt} ${note}`,
  }));
}
